### ISSUE TITLE
PIXI.BitmapText - does not show characters

### ISSUE THREAD

**Issue by Triborg333** [pixijs/pixi.js#7253] opened 2021-02-19 22:03 UTC
Help me:)

PIXI.BitmapText - does not show characters For example: (!@$%^!@%^!@)

const app = new PIXI.Application({ 
    width: window.innerWidth,         // default: 800
    height: window.innerHeight,        // default: 600
    antialias: true,    // default: false
    transparent: false, // default: false
    resolution: 1,      // default: 1
	backgroundColor:0xFFFFFF
  }
);

document.body.appendChild(app.view);

const fontSize = 50;

const style = new PIXI.TextStyle({
		fill: "white",
		fontFamily: "Arial",
		fontSize: 68,
		fontWeight: "bolder",
		strokeThickness: 8
});

const font = PIXI.BitmapFont.from("fontName", style, { resolution: devicePixelRatio });

const name = new PIXI.BitmapText('!@$%^!@%^!@', {
	fontName: 'fontName',
	fontSize: 100,
});

app.stage.addChild(name)

Help me please:)

**Comment by bigtimebuddy** [comment] 2021-02-20 03:33
Where you are setting resolution in the BitmapFont options, there's an option called chars. You'll need to add special characters or use the ASCII preset to render those characters. Please refer to the documentation for that.

**Comment by bigtimebuddy** [comment] 2021-02-20 05:27
Duplicate of #7132

**Closed by bigtimebuddy** 2021-02-20 05:27 UTC
Labels: 👍 Not A Bug
