### ISSUE TITLE
Graphics generateCanvasTexture() bug

### ISSUE THREAD

**Issue by D-Hartley** [pixijs/pixi.js#3446] opened 2016-12-12 12:27 UTC
There is a bug when converting a graphics object to a texture.
Below is a pen that shows the issue.

[CodePen](http://codepen.io/davidhartley/pen/1c419f69b4ff3f53513144477da037ef)

Part of the texture is cut off at the bottom right.
This can be fixed in the pen by either uncommenting line 28 in the JS (which adds the original graphics object to the stage) or by going to the JS Settings (the cog next to JS) and changing the PIXI version from 4.2.1 to 4.1.1.

You will see the positioning of the line moves slightly and the bottom right is no longer cut off. Could be an issue with calculating graphics bounds during the texture generation when the graphics is not being rendered? The getBounds function always returns the correct values though.

**Comment by sivael** [comment] 2016-12-12 17:08
I have experienced similar effects.
The issue seems to stem from m.invert() function call - tx in my case was becoming -3999.5 which caused the cached items not to render at all(well, render off-image).

I have patched it in as 
//cacheAsBitmap.js from NPM line 284:
    if(this._zeroMatrix){
      m.tx = -bounds.x;
      m.ty = -bounds.y;
    }

And I'm simply setting the problematic elements' _zeroMatrix to true.

This fixes the issue for the two types of problematic items. 

The rest of the items I'm displaying, however works 100% properly to which I do not have an explanation.

I do no scaling nor skewing, just straight up hierarchic positioning 1:1.

I have personally no idea why it happens, or even if the cause is where I'm looking at, but including this seems to fix the issues for the problematic items.

Hope this helps.

**Comment by lincsanders** [comment] 2016-12-12 20:52
I put through a pull request for a fix I have proposed, feedback more than welcome. https://github.com/pixijs/pixi.js/pull/3447

**Comment by lincsanders** [comment] 2016-12-12 20:59
Woops scratch that entirely, I posted this in entirely the wrong place.

**Comment by Tigerwulf** [comment] 2016-12-19 16:47
Hey,

i have the same problem. A workaround is to change the position of the graphic object, befor you use '.generateCanvasTexture()'. In the CodePan example is enough to add the line "g.x +=1;" befor calling generateCanvasTexture.

It looks like that the size of the object is the right one, but it generate the texture from the 0,0 point. After changing position it will use the right origin point, to create the texture.

Also you can change the pivot of the root object. In this case it will use all time the 0,0 point of the root render object, to generate the texture. After changing position, its all fine.

Hope it will help to find and fix it.

**Comment by GoodBoyDigital** [comment] 2017-01-17 21:07
hello! just submitted a pr, works like a champ!

**Comment by GoodBoyDigital** [comment] 2017-01-19 21:50
closing cos its fixed 👍

**Closed by GoodBoyDigital** 2017-01-19 21:50 UTC
Labels: Domain: API, Plugin: Bounds, Plugin: Graphics, Type: Bug, Version: v4.x
