### ISSUE TITLE
pixi.js:15891 WebGL: INVALID_ENUM: activeTexture: texture unit out of range

### ISSUE THREAD

**Issue by zzzzzyb** [pixijs/pixi.js#3373] opened 2016-11-29 06:23 UTC
?

**Comment by zzzzzyb** [comment] 2016-11-29 06:25
when i  set a setTimeout to change text

**Comment by zzzzzyb** [comment] 2016-11-29 06:27
render appear flash screen

**Comment by kaansoral** [comment] 2016-11-29 07:38
++

This issue haunts me too, yet I don't know why it happens

**Comment by zzzzzyb** [comment] 2016-11-29 07:59
thanks

**Comment by themoonrat** [comment] 2016-11-30 16:39
@zzzzzyb Could you produce a jsfiddle with this issue please?

**Comment by EneaEntertainment** [comment] 2016-12-02 21:47
run the pen on mobile/chrome mobile emulator, you will spot mentioned error in browser console and some of the texts will be randomly changing. was ok in Pixi 4.0

[http://codepen.io/anon/pen/eBVJpN](http://codepen.io/anon/pen/eBVJpN)

[https://github.com/pixijs/pixi.js/blob/dev/src/core/utils/maxRecommendedTextures.js#L8](https://github.com/pixijs/pixi.js/blob/dev/src/core/utils/maxRecommendedTextures.js#L8)

this happens when text changes are not synced with animation frame and more than 4 textures are used

**Comment by staff0rd** [comment] 2016-12-03 00:43
Thx for the pen @EneaEntertainment.  Here it is again without the html; http://codepen.io/staff0rd/pen/XNZdPB?editors=0010

For the purposes of attempting to increase my very poor webgl experience, I took a look but was unable to determine why it's happening (i'm sure one of the others will find it tho).  How did you link it to maxRecommendedTextures?

**Comment by GoodBoyDigital** [comment] 2016-12-05 08:22
Yoyo! Assign this one to me :) once I get my internet back I will take a
look!

**Comment by finscn** [comment] 2016-12-08 15:14
If  change this line  https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js#L410

from 
```
if (rendererBoundTextures[group.ids[j]] !== currentTexture)
```
to 
```
if (group.ids[j] >= 0 && rendererBoundTextures[group.ids[j]] !== currentTexture)
```

This error will disappear.  But why ```group.ids[j]``` could be -1 ? Is this normal ？

And

The ```group.ids[j]``` could be -1 , Because that (I'm not sure) : 
the code at
https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js#L275-L295

Sometimes ,  ```t._enabled ``` always equals ```TICK``` , then the ```nextTexture._virtalBoundId``` always be ```-1```.

**Comment by finscn** [comment] 2016-12-08 15:27
There is a other way for fix this issue (maybe it's just palliative, not the key point )  :  
change
https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js#L275-L295
to 
```
                    if (nextTexture._virtalBoundId === -1)
                    {
                        for (let j = 0; j < MAX_TEXTURES; ++j)
                        {
                            const tIndex = (j + TEXTURE_TICK) % MAX_TEXTURES;

                            const t = boundTextures[tIndex];

                            if (t._enabled !== TICK)
                            {
                                TEXTURE_TICK++;

                                t._virtalBoundId = -1;

                                nextTexture._virtalBoundId = tIndex;

                                boundTextures[tIndex] = nextTexture;
                                break;
                            }
                        }
          // ****** Add these codes ****** //
                        if (nextTexture._virtalBoundId === -1)
                       {
                          //  nextTexture._virtalBoundId = 0 ?  is it ok?
                           nextTexture._virtalBoundId = TEXTURE_TICK % MAX_TEXTURES;
                       }
                    }
```

**Comment by antag0n1st** [comment] 2016-12-13 11:19
I have the same error with pixi 4.2.3
and in my case some of the images are flickering on the screen , just like a bad glitch from the 80s movie.

here is the stack:
> 

pixi.js:16592 WebGL: INVALID_ENUM: activeTexture: texture unit out of rangebindTexture 
@ pixi.js:16592flush 
@ pixi.js:20818stop 
@ pixi.js:20858setObjectRenderer 
@ pixi.js:16397_renderWebGL 
@ pixi.js:10599renderWebGL 
@ pixi.js:8379renderWebGL 
@ pixi.js:8383render 
@ pixi.js:16373Stage.update 
@ ...

**Comment by GoodBoyDigital** [comment] 2016-12-13 11:24
hi @antag0n1st - can I ask what device browser you are using?
also are you using filters / cacheAsBitmap at all?
cheers!

**Comment by kaansoral** [comment] 2016-12-13 11:30
I'm using a global container filter, but no cacheAsBitmap's, the glitches are similar, it also causes the game and webgl to crash, additionally, it causes system issues outside the game too, very rarely, I can observe momentary visual glitches in OSX

Thanks to this issue, the userbase of my game has been dwindling, many regular players are affected, I was waiting for an official fix, but I guess I need to find a solution myself too

**Comment by GoodBoyDigital** [comment] 2016-12-13 11:43
if you disable the filters, does the issue remain? cheers!
Unfortunatly a very busy time for me as the studio is wrapping up the client projects for the year...fun fun! This means its taking a little longer to get round to fixing this than I had hoped.

**Comment by kaansoral** [comment] 2016-12-13 11:58
<img width="467" alt="screen shot 2016-12-13 at 14 50 20" src="https://cloud.githubusercontent.com/assets/170243/21139395/b4d16a40-c143-11e6-9a2b-ee247fa95573.png">

Caught these in the logs, these are easy to reproduce, I don't know how they happen, but they seem to happen on their own - I caught 2 of these, and they both happened when the tab was in the background, so I don't know whether there might have been an accompanying glitch or not

So these ones seem to originate from pixi-display, but it's unclear whether pixi-display is the cause

Anyway, just an intermediary update, going to keep an active eye on the issue, and If I can detect how the issue happens, I can try toggling filters and other things too (I can't easily reproduce it on the non-live version of the game, so testing isn't trivial)

**Comment by GoodBoyDigital** [comment] 2016-12-13 12:11
totally understand! This bug is a sneaky one! If we can establish that the bug only occurs only when filters or pixi-display are being used that would really help narrow down where we can start looking.

Cheers!

**Comment by antag0n1st** [comment] 2016-12-13 13:36
@GoodBoyDigital I use google chrome on win7. 
No filters are used , no caching is used.
I loaded the project without the pixi-filters.js , and the result is the same.
The issue is reproducible every time. ( one of the images/sprite is flickering)

**Comment by GoodBoyDigital** [comment] 2016-12-13 13:53
any chance you can shar your code? ta!

**Comment by antag0n1st** [comment] 2016-12-13 14:09
Yes , 
https://drive.google.com/open?id=0B0Yxs7sVaoX3S3JLQ00wcEotclU
The project needs to be hosted under localhost , then:
Just click on last button saying "Flicker" , and it will open a screen where one of the buttons on the right side is flickering.

**Comment by GoodBoyDigital** [comment] 2016-12-16 23:05
Hey all! just put a PR up that should fix this 👍

**Comment by kaansoral** [comment] 2016-12-22 04:18
Is there an ETA for a build with the PR applied? :)

**Comment by DimaNazdratenko** [comment] 2016-12-27 14:09
Hi, I correctly understand that when I see warning WebGL: INVALID_ENUM: activeTexture: texture unit out of range, It is a bug which was fixed here https://github.com/pixijs/pixi.js/pull/3501

And I need update my pixi.js file and all will be ok?)))

Sorry for maybe stupid question, but I am newbie in dev and pixi too)))

**Comment by GoodBoyDigital** [comment] 2017-01-16 22:38
closing this for now as I believe it's saved in the latest dev branch 👍

**Closed by GoodBoyDigital** 2017-01-16 22:38 UTC
Labels: Domain: API, Plugin: Text, Renderer: WebGL, Status: Needs Investigation, Version: v4.x
