### ISSUE TITLE
no x and y offset on filters anymore in 3.0?

### ISSUE THREAD

**Issue by Esshahn** [pixijs/pixi.js#1898] opened 2015-06-15 13:18 UTC
I'm trying to recreate the "underwater" displacement effect, which doesn't seem to work anymore with 3.0. 
I just can't figure out how to achieve something like this: http://jsfiddle.net/glafarge/6h84bpnk/
Any hints?

**Comment by RoryPicko** [comment] 2015-06-15 13:26
on the documentation http://pixijs.github.io/docs/PIXI.filters.DisplacementFilter.html

**You can use this filter to apply all manor of crazy warping effects Currently the r property of the texture is used to offset the x and the g property of the texture is used to offset the y.**

**Comment by Esshahn** [comment] 2015-06-15 13:29
Thank you, yes I read that too, and if that works I have no idea how.

**Comment by englercj** [comment] 2015-06-15 14:11
Looks like we removed that stuff in favor of a matrix that does all those things for you in the vert shader:

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/filters/displacement/displacement.vert#L6

You can manipulate it via the `maskMatrix` property:

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/filters/displacement/DisplacementFilter.js#L34

I would probably be nice to have some getters/setters that manipulate this matrix for you.

**Comment by Esshahn** [comment] 2015-06-15 14:18
Thank you. Hm, whatever changes I make to maskMatrix doesn't change anything to the filter. Could you do me a big favor and show me a line of code or two that does what x and y did?
Probably the old way was more intuitive for me and some others too.

**Comment by Esshahn** [comment] 2015-06-16 12:07
Don't mind. I went back to 2.2.9, thanks anyway.

**Comment by Friksel** [comment] 2016-03-25 21:18
I'm having the exact same problem now by trying to update from 2.2.9 to 3.0.10... I guess we're not the only one missing a replacement for the filteroffset. Is this feature-request in the pipeline for version 4 (or maybe 3 still?) ?

**Comment by jesperlandberg** [comment] 2016-07-07 06:36
Is there any code example how this can be done yet?

**Comment by ivanpopelyshev** [comment] 2016-07-07 09:38
You can achieve it by moving displacementSprite around. MaskMatrix is calculated by position and scale of displacementSprite

**Comment by Friksel** [comment] 2016-07-07 14:47
@ivanpopelyshev 
Last months I tried lots of different things to move the displacement map around, without any luck. 
After your latest post I tried this, like in the example: 
(moving waterMapSprite.x with a greensock tween)...
> this.wmTl = new TimelineMax({repeat:-1});
> this.wmTl.to(this.waterMapSprite, 3, { x: this.canvas.width, ease: Linear.easeNone });

...it's not moving the displacement map. Instead it is flashing the output sometimes only. 
I see the example on the pixi website and when I do the same it's not moving at all.
I can't get my head around it. This should be something really easy, but it's driving me crazy...
For the record: everything was working perfectly fine in Pixi v2. But since version 3 couldn't get it to play nice anymore.

I found this example and it seems to be running on pixi v4.
http://pixijs.github.io/examples/index.html?s=filters&f=displacement-map.js&title=Displacement%20Map
btw Although this is moving the displacement map, this example isn't working well in Chrome. There is a drop out (repeated lines) left of the magnifier in the displacement map.

Are there any limitations to the displacement map I should know about?
Extra resources that should be loaded? Fileformat? max dimensions?
I'm out of ideas. :(

**Comment by GoodBoyDigital** [comment] 2016-08-09 19:45
closing as im sure this is fixed in v4 👍

**Closed by GoodBoyDigital** 2016-08-09 19:45 UTC
Labels: feature-request, Filters

**Comment by Friksel** [comment] 2016-08-10 14:24
Hey???? You're closing this because you're sure this is fixed??? So what's changed? The offset still isn't working in v4-rc3. And there is still no answer on how it should be done in v4. Where's this described in the docs? I'm probably missing something, but whatever I tried (and I tried A LOT!!), nothing seem to work with moving the displacement from pixi v3 up.

I really appreciate pixi a lot. I like it much better then createjs. but this thing is driving me crazy and I'm an advanced user, not a newby. I'm probably missing something, or I'm having some special combination of factors why it's not working here. 
Would be appreciated if you could provide some more information on how it should work now.

**Comment by ivanpopelyshev** [comment] 2016-08-10 14:27
Offset is made by moving displacementSprite. Please look at pixi examples. then at displacementFilter sources. There's a matrix that is "borrowed" from a virtual sprite, it has offset, rotation and all those stuff.

**Comment by Friksel** [comment] 2016-08-10 14:39
Thanks for your quick reaction @ivanpopelyshev . 
I was watching the example several times. And now I'm having the following (typescript), wich is only flashing the graphics instead of moving the displacement from left to right: 

```
// WATERMAP
this.waterMapSprite = this.getSpriteFromResources(this.settings.graphics['water'].displacementMapID);
this.waterMapFilter = new PIXI.filters.DisplacementFilter(this.waterMapSprite);
this.anim.filters = [this.waterMapFilter];

// FILTER ANIM
this.wmTl = new TimelineMax({repeat:-1});
this.wmTl.to(this.waterMapSprite, 3, { x: this.canvas.width, ease: Linear.easeNone });
```

btw The displacement map is a jpg of 512x512px.


I'm sorry, I can't find the example at this moment (and I'm on the move), but I believe I made this just like the latest v4 example. 

Thanks again for your help. Maybe you could tell me if I'm doing something wrong or this is some other weird thing?

**Comment by GoodBoyDigital** [comment] 2016-08-10 14:45
Hello, did ya add the this.waterMapSprite to the stage?

**Comment by Friksel** [comment] 2016-08-11 08:49
Thanks Matt. That was it. The mapSprite wasn't added to the stage. The displacement filter is now moving! Hooray! :)

There are two another things I need to solve right now:
**A- In v2, where the offset of the filter was tweened, the texture is repeating itself (tiling). But in v4 (moving the sprite instead of offsetting the filter), the sprite is just a single sprite, moving off the stage.** 
This breaks the 'flowing water'-effect on my project.
To solve A I can double my spriteimage to twice the canvas width to have a tiling-effect while moving from right to left. But that's obviously not ideal (redundant pixels, higher loadtimes). Is there a better way to do a sprite tiling for the filter? (would be great if a tilingsprite would work for this, not sure if this is possible though, I need to test that out).

**B- There seem to be something going on that's causing the filter to jump/flash on random intervals** (not being caused by the greensock timeline repeating). It seems like this is especially the case if the animation is just started, but is happening more times after that too. This was not the case in v2 where all movements in the same project were fluid. It seems like something is not being able to handle the performance, but it's not a heavy animation at all and it's all running on a desktop.

Any thoughts on this?

**Comment by ivanpopelyshev** [comment] 2016-08-11 10:53
A - it depends on your texture that you use as displacement. You have to specify that its repeated. It was by default in v2. "texture.baseTexture.wrapMode = PIXI.WRAP_MODES.REPEAT" - execute this after you load the texture.

B - I dont know, I need to be able reproduce that to fix

**Comment by Friksel** [comment] 2016-08-11 15:30
@ivanpopelyshev . This is really helpful. Changing the wrapMode made it work again. Thanks.

Unfortunately the stuttering in the displacementmap is still there. After some testing I found out tweening the displacement map is moving fine on itself without any stuttering. But when used inside my project, wich only moves some sprites with bubble-graphics inside water from bottom to top, the water (with the displacement map tween), starts stuttering on 'random' intervals.
This problem wasn't there when the animation was working with v2 and the offset. And to be honoust at the moment I cannot find any reason why the 'bubbles'-tweens can influence the displacement-tween.

So I'll do some more testing on that problem (and I'm open for suggestions ofcoarse!). But next to this stuttering, moving the displacement map is working as expected now! Thanks for your help!

**Comment by ivanpopelyshev** [comment] 2016-08-11 15:46
OK, I'll see what can we do about stuttering.

**Comment by Dairnon** [comment] 2017-01-11 20:19
So i recently made a new issue thread, but noticed this the next day when looking at more possible solutions. I have to say the studdering issue is still there and appears to be connectes to the filter scale... is there a possible fix for this?
