### ISSUE TITLE
PixiJS 4.5.0 mouse events wont trigger in Google Chrome using Wacom tablet

### ISSUE THREAD

**Issue by Qubica** [pixijs/pixi.js#3867] opened 2017-03-24 11:17 UTC
My Wacom Bamboo & Wacom Intuos Pro (up to date drivers) won't trigger mouseover / mouseout events in Chrome (v57) in the following example:

https://pixijs.github.io/examples/#/demos/interactivity.js

This interaction is working in Firefox and Safari.

The weird part is, when I use a mouse or touchpad on laptop the mouseover / mouseout the events do trigger.

Is there a way to fix this?

PixiJS 4.3.0 is working.

**Comment by bigtimebuddy** [comment] 2017-03-24 12:15
Related issue: https://github.com/pixijs/pixi.js/issues/3695#issuecomment-288448959

**Comment by englercj** [comment] 2017-04-17 22:08
Going to close this as a duplicate since it seems answered in a different thread.

**Comment by Qubica** [comment] 2017-04-20 12:36
The issue isn't resolved in: https://pixijs.github.io/examples/#/demos/interactivity.js

**Comment by englercj** [comment] 2017-04-20 14:30
@andrewstart Can you take a look at this?

**Comment by Qubica** [comment] 2017-04-28 10:04
Sorry to inform that the issue is still present. Let me know if you need more information about the issue.

**Comment by andrewstart** [comment] 2017-05-02 01:23
Still present using the latest dev?

**Comment by Qubica** [comment] 2017-05-08 09:38
yes, the issue is still present in the latest dev. 

a. when I roll over a button with a wacom pen, the rollover state isn't triggered.
b. when I do the same with the touchpad, it works. 
c. after using the touchpad, the rollover also works with the wacom pen. (which is pretty weird)

**Comment by andrewstart** [comment] 2017-05-08 12:14
Would you mind collecting some data for me? Using a `pointerdown` event, I'm curious what the `pointerType` and `pointerId` properties are on the original event, in each of those 3 situations.

**Comment by themoonrat** [comment] 2018-07-15 12:05
@Qubica Sorry to bug you again, but would it be possible to have another look at this please using latest?

**Closed** 2019-02-24 15:31 UTC
Labels: Domain: API, Plugin: Interaction Manager, Resolution: Won't Fix, Status: Needs Investigation, Type: Bug, Version: v4.x

**Comment by micsun-al** [comment] 2019-05-01 17:56
This reproduces for me with the current build.  Wacom tablets aren't really mainstream though I guess, is this uninteresting to address I guess?

**Comment by themoonrat** [comment] 2019-05-01 18:27
What browser? Could you put up a demonstration somewhere of the simplest code that doesn't work?
