### ISSUE TITLE
PIXI.loader: Spritesheet image will fail to load if Spritesheet was loaded with crossOrigin = true

### ISSUE THREAD

**Issue by H34D** [pixijs/pixi.js#2193] opened 2015-11-14 20:08 UTC
If i load a spritesheet with crossOrigin true it will not load the image from the meta section

		let options = {
			crossOrigin: true
		};

		PIXI.loader.add("sprites", "spritesheet.json", options);

PIXI 3.0.8

I have supplied a fix in the following commit: https://github.com/H34D/pixi.js/commit/c39e3786ddaec0f3fb91a0f492363b6703230a8f it would be cool if it makes it in the framework.

Regards,
H34D

**Comment by englercj** [comment] 2015-11-15 00:29
This is a bug in resource-loader, I'd post it there. Relevant code:

https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L65
https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L253-L256

**Comment by manelis** [comment] 2015-11-16 16:23
Is this the solution for this problem?

http://www.html5gamedevs.com/topic/17315-asset-loader-failed-to-load-element-cross-domain/#entry97499

**Comment by englercj** [comment] 2015-11-16 16:25
Not sure, because I don't know what your issue is specifically.

**Comment by manelis** [comment] 2015-11-16 16:30
I really cant share the example, but basically pixi is unable to load the texture when we use cloudfront.

The only thing that I have is the error that I posted there. It is not me that can put the textures on the cdn right now, but if you have any sugestion of what I can try when we can get back to it it would be usefull :)

I will try this fix at the time anyway, simply noticed this issue was here and decided to ask-

**Comment by englercj** [comment] 2015-11-16 16:34
If you set crossOrigin, your server need to enable CORS headers. Usually for an image off a CDN you don't need to worry about that, you can just load the image and the library will take care of it for you.

If you are having problems, open an issue on the resource-loader repository with a case the reproduces the error so I can debug it. Closing this now since it is unrelated to pixi.

**Closed by englercj** 2015-11-16 16:34 UTC

**Comment by JiDW** [comment] 2015-11-16 16:43
We use cloudfront with PIXI and it works. You need to configure S3 with a CORS policy xml file (google it) and configure cloudfront to copy the headers of the origin (by default, it won't).

Do not forget to invalidate your files when you test your fix, because your headers are cached with the files.

**Comment by H34D** [comment] 2015-11-16 21:08
i discoved this using aerobatic.io hosting out of bitbucket. i can reproduce it with the current version and its fixed with my fix.
