### ISSUE TITLE
[BUG] No mouseout event emitted when outside of mask

### ISSUE THREAD

**Issue by AleXNoD** [pixijs/pixi.js#5135] opened 2018-09-27 23:53 UTC
### Expected Behavior

I put any rectangle in the mask with the same dimensions, so, rect in rect-mask. When mouse is out I expect to see "mouseout" event.

### Current Behavior

There is no "mouseout" event.

### Possible Solution

Any ideas for temporary solution while you fix it?

### Environment

- `pixi.js` version: _e.g. 4.7.2_
- Browser: _e.g. Opera last ver_
- Device: _e.g. Desktop_

**Comment by AleXNoD** [comment] 2018-09-28 01:10
> Please provide a jsfiddle or codepen that demonstrates behavior. Thanks

Okay!
https://codepen.io/AleXNoD/pen/LgYZRO

Try to move cursor on and out of the blue rectangle and check the console.
With the mask we catch a bug (no "OUT" message). If you remove the mask, evetything will be ok.
I would be happy if you fix it.

**Comment by AleXNoD** [comment] 2018-09-29 20:11
I temporarily fixed it by using "mousemove" event that works correctly.
It's sad crutch, so the bug needs to be fixed completely.

**Comment by wilcobrouwer** [comment] 2018-10-09 18:13
I can confirm to have the same problem in practically the same situation. My solution was to add an additional container to the stage without a mask, containing the sprites which react to mouse events.

**Comment by stanislavpodolia** [comment] 2018-11-12 18:39
I have the same issue. Fixed by commenting out line 1050 in InteractionManager.js (line - hitTestChildren = false;). Actually we need to hitTestChildren, even if they're out of the mask, to handle pointerout events.

**Closed** 2019-02-24 15:30 UTC
Labels: Plugin: Interaction Manager, Resolution: Won't Fix, Version: v4.x

**Comment by AleXNoD** [comment] 2019-04-15 00:59
Why you closed it while it has not been fixed both in 4.x and 5.x versions?

**Comment by bigtimebuddy** [comment] 2019-04-15 02:54
We closed it because no one has picked up the issue. The pixi core team volunteers their time and has very limited resources and we recently auto-closed a bunch of issues that no one touched in awhile.

While this is definitely a known bug (masks + interaction) there are workarounds mentioned above. If someone wants to fix, PR welcome. The experts on interaction are @themoonrat and @andrewstart if someone needs guidance or review for this.

**Comment by AleXNoD** [comment] 2019-04-15 17:46
Thanks for the explanation! I understand that now.
I'd love to do that fixes in PIXI but I can't do it due the same reason. In addition I don't know the code.
This issue can be fixed by adding any construction that uses "mousemove" event and async checking of a next mouse position. It sounds hard but it works.
Anyway thanks for feedback. This bug is not critical because I have my own fix.

**Comment by bigtimebuddy** [comment] 2019-04-15 17:59
Thanks @AleXNoD for the suggested fix. Hopefully some hero will be willing to pick it up!
