### ISSUE TITLE
graphics lines cap style

### ISSUE THREAD

**Issue by PierBover** [pixijs/pixi.js#2686] opened 2016-06-29 04:38 UTC
In AS3 there is this option for lines in graphic objects.

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/CapsStyle.html

Is there anything similar in Pixi?

If not, could you tag this as a feature request?

**Comment by ivanpopelyshev** [comment] 2016-06-29 10:26
No. Graphics creates polygons, so you can add some methods there that will generate that kind of endings.

**Comment by GoodBoyDigital** [comment] 2016-08-09 20:47
closing as duplicate of #891

**Closed by GoodBoyDigital** 2016-08-09 20:47 UTC
