### ISSUE TITLE
PIXI 4.7.3 - mouseup/pointerup bug

### ISSUE THREAD

**Issue by Kamil93** [pixijs/pixi.js#4863] opened 2018-04-26 09:53 UTC
mouseup / pointerup bug

```
    this.on("pointerdown", (e) => {
      console.log("up", e.data.buttons); // left mouse button prints '1'
    });
    
    this.on("pointerup", (e) => {
      console.log("up", e.data.buttons); // any mouse button prints always '0'
    });
```

**Comment by gooderist** [comment] 2018-08-18 06:15
Hello, I'm trying to figure out what the bug is. What's exactly is the expected behavior?

On my setup, Firefox / macOS, "pointerup" only fires after I release all the buttons. "mouseup", on the other hand, will fire even if I'm holding other buttons down (ex: right click & hold, left click & release -> "mouseup" fires but not "pointerup"). That being the case, `onPointerUp` will only get called when `buttons === 0` (all buttons are released).

Here is [fiddle](https://jsfiddle.net/oeh0c1rz/7/) to test. This seems more like a browser issue than a PIXI one. Or am I completely off?

**Comment by gooderist** [comment] 2018-08-18 13:25
Hello @themoonrat - Thanks for the illuminating reply. It does seem like mouseup/down is the way to go especially since pointerup/down behavior varies between browsers. Maybe update the docs to recommend mouse events and call it a day?

**Comment by bigtimebuddy** [comment] 2018-08-18 13:44
Doc changes to clarify this welcomed!

**Comment by themoonrat** [comment] 2018-08-18 14:59
@gooderist Updated docs, yeah. I'll close this issue, because the behaviour is as intended, but updated docs to clarify the situation would be awesome.

I'd say that, in general, for the vast majority of use cases, using the 'pointer' events is much better. Because it covers mouse/touch/pen/whatever you want, and it just works. But in this specific case, where you're wanting to know the events of different mouse buttons as they are pressed; well then use the 'mouse' events that are there for just that reason :)

**Closed by themoonrat** 2018-08-18 14:59 UTC
Labels: Domain: API, Plugin: Interaction Manager, Status: Accepting PRs, Type: Bug, Version: v4.x
