### ISSUE TITLE
Drawing lines with vertexes always closes the shape in PIXI 3

### ISSUE THREAD

**Issue by kidkarma** [pixijs/pixi.js#2014] opened 2015-07-30 22:36 UTC
In PIXI 2, I could draw a line with a vertex like so:
```
var renderer = PIXI.autoDetectRenderer(800, 600, { antialias: true });
document.body.appendChild(renderer.view);
var stage = new PIXI.Stage();
var graphics = new PIXI.Graphics();
stage.addChild(graphics);

// draw line
graphics.lineStyle(5, 0xffffff);
graphics.moveTo(100, 200);
graphics.lineTo(200, 200);
graphics.lineTo(200, 100);
graphics.endFill();
renderer.render(stage);
```
Result using PIXI 2.2.9 works as expected.
![pixi2](https://cloud.githubusercontent.com/assets/5833505/8996785/a508437c-36cf-11e5-9db2-5804098c07ab.jpg)
http://jsfiddle.net/vzgoawzy/

---------------------------------------------------------------------------

When I do the same thing in PIXI 3.0.7, an extra unwanted line is drawn back to the starting point. This occurs with both  Canvas and WebGL renderers:
```
var renderer = PIXI.autoDetectRenderer(800, 600, { antialias: true });
document.body.appendChild(renderer.view);
var stage = new PIXI.Container();
var graphics = new PIXI.Graphics();
stage.addChild(graphics);

// draw line
graphics.lineStyle(5, 0xffffff);
graphics.moveTo(100, 200);
graphics.lineTo(200, 200);
graphics.lineTo(200, 100);
graphics.endFill();
renderer.render(stage);
```
Result has unexpected behaviour. An extra unwanted line is drawn back to the start.
![pixi3](https://cloud.githubusercontent.com/assets/5833505/8996782/a075dfa4-36cf-11e5-9eb5-f8f9cc8111ed.jpg)
http://jsfiddle.net/wanh44t4/

--------------------------------------------------------

Is there a way to get the top result using PIXI 3?

**Comment by kidkarma** [comment] 2015-07-30 22:59
It seems I can achieve the desired result by doing this:

`graphics.currentPath.shape.closed = false;`

But is there a better, more modular way to do this?

**Comment by englercj** [comment] 2015-07-31 02:42
Duplicate of #1892 I believe.

**Closed** 2015-07-31 02:42 UTC
Labels: duplicate
