### ISSUE TITLE
PIXI V4 - Resizing trimmed sprite from SpriteSheet seems to ignore trimmed area.

### ISSUE THREAD

**Issue by SlawomirMazgaj** [pixijs/pixi.js#2565] opened 2016-05-13 11:57 UTC
Hello again. I think there's something weird going on with resize. I was able to reproduce it using [SpriteShee Animation Example](http://pixijs.github.io/examples/index.html?s=basics&f=spritesheet.js&title=SpriteSheet+Animation).

I'm adding one frame of the animation (picked frame where plane is rotated so we have plenty of trimmed alpha around) and same one just below, but 2nd one is inside a container and I'm making `container width/height *2` and `image width/height /2` at the same time.

Expected outcome would be same size Sprites (and it is in V3) but in V4....
![resizeissue](https://cloud.githubusercontent.com/assets/2122619/15247054/6f76598e-1909-11e6-8d4e-82c1c39df094.png)

Here's the code I used:
```js
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);

var stage = new PIXI.Container();


PIXI.loader
    .add('_assets/basics/fighter.json')
    .load(onAssetsLoaded);


function onAssetsLoaded()
{
  //var texture = PIXI.Texture.fromImage('_assets/basics/bunny.png');
  var texture = PIXI.Texture.fromFrame('rollSequence0010.png');
  var img1 = new PIXI.Sprite(texture);
  var img2 = new PIXI.Sprite(texture);

  stage.addChild(img1);

  
  setTimeout(doStuff, 500);

  function doStuff() {
    var spriteWidth = img1.width;
    var spriteHeight = img1.height;
    
    // Add container below img1
    var mainContainer = new PIXI.Container();
    mainContainer.y = 300;
    stage.addChild(mainContainer);
    // Add img2 to container
    mainContainer.addChild(img2);

    // Container size * 2
    mainContainer.width = spriteWidth * 2;
    mainContainer.height = spriteHeight * 2;

    // Img2 size /2
    img2.width = spriteWidth / 2;
    img2.height = spriteHeight / 2;
  }
}


animate();
function animate() {
    requestAnimationFrame(animate);
    renderer.render(stage);
}
```

**Comment by ivanpopelyshev** [comment] 2016-05-13 12:00
Wow, you did it again! And now we have a problem in pixiv4

**Comment by ivanpopelyshev** [comment] 2016-05-13 12:05
Ok, I realised that Sprite width/height and Sprite getBounds() are different in that case because texture is trimmed. width/height reports original image (which has width 175), while getBounds() show cropped one (which is 49). 

I dont know what to do with it.

**Comment by ivanpopelyshev** [comment] 2016-05-13 12:09
@SlawomirMazgaj please use img1.getBounds() to determine width and height, because Sprite width/height implementation differs from container implementation.

Btw, In v3 "trimmed" width/height is in "texture.crop", while in v4 its "texture.trim", because API was changed.

**Comment by SlawomirMazgaj** [comment] 2016-05-13 13:18
Haha, sorry we have bunch of visual tests in here with alpha, scaling, rotations, etc... so it's quite easy to spot the difference between pixi versions ;)

Using `img1.getBounds()` sounds like a workaround for this one but it's not gonna solve all the issues. If I want to put bunch of images inside container and then resize this container it's still won't work. Comment out:
```js
img2.width = spriteWidth / 2;
img2.height = spriteHeight / 2;
```
from previous script so it's just container resize and see how big the image gets.
So if I want to resize images I could use `getBounds()` to determine width and height like you said. But if I want to resize container I'm kinda screwed :/

**Comment by ivanpopelyshev** [comment] 2016-05-13 13:24
The problem is, container resize and sprite resize are different. Either you use container width/height for resize, either you use sprite ones, please dont mix them.

**Comment by SlawomirMazgaj** [comment] 2016-05-13 13:47
Oh wow, that's quite an unexpected change :/

**Comment by ivanpopelyshev** [comment] 2016-05-13 16:48
Do you think that it will be better if I return v3 behaviour there?

**Comment by SlawomirMazgaj** [comment] 2016-05-13 16:53
Not sure about the others guys here but in our case it's a no-go and we gonna stick with V3 for now.

**Comment by ivanpopelyshev** [comment] 2016-05-19 15:11
fixed, merged, can be closed.

**Closed** 2016-05-19 15:15 UTC

**Comment by hoomanrow** [comment] 2016-09-20 17:55
I think I have a similar issue with 4.0.1, all my trimmed sprites seem skewed for some reason.  Didn't happen in v2 or v3.
