### ISSUE TITLE
The problem of loading @2x image

### ISSUE THREAD

**Issue by zhnoah** [pixijs/pixi.js#5753] opened 2019-06-04 06:47 UTC
### Expected Behavior
I want to load **name.jpg** on the regular screen and **name@2x.jpg** on the Retina screen.

I have this code：

```js
// set
new PIXI.Application({
    autoResize: true,
    resolution: window.devicePixelRatio || 1,
    transparent: true
})

// load image
PIXI.loader.add('key', 'name@2x.jpg')

// other...
```

### Current Behavior

**name@2x.jpg** image is loaded on any screen

### Possible Solution

Did I miss something?

### Environment

- **`pixi.js` version**: _e.g. 4.8.8_
- **Browser & Version**: _e.g. Chrome 74_
- **OS & Version**: _e.g. Windows 10_
- **Running Example**: _url_

**Comment by ivanpopelyshev** [comment] 2019-06-04 07:45
Working as intended. Pixi Loader does not have any options for choosing the resolution and extension of the file. 

There's a chooser at https://github.com/pixijs/pixi-compressed-textures/ , but I recommend to look up how it works before you use it. I advice to study the code, ctrl+c it and make loader that suits your app. Usually when someone needs a resolution chooser he also needs other sophisticated hacks ;)

**Comment by themoonrat** [comment] 2019-06-22 15:43
Hi @zhnoah 

I've tested this exact scenario, and it works absolutely fine for me.

I've attached a zip with the basic example put together: [pixi-resolution.zip](https://github.com/pixijs/pixi.js/files/3316986/pixi-resolution.zip)

In main.js, change 
`app.loader.add('square', '../assets/square@1x.png')`
to
`app.loader.add('square', '../assets/square@2x.png')`
And it changes as expected

**Comment by themoonrat** [comment] 2019-07-28 17:47
Closing as it seems to work; if you have any further problems, please raise an issue with a pixi playground example to help debug. Thanks!

**Closed** 2019-07-28 17:46 UTC
Labels: Plugin: Loader, Type: Question
