### ISSUE TITLE
TransformStatic , update rotation Reset skew , scale , why ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi.js#4602] opened 2018-01-12 05:02 UTC
hi guy, am trying to make a simple easing loop animation.
I need pass a obj, with propreties.
i pass the **TransformStatic** 

How i can perform correctly and update skew, scale, and rotation.
Rotation seem to always reset my transform!, maybe am not understand correctly how this work.
thank for help

![sans-titre-1](https://user-images.githubusercontent.com/24865815/34860371-ef1d32a6-f72a-11e7-923c-e185c695564c.png)

what i need to do it, something like this
```javascript
this._cx = newValur;
this._cy = newValur;
this._sy = newValur;
this._rotation = newValur; // not work when upd localID!?
this._localID++; // this seem to update all transform but not the rotation
// so 
this.rotation = newValur;
//!!! ho, rotation reset all data transform!! why and how fixe this
```

**Comment by ivanpopelyshev** [comment] 2018-01-12 09:25
Because .. source code: https://github.com/pixijs/pixi.js/blob/dev/src/core/display/TransformStatic.js#L177

When someone changes rotation it automatically calls updateSkew() without any update ids.

**Comment by ivanpopelyshev** [comment] 2018-01-12 12:12
There are many ways to implement Transform, I can't provide an explanation why does it work exactly like it works now. It was born by serious effort of multiple people when we made pixi-v4 release candidate.

**Comment by djmisterjon** [comment] 2018-01-13 19:41
thanks @ivanpopelyshev for you anwser.
i have found an tempory alternative for now, i have modify the update of my EASE animation system.
The problem is that I have to point to 2d properties. ( this[props][props2] )
and this not good for **performance** in the update.

ideally I would like a suggestion to manage everything in TransformStatic.
So for now a pass the sprite, and use 
**this.rotation,..
this.x, ...
this.alpha..
this.skew.x ..(2D deep mode for udpate)
this.scale.x ..(2D deep mode for udpate)**

  ```javascript
$.prototype.update = function() {
            if(!this._running || --this._delay >= 0) {
                return true;
            }
            var complete = (++this._time >= this._duration);
            var progress = complete ? 1.0 : parseFloat(this._easing(this._time / this._duration));
            for(var prop in this._valuesEnd) {
                if(typeof this._valuesEnd[prop]==='number'){
                var start = this._valuesStart[prop];
                var end = this._valuesEnd[prop];
                this._valueSetCallback(this._object, prop, start + (end - start) * progress);
                }else{ // its 2d PIXI DEEP PROPRETY 
                    for(var prop2D in this._valuesEnd[prop]) {
                        var start = this._valuesStart[prop][prop2D];
                        var end = this._valuesEnd[prop][prop2D];
                        this._valueSetCallback(this._object[prop], prop2D, start + (end - start) * progress);
                      
                    }
                }
            }
            if(this._onUpdateCallback !== undefined) {
                this._onUpdateCallback(this._object,progress);
            }
            if(complete) {
                this._running = false;
                if(this._onCompleteCallback !== undefined) {
                    this._onCompleteCallback(this._object);
                }
                this._chainedTweens.forEach(function(tween) {
                    tween.start();
                });
            }
            return !complete;
        }
```
if anyone has an idea or an alternative ?
thank

**Comment by djmisterjon** [comment] 2018-01-15 10:44
that show little bit the issue and hard target all props with animatedSprites
https://youtu.be/N3WDQHXUvwc

**Comment by ivanpopelyshev** [comment] 2018-01-15 12:05
I dont get it. The issue is obfuscated, please make a fiddle without RMMV, just vanilla pixi, tweens and one AnimatedSprite. 

I would debug your game directly if I had time, but unfortunately I'm too busy with v5.

**Comment by ivanpopelyshev** [comment] 2018-01-15 12:06
However, I like issues related to Transform, so if we find some inconsistance, we can probably change it in v5 ;)

**Comment by djmisterjon** [comment] 2018-01-15 12:12
my full plugin avaible here
https://codeshare.io/aVkDA3

**Comment by ivanpopelyshev** [comment] 2018-01-15 12:17
I dont need plugin, I need working example that fails, no extra references. You can also wait, I'm sure i'll have time next weekend. or one after next. Or next month :)

**Comment by ivanpopelyshev** [comment] 2018-01-15 12:28
btw art looks good.

**Comment by djmisterjon** [comment] 2018-01-15 16:23
in fact an idea comes to me, i think these approaches on AFTER EFFECT that is not the right one.
I'll see if I can try another approach.

I will probably take advice on your work about the 2.5D calculation.
i working on a tool for PIXI SPRITEANIMATION which will makes me very easy integration work in development.
there is just a problem for the 2.5D tool, what you can constrain it on this preview.
https://youtu.be/3Dt-IXhE2fc
I will probably need some advice on the approach of your work when the time will comes.
thank

ps thank for art, am waiting my new pen tabs in 5 day.

**Comment by ivanpopelyshev** [comment] 2018-01-15 16:52
Looks good, i can help with it :)

**Comment by djmisterjon** [comment] 2018-01-17 00:34
thank 
I'll try to finish it in 2 or 3 day the toolz, and make you a demo with a debug console.
if you will can help me with algorithm for the 2.5D tool , it will be very welcome for me.
I'm rewriting cleanest the code right now.

**Comment by themoonrat** [comment] 2018-07-02 18:33
@djmisterjon closing as I think you have a workaround for how transforms work in v4 now? Please re-open if you're still having issues

**Closed by themoonrat** 2018-07-02 18:33 UTC
Labels: Domain: API, Plugin: Transforms, Type: Question, Version: v4.x
