### ISSUE TITLE
Pixi.js 5.x behaves abnormally when drawing thousands of rectangles

### ISSUE THREAD

**Issue by alfred-f-yu** [pixijs/pixi.js#6104] opened 2019-09-18 04:41 UTC
The minimum reproducible code has been uploaded https://github.com/alfred-f-yu/pixijs_test/blob/master/pixi_test.html.

### Expected Behavior
When using pixi.js 4.8.8 to draw 10,000 (100x100, Graphic.drawRect) , the results are correct. 
As show in follow:
https://raw.githubusercontent.com/alfred-f-yu/pixijs_test/master/pixijs_4.8.8.png

### Current Behavior
But, when using the same codes with pixi.js 5.1.3, the results are strange.
As show in follow:
https://raw.githubusercontent.com/alfred-f-yu/pixijs_test/master/pixijs_5.1.3.png

If only draw 100 rectangles, both of 4.x and 5.x results are correct.

### Environment

- **`pixi.js` version**: _5.1.3_
- **Browser & Version**: _Chrome 77_
- **OS & Version**: _macOS 10.14.6_
- **Running Example**: _https://github.com/alfred-f-yu/pixijs_test/blob/master/pixi_test.html_

**Comment by ivanpopelyshev** [comment] 2019-09-18 12:18
Duplicate of #6047 and many others.

https://github.com/pixijs/pixi.js/wiki/v5-Hacks#removing-65k-vertices-limitation

I don't know whether it should be fixed or not, there are multiple ways and we still dont agree on them :(

**Comment by bigtimebuddy** [comment] 2019-09-18 13:29
Closing because duplicate.

**Closed by bigtimebuddy** 2019-09-18 13:29 UTC

**Comment by bigtimebuddy** [comment] 2020-02-20 17:17
Fixed in #6417
