### ISSUE TITLE
lineStyle alignement is not respected while rendering on Canvas (legacy)

### ISSUE THREAD

**Issue by cedeber** [pixijs/pixi.js#7263] opened 2021-02-24 18:47 UTC
### Expected Behavior
Lines are rendered sharp as when rendered with WebGL.

### Current Behavior
On canvas, the stroke is drown in the middle, so, for instance, if it is 1px, then it is 0.5px misplaced if you aligned it inside of the shape.

### Possible Solution
We should render the shape with strokeWidth / 2 when alignement is 0 or 1 (or some better math)

**Comment by bigtimebuddy** [comment] 2021-02-24 18:51
Duplicate of #7130

**Closed by bigtimebuddy** 2021-02-24 18:51 UTC
