### ISSUE TITLE
Limited display number of rectangle with Graphics.drawRect()

### ISSUE THREAD

**Issue by SpinningK** [pixijs/pixi.js#6184] opened 2019-10-19 01:59 UTC
Hi, I'm new to pixi.js. I'm doing a data visualization work with it. But there's a problem when I draw rects in canvas.

### Expected Behavior
Draw 40000 rects in canvas with Graphics.drawRect()

### Current Behavior
Maximum number of rects displayed on the screen is 16384(2^14), if use drawCircle(), 4096(2^12) circles at most. No log dispalyed in console.

### Possible Solution
I didn't know why there is a limitation of the display number of rects, intentionally set or just a bug. But if I create another instance of PIXI.Graphics, I can draw another 2^14 rects. It's verbose, isn't it? So I hope you can fix this issue.

### Environment

- **`pixi.js` version**: 5.1.5
- **Browser & Version**: chrome 77.0.3865.120
- **OS & Version**: macOS 10.15 (19A602)

### Running Example
```html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
</head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.1.5/pixi.min.js"></script>

<body>
    <script type="text/javascript">
        let app = new PIXI.Application({
            width: 800,
            height: 800
        });
        document.body.appendChild(app.view)
        let graphics = new PIXI.Graphics();
        app.stage.addChild(graphics);

        graphics.beginFill("0xff0000");
        // hope 40000 rects, but got 2^14 rects at most.
        for (var i = 0; i < 40000; i++) {
            let x = (i % 200) * 4;
            let y = parseInt(i / 200) * 4;
            //let r = 1
            let w = 2
            let h = 2
            graphics.drawRect(x, y, w, h)
            //graphics.drawCircle(x, y, r); // 2^12 circles at most.
        }

        /* If I create another instance of Graphics, I can draw more rects */

        // let graphics2 = new PIXI.Graphics();
        // app.stage.addChild(graphics2);
        // graphics2.beginFill("0x0000ff");
        // for (var i = 0; i < 40000; i++) {
        //     let x = (i % 200) * 4;
        //     let y = parseInt(i / 200) * 4 + 400;
        //     //let r = 1
        //     let w = 2
        //     let h = 2
        //     graphics2.drawRect(x, y, w, h)
        //     //graphics.drawCircle(x, y, r);
        // }
    </script>
</body>

</html>
```

**Comment by bigtimebuddy** [comment] 2019-10-19 05:08
Duplicate of #6047 and many others.

https://github.com/pixijs/pixi.js/wiki/v5-Hacks#removing-65k-vertices-limitation

Closing.

**Closed by bigtimebuddy** 2019-10-19 05:08 UTC
