### ISSUE TITLE
Pixi blank white page after running in background tab

### ISSUE THREAD

**Issue by jasonsturges** [pixijs/pixi.js#6370] opened 2020-01-31 06:09 UTC
Discovered this on a variety of Pixi solutions; so, thought I'd bring it up.

If I leave a Pixi application open in a background tab for a while, when I come back the Pixi application is blank - white, still in the DOM, but nothing visible.  

Seems like the `requestanimationframe` is not picking back up.

Any action to trigger render, like resizing the browser brings it back to life.

Might seem like a corner case, but has some major ramifications on Kiosk based applications at my company - if the view moves to background for a while, it is blank when it comes back into the foreground.

### Expected Behavior

When tab returned to foreground, requst animation frame picks back up.

### Current Behavior

After leaving a tab in the background for a while the Pixi view is blank.  White, nothing in it.

Not sure exactly how long this takes in minutes.

### Possible Solution

Unknown - might not be a solution.  Seems like browser should control pause / resume of request animation frame.

Otherwise, maybe page visibility change events

```
document.addEventListener("visibilitychange", onVisibilityChange);
```

### Steps to Reproduce

- Open a Pixi application in a tab
- Leave that tab in the background for a while, like, 30 / 60 minutes maybe
- When you come back to that tab, it's blank - Pixi application buffer is empty, and not rendering

### Environment

- Pixi 5.2.0
- Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- macOS Mojave Version 10.14.6
- Codepen can reproduce: https://codepen.io/jasonsturges/pen/BayMWxm

**Comment by ivanpopelyshev** [comment] 2020-01-31 08:14
We cap our "deltaTime" with max delta so it should work. 

> Might seem like a corner case, but has some major ramifications on Kiosk based applications at my company

Its not a corner case, but it can be tied to your browser.

Can anyone confirm this please on regular computer and not on a kiosk?

**Comment by ivanpopelyshev** [comment] 2020-01-31 08:15
One of my ideas regarding the problem is that the context was lost due to other app eating the memory. We need to confirm that PixiJS survives context loss in that case.

**Comment by eXponenta** [comment] 2020-01-31 09:09
We can't fix this inside pixi , because this is device problem:
when memory os full, taskkiller kill unused suspended process and free memory, WebGL is separated process, it killed before killing page process, and sometimes browser save page memory to disk cache, and resore back when tab activating, but WebGL thread already dropped.

We can't restory WebGL state fully inside PIXI, you must do it themself, or restart app.

**Comment by ivanpopelyshev** [comment] 2020-01-31 09:13
Oh, right, you need to put an `if` that checks if context is lost and calls restore in your app. We certainly dont put it in default pixi application.

**Comment by jasonsturges** [comment] 2020-01-31 15:29
Example of the issue from codepen, just from my MacBook:

![pixi-empty2](https://user-images.githubusercontent.com/1213591/73550800-de68e700-440a-11ea-9eaa-065490cf6ece.gif)

That makes a lot of sense - multiple Pixi instances competing for memory.

In development, I see it often as I have many Pixi applications running at one time.

This helps me assure production deployment patterns to prevent this from happening.

Really appreciate the insight - that's all the resolution I need - thanks!

**Comment by bigtimebuddy** [comment] 2020-01-31 15:34
Seems answered, closing.

**Closed by bigtimebuddy** 2020-01-31 15:34 UTC
