### ISSUE TITLE
Performance degradation caused by antialias and renderer.resize

### ISSUE THREAD

**Issue by RobertAKARobin** [pixijs/pixi.js#5949] opened 2019-07-25 15:54 UTC
Depending on the order of `renderer.resize` and `renderer.resolution`, and the value of `antialias`, there is a considerable performance degradation on my machine: the fans spin up and the screen lags.

Here's the code I've tested. The lines marked with asterisks are the ones I've tried in various combinations (see below table):

```js
document.addEventListener('DOMContentLoaded', ()=>{
    const app = new PIXI.Application({
/**/    antialias: true,
/**/    resizeTo: document.body,
/**/    resolution: window.devicePixelRatio
    })
    document.body.append(app.view)
    console.log(`${app.view.clientWidth}w x ${app.view.clientHeight}h`)
/**/app.renderer.resolution = window.devicePixelRatio
/**/app.renderer.resize(document.body.clientWidth, document.body.clientHeight)
})
```

Here are the different combinations I've tested:

| Performance | options.antialias | options.resizeTo | options.resolution | renderer.resize | renderer.resolution | view.clientW/H  |
|-------------|-------------------|------------------|--------------------|-----------------|---------------------|-----------------|
| Bad         | `true`            | set              | set                |                 |                     | 2510w x 1332h   |
| OK          |                   | set              | set                |                 |                     | 2510w x 1332h   |
| Bad         | `true`            |                  | set                | set             |                     | 1600w x 1200h   |
| OK          |                   |                  | set                | set             |                     | 1600w x 1200h   |
| Bad         | `true`            |                  |                    | set, first      | set, second         | 800w x 600h     |
| OK          |                   |                  |                    | set, first      | set, second         | 800w x 600h     |
| OK          | `true`            |                  |                    | set, second     | set, first          | 800w x 600h     |
| OK          | `true`            | set              |                    |                 | set                 | 1255w x 666h    |

- **`pixi.js` version**: 5.1.0
- **Browser & Version**: 75.0.3770.142
- **OS & Version**: Mac OS 10.13.6

**Comment by photonstorm** [comment] 2019-07-25 16:24
If you call `resize` _before_ setting the `resolution` then surely you're just creating a canvas that is considerably smaller than it otherwise would be (assuming a HighDPI screen is in use). What you should add to your table is the canvas size that is actually created - because I'll bet it will correlate perfectly with 'Bad' performance.

**Comment by RobertAKARobin** [comment] 2019-07-25 16:36
@photonstorm I've updated my post with that info.

**Comment by ivanpopelyshev** [comment] 2019-07-25 18:55
Welcome to our sweet repo! I like tables!

The problem is that `renderer.resolution=2` doesnt actually change backbuffer resolution, and calling `renderer.resize()` after that change also doesn't work, you need a couple more lines.

That means the real issue is that `resolution` is not marked as @readonly with big flashy warning.

https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/AbstractRenderer.js#L93

I can write that couple of lines later, i did that for v4 before but i dont have it on my fingers.

**Comment by ivanpopelyshev** [comment] 2019-07-25 18:56
Also, seeing @photonstorm in our issues/PRs always raises my spirits.

**Comment by ivanpopelyshev** [comment] 2019-07-30 12:54
OK, I looked in the code and seems this can work:

```js
renderer.resolution = 2;
renderer.resize(w, h);
```

Demo:
https://www.pixiplayground.com/#/edit/JmmpVKIvGdJtEGoxkF922

I think that `antialias:true` is bad at big resolutions. can you re-do the test please?

**Comment by RobertAKARobin** [comment] 2019-07-30 13:00
Unfortunately the display on my Mac went on the fritz. I'll test it out when it's repaired in (hopefully) a few days.

**Comment by RobertAKARobin** [comment] 2019-08-03 03:07
@ivanpopelyshev Your code works for me!

**Comment by bigtimebuddy** [comment] 2019-08-03 04:05
Seems answered. Closing.

**Closed by bigtimebuddy** 2019-08-03 04:05 UTC
