### ISSUE TITLE
Sprites unable to have 0px width/height proportion

### ISSUE THREAD

**Issue by brenwell** [pixijs/pixi.js#2181] opened 2015-11-03 17:15 UTC
Firstly thanks for the lib!

I am not sure if this is intentional, however, since 3.0.8 sprites can nolonger have a width or height of 0.

I have many occassions I am am tweening sprites to 0 width/height and back, creating a flipping appearance. However once a sprite has had its height or width attribute assigned to 0, it appears to be destroyed and assigning a new positive value will not fix it. 

I feel that sprites should be allowed to be >= 0 in dimension, what do you think?

A quick sample. **Click the sprite** it will shrink and never reach 0. **Click the 1 pixel high sprite** and it will have its height assigned to 0 and then attempt to grow. It will never return.

http://jsfiddle.net/sD8Tt/240/ 

I think it may have something to do with this commit, but not sure. https://github.com/pixijs/pixi.js/commit/45e3531a6893e1248935a68f282f5f9079e6dd74 

Thanks

**Comment by jberube** [comment] 2015-11-04 15:51
Look like a duplicate of https://github.com/pixijs/pixi.js/issues/2159 ?

**Comment by brenwell** [comment] 2015-11-04 15:55
Think it might be. My bad.

**Comment by englercj** [comment] 2015-11-04 16:04
Pretty sure this is the same issue, try it with the dev branch and see (be sure to build locally).

**Comment by GoodBoyDigital** [comment] 2016-08-09 21:00
closing due to inactivity 👍

**Closed by GoodBoyDigital** 2016-08-09 21:00 UTC
