### ISSUE TITLE
Render texture is opaque on current Windows Firefox, when using WebGL renderer.

### ISSUE THREAD

**Issue by martin-stone** [pixijs/pixi.js#1636] opened 2015-04-07 10:06 UTC
The background of a render texture appears to be solid black on Windows Firefox, when using the WebGL renderer. It's transparent as expected when using canvas or using WebGL in other browsers (including FF on Mac).

Repro code here: http://jsfiddle.net/25s8phpg/ (This uses the pixi.js from the Pixi examples page, but the behaviour is the same with 2.2.8 and 2.2.0)

Seen on Firefox 36.0.4 and 37.0.1.

**Comment by GoodBoyDigital** [comment] 2015-04-11 19:49
hey there! does this happen with v3 of pixi? thanks!

**Comment by martin-stone** [comment] 2015-04-13 09:58
It doesn't work at all on 3.0.0-rc4...

RenderTexture.js:346  Uncaught TypeError: undefined is not a function

Not sure what I'm doing wrong.

**Comment by GoodBoyDigital** [comment] 2015-04-13 10:14
Yo! The API for v3 is a little different - you have to pass a renderer as the first parameter when creating a render texture

**Comment by martin-stone** [comment] 2015-04-13 10:23
OK, now it's opaque black on all browsers / renderers: 

http://jsfiddle.net/usskgphh/

which is at least consistent :-) Do we have to explicitly initialise a render texture to be transparent?

**Comment by GoodBoyDigital** [comment] 2015-04-13 10:26
nice, we can work with that :) will take a look today..

**Comment by GoodBoyDigital** [comment] 2015-04-13 10:28
looks like another API change was causing the black

http://jsfiddle.net/6r5e070w/

does this work on all browsers for ya?

**Comment by martin-stone** [comment] 2015-04-13 10:37
That now behaves exactly as in the original report (once the canvas renderer is given the green background too). I.e. black for Firefox Windows + WebGL, green otherwise.

**Comment by yotamlaufer** [comment] 2015-04-18 13:16
Hi All, will this issue be fixed for 2? It's a blocker for me.

**Comment by GoodBoyDigital** [comment] 2015-04-18 16:37
This one is really tricky for me to check as I have no easy access to a PC and browserstack does not support webGL :/

Hopefully I will get my mits on a PC soon to test.

**Comment by jdashg** [comment] 2015-04-27 22:39
I filed a bug for this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1159034

**Comment by englercj** [comment] 2015-04-28 01:22
@jdashg Thanks for looking into this, we really appreciate your time and effort.

@martin-stone Looks like this is a Firefox bug, as it states in that ticket you can work around it by passing `alpha: true` on context creation. To do that in pixi, just extend the default context params.

```js
PIXI.DEFAULT_RENDER_OPTIONS.alpha = true;
```

**Comment by martin-stone** [comment] 2015-04-29 11:07
Thanks everyone, that workaround does fix the problem for me, although now I have to work around having a transparent canvas where I was previously relying on the background colour. Is there a neater way than just drawing a big rectangle?

**Comment by englercj** [comment] 2015-04-29 14:06
make the background color of the element it is in whatever color you want with CSS

**Comment by jdashg** [comment] 2015-04-29 17:20
Just clear the backbuffer's alpha channel to 1.0, and set
colormask(1,1,1,0) when operating on the backbuffer.

**Comment by nickdesaulniers** [comment] 2015-05-04 17:27
This has been fixed in Firefox 40, which will ship [2015-08-11](https://wiki.mozilla.org/RapidRelease/Calendar#Future_branch_dates).

**Comment by jdashg** [comment] 2015-05-05 00:56
I've written a regression test for this, and will try to get the fix into
Aurora.

**Comment by englercj** [comment] 2015-05-05 00:59
Really appreciate the work, thanks for keeping us in the loop.

**Comment by GoodBoyDigital** [comment] 2015-10-22 20:34
Howdy, looks like this has been resolved. Closing for now :+1:

**Closed by GoodBoyDigital** 2015-10-22 20:34 UTC
Labels: Browser Bug, WebGL
