### ISSUE TITLE
loader progress over 100% in v4

### ISSUE THREAD

**Issue by humanhighway** [pixijs/pixi.js#2876] opened 2016-08-29 09:13 UTC
occur status : 
- use spritesheets ( generated by texture packer )
- use browser-sync open html (works normal if open html directly.)
- v4  ( works normal at v3 )

example code : 
[pixi-loader-test.zip](https://github.com/pixijs/pixi.js/files/442093/pixi-loader-test.zip)

step : 
  1. npm install
  2. browser-sync start --server
  3. check consloe.log

**Comment by englercj** [comment] 2016-08-29 15:00
This most likely is a resource-loader issue, can you try to make an example using the latest of that lib?

https://github.com/englercj/resource-loader

I fixed a few bugs since pixi last updated.

**Comment by FNevesFMQ** [comment] 2016-08-29 16:07
I'm getting same issue!
And from what I have inspected, in my case, it's about .fnt files
When loading that, loader is considering the image related to .fnt file, and increases it on progress attribute..

**Comment by englercj** [comment] 2016-08-29 17:06
You're probably talking about this bug then? https://github.com/englercj/resource-loader/pull/32

**Comment by FNevesFMQ** [comment] 2016-08-30 09:00
I don't think so... that bug is about a manif file being load in last, and itself loads another amount of files given the impression of getting stuck on 100% (right?)

In my case, is just a bunch of image atlas (.json) and font files (.fnt), and each one have an image file associated. For example, if I have 2 .json and 2 .fnt it should be 25% for each file, right? But now it goes until 200% because each adds one more file with same weight..

But something curious is that after doing "loader.add(url_list)" if I print "loader.resources" it gives me a correct assets list, including referencing images from that files (.json and .fnt). Also, on complete loading, attribute loader.progress goes back to 100%

**Comment by englercj** [comment] 2016-08-30 14:11
@FNevesFMQ Hmm, I haven't seen that. Please open an issue on resource-loader with a repro case there. Please use the latest version of the repo and not pixi.

**Comment by FNevesFMQ** [comment] 2016-08-31 11:03
@englercj from what I tested, this only occurs using pixi, not the resource-loader standalone.

Something about 'Loader._pixiMiddleware', that is where it parses the textures/spritesheet/bitmapFont

Because using resource-loader standalone and trying to load .json and .fnt it only loads that files, but with pixi it also loads the image ref file for each one.. and probably that's the problem, no?

**Comment by englercj** [comment] 2016-08-31 14:14
> Because using resource-loader standalone and trying to load .json and .fnt it only loads that files, but with pixi it also loads the image ref file for each one.. and probably that's the problem, no?

Because the middleware adds more files. Nothing in pixi deals with progress at all. In your repro case just have the middleware add more files and try to reproduce it.

**Comment by FNevesFMQ** [comment] 2016-09-01 09:58
> In your repro case just have the middleware add more files and try to reproduce it.
I tried and works fine. I added some files in the middle of loading process and progress was well calculated.

So, must be something on pixi..

**Comment by englercj** [comment] 2016-09-01 14:08
> I tried and works fine. I added some files in the middle of loading process and progress was well calculated.

>So, must be something on pixi..

Weird, resource-loader has tests for this case so I didn't think it was broken but not sure what pixi could be doing that is breaking it.

**Comment by FNevesFMQ** [comment] 2016-09-05 13:38
Look here: https://jsfiddle.net/FNevesFMQ/c036va1w/11/

I made an example using PIXI v4 and some .json and .fnt files from my dropbox.
As you can see, it goes over 100% and in the end goes back to 100..

**Comment by sopilkar** [comment] 2016-09-07 11:50
This problem appears because some resources contains nested files. In result the 'resources' property from PIXI's loader is changing dynamically.
As one of solutions I've made this example: https://jsfiddle.net/7zc05szm/4/

**Comment by englercj** [comment] 2016-09-08 01:16
Looked into this a bit more, and added a bunch more tests to resource-loader and managed to get it to reproduce finally.

Most of the tests in place only added a single additional resource, and this seems to only happen with multiple additional resources. I now have a test added that is failing, so I can track down a solution.

Here is the test that fails: https://github.com/englercj/resource-loader/blob/312022a6c3745481022b86f1ce533a5563c7e425/test/unit/Loader.test.js#L495-L510

Likely, I will roll in the solution to this issue with the progress rewrite I proposed here: https://github.com/englercj/resource-loader/pull/32#issuecomment-239654160

Since this is a resource-loader issue I'm closing this in favor of tracking on the issue I linked.

**Closed by englercj** 2016-09-08 01:16 UTC
Labels: bug, minor

**Comment by sonhihi** [comment] 2016-09-26 09:36
i've a same issue

**Comment by FNevesFMQ** [comment] 2016-11-21 10:42
I'm using PIXI 4.2.2 and this still occurs.. is the last version of resource-manager fixed or pixi still have an outdated version?

**Comment by ppluchon** [comment] 2016-12-12 17:40
Hello guys, any news from this issue?
Thanks

**Comment by ivanpopelyshev** [comment] 2016-12-12 18:06
Nope. No one is brave enough to introduce latest loader in pixi :( I'm writing my own laoder at the time.

**Comment by englercj** [comment] 2016-12-26 07:44
This is solved by resource-loader v2. I'll update it now is dev.
