### ISSUE TITLE
is SimplePlane broken?

### ISSUE THREAD

**Issue by s-r-x** [pixijs/pixi.js#5487] opened 2019-03-04 08:16 UTC
pixi's 4.* mesh.Plane was so nice, but i can't figure out how to change vertices with this new api. docs says that i need to 'change its uvBuffer data and increment its _updateID', but simpleplane object doesn't have that _updateId prop. in v4 i could just change its vertices and it worked! help! here's the code:

const mesh = new SimplePlane(texture, 15, 15);

app.stage.addChild(mesh);

const originals = [ ...mesh.uvBuffer ];

let acc = 0;

app.ticker.add(() => {

  acc += 0.01;

  mesh.uvBuffer.forEach((_, i) => mesh.uvBuffer[i] = originals[i] + Math.sin(acc));

});

**Comment by Dairnon** [comment] 2019-03-04 09:48
Next time try to provide a www.pixiplayground.com example

All meshes/sprites are made up of 4 different things

geometry
shader
state
render --> draw

In this case you need to modify the geometry of the SimplePlane, you can get that a number of ways.

The easiest way is to use getAttribute

https://www.pixiplayground.com/#/edit/H2Pf5H3wL3K0PERpGIAqg

**Comment by s-r-x** [comment] 2019-03-04 10:19
Dairnon, thanks for the answer man. I've have a look at your demo, but that's not exactly what i want. Can you explain how can i get something like this with new api?
https://www.pixiplayground.com/#/edit/zyX4okQCiDNCXstXZaL7h

**Comment by ivanpopelyshev** [comment] 2019-03-04 13:24
It should work guys. If it doesn't work, please look in source code, find our mistake. I dont have enough brain juice right now to help with this thing, it should be easy.

**Comment by ivanpopelyshev** [comment] 2019-03-04 13:28
```
let uvs = this.geometry.getAttribute('aTextureCoord')
// look inside this buffer object, it has _updateID ^^^^^
```

**Comment by s-r-x** [comment] 2019-03-04 14:19
i've tried to increment everyone of these guys, with no success.
actually, i've decided to switch to 4.8.6 version, where everything works fine.
thanks for the help anyways

**Comment by Dairnon** [comment] 2019-03-04 23:40
@s-r-x My repo was only making the code u provided work, which it does.

Getting the animation to be the same is up to you to figure out! :)

**Comment by Dairnon** [comment] 2019-03-04 23:57
Also ur initial example was changing uv's not vertices. That's why mine acted different. 

Here is an attempt to copy the example you provided. 

https://www.pixiplayground.com/#/edit/0V0ndh3PGYGPxvBnSzy22

One thing of note, PlaneGeometry's construction  may bit different from the plane in v4, so you'll notice as you add more segments the result will look different. 

Anyway this I believe is working as intended, please check out the demo I provided and see what results you get :) 

Closing.

**Closed by Dairnon** 2019-03-04 23:57 UTC
