### ISSUE TITLE
Firefox - Massive FPS loss

### ISSUE THREAD

**Issue by JAA17** [pixijs/pixi.js#4111] opened 2017-06-19 16:06 UTC
I am working on a game which is nowhere near completion yet, so I cannot give you a running example, however, I can say what I am doing.

I have 5 cropped sections over the screen, each showing a different representation of the scene. Eg the user's main view, a mini-map showing the user's relation to others, etc
There are several text areas giving the user important info. About 50 bits of text which need to be aligned, due to them needing to be in columns.
I only have about 30 images in each scene that are moving.

In the wonderful chrome I am getting 60fps.
In edge I am getting 45fps, but it has the known keyboard input issue which might put some users off using edge.

However in Firefox I am getting a terrible 6fps.

Has anyone experienced such a thing before? Is there something in Firefox that needs to be turned on or something?

**Comment by siwel** [comment] 2017-06-19 16:27
Seems odd that the difference between chrome and firefox is that large. _I have had a similar issue where it ended up being an extension logging out to the console too much. _. Presides the normal profiling it might be worth checking that there is nothing wrong with you Firefox install by comparing the[ Pixi examples](https://pixijs.github.io/examples/#/basics/spritesheet.js) on FireFox vs Chrome. In my experience, they perform reasonably similar.

**Comment by JAA17** [comment] 2017-06-19 16:36
Thanks for the reply.
The pixi examples appear reasonably similar.
What do you mean by 'an extension logging out to the console too much'?
Also, what kind of profiling to you use?

**Comment by siwel** [comment] 2017-06-19 16:47
Ohh so I had a WebGL insight extension that was spamming the console, and that was the route of my bad performance. Though it was worth mentioning, however, if it works well on the examples then it's likely it's not that. 

I just use the tools built into Chrome most of the time, looking at what is forcing redraws on the page. As for profiling within Pixi, that's something I find fairly difficult :( Will be interested to see others suggestions.

Additionally, if you have not come across it already there are a nice number of tips here: https://github.com/pixijs/pixi.js/wiki/Performance-Tips

**Comment by JAA17** [comment] 2017-06-24 10:33
Update: I have literally removed most things except the very base animation and I am still only getting 10fps on firefox. There must be a firefox setting that is not right on my machine, or I am setting things up incorrectly somehow that firefox does not like.

**Comment by tobireif** [comment] 2017-11-05 17:56
Since the issue is in Firefox, perhaps you could file a Firefox bug report in addition to the PixiJS report? https://bugzilla.mozilla.org/enter_bug.cgi

**Comment by GoodBoyDigital** [comment] 2018-02-22 23:35
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍

**Closed by GoodBoyDigital** 2018-02-22 23:35 UTC
