### ISSUE TITLE
Partial text-styling?

### ISSUE THREAD

**Issue by UltraCakeBakery** [pixijs/pixi.js#6323] opened 2020-01-11 16:31 UTC
Is there any way to do partial text styling?

So for example;
"[I][LOVE][PIXI]" could turn in to "**I** _LOVE_ PIXI"

**Comment by ivanpopelyshev** [comment] 2020-01-11 17:11
We are waiting for someone to port https://github.com/avgjs/pixi-richtext/ to pixi-v5. Its a community problem. Do you want to try? SDF stuff has to be moved to shader meshes.

**Comment by themoonrat** [comment] 2020-01-11 17:53
https://github.com/tleunen/pixi-multistyle-text also exists and is pretty neat

**Comment by UltraCakeBakery** [comment] 2020-01-13 08:49
I can try but sadly have no idea how shaders work. Let alone know what SDF is. 
I'm planning on doing research on all of it later this month.

**Comment by ivanpopelyshev** [comment] 2020-01-13 09:52
> I can try but sadly have no idea how shaders work. Let alone know what SDF is.
> I'm planning on doing research on all of it later this month.

^^ look up @themoonrat response

**Comment by ivanpopelyshev** [comment] 2020-01-14 07:07
Good answer here: https://www.html5gamedevs.com/topic/44521-multi-style-text/?do=findComment&comment=247868

**Comment by UltraCakeBakery** [comment] 2020-01-15 11:38
Thanks for the link @ivanpopelyshev. So he basically says that i could use PIXI.TextMetrics.measureText() to get a array of all words that I can style separately?

**Comment by themoonrat** [comment] 2020-01-15 11:55
At it's most basic level, you could take, say, a 5 word sentence. Create the first word with the right styling, call .updateText() on it, and add it to a parent. Then use text1.width to find out how much room it takes up, and place a second text object text1.width pixels to the right of it. And so on. So for 5 words, you have 5 individual pieces of text all positioned within 1 container.

For word wrapping, if text1.width + text2.width + text3.width would be over the limits you want, you then set text3.y to text1.height, and set it's x to 0 and start again. (with added spacing to make it look nice)

Not quite sure what jonforum's method would be - hopefully he can fix that link on his post, I'd be interested to take a look too!

**Comment by UltraCakeBakery** [comment] 2020-01-15 12:09
It's a good replacement for basic use-cases but sadly I need to be able to make something on the same level as a semi-advanced text editor. I could make a plugin for PIXI to realize that idea but the thing is that that wouldn't be the most performant option (i think?) in the long run.

**Comment by ivanpopelyshev** [comment] 2020-01-15 12:15
Oh, performance for text-format is entirely different problem, not related to pixijs. The problem is universal function `replace(start,end,newstring)`, and reflow that it can cause. In that case text editor should be tile-based, many small canvases size of 256x256, redraw only those that were affected. 

I don't know of pixijs plugins that handle that thing, its completely out-of-scope. The rendering base itself is canvas2d that gets uploaded to gpu, or is on gpu because of browser magic. Do you know whether particular Image or Canvas already present in GPU memory? The only way to know it is to measure upload method - it will be very fast if its already on GPU, theoretically, unless there are more of lazy operations.

**Comment by ivanpopelyshev** [comment] 2020-01-15 12:20
Actually, you can check if AwayJS has good enough text editor. They might.

**Comment by djmisterjon** [comment] 2020-01-15 20:12
@themoonrat yes sorry, it was my private repo, i was think i can share direct link with people from a private repo but seem no!
I fixed my repo with public, now link should work.

The thing i was think for very simple use , in case if the guy dont like play with regex.
![image](https://user-images.githubusercontent.com/24865815/72466909-d6247100-37a7-11ea-911c-ba3d42bdb902.png)
You can easily map PIXI.texts in a Container with those data provide by Metrics.
For a very simple use , it maybe the most easy Vanilla way, no ?

On my game engine , i was need something very complex with text, and pixi metric api save me a lot of time for multiStyles and also for motions. 
https://github.com/djmisterjon/ANFT/blob/1bfda5a7a047ee2dcc963c59873f5f0b65b7c24c/js/game/global/texts.js#L239

**Comment by themoonrat** [comment] 2020-02-20 17:20
closing as examples for how to do this have been given!

**Closed by themoonrat** 2020-02-20 17:20 UTC
