### ISSUE TITLE
Blendmode Multiply with filter make sprite black

### ISSUE THREAD

**Issue by Bouh** [pixijs/pixi.js#7224] opened 2021-02-04 19:34 UTC
### Expected Behavior
Blendmode and effect should working together.

### Current Behavior
Blendmode multiply make sprite black with blur effect, maybe with other effects too.

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/XIU2u6lFUP3iyrl3VEmRN

### Environment

- **`pixi.js` version**: 6.0 and lower
- **Browser & Version**: Chrome 87
- **OS & Version**: w10
[Running Example](https://www.pixiplayground.com/#/edit/XIU2u6lFUP3iyrl3VEmRN)

**Comment by bigtimebuddy** [comment] 2021-02-05 00:19
Try this instead.
```js
//dude.blendMode = PIXI.BLEND_MODES.MULTIPLY;

var blurFilter = new PIXI.filters.BlurFilter();
blurFilter.blendMode = PIXI.BLEND_MODES.MULTIPLY;
dude.filters = [blurFilter]
```

**Comment by Bouh** [comment] 2021-02-05 00:33
It works like you suggest, any idea why the blend mode on sprite is not correct?
Blend mode on object and filters are different?

**Comment by bigtimebuddy** [comment] 2021-02-05 01:05
This is working as intended, but I can see what this is confusing.

In general, for filters to work, Pixi does a "snapshot" of your display object to another surface then applies the filters to that. Because blend modes are a post-process, when you use multiply to your original container of sprites Pixi doesn't know what to multiply the pixels to when it does the snapshot because blend modes take into account the pixels below the object. What you actually need to do is add the blend-mode to is the filter, which will apply it to the snapshot the the original source. 

Now, this would work if you your bunnies weren't on a transparent background, like this:
https://jsfiddle.net/bigtimebuddy/to5k9z0s/

In that case, we create an opaque background, add multiply to the bunnies, then blur. Everything is :+1:

**Comment by Bouh** [comment] 2021-02-05 01:34
Thanks for the explanation! :)

**Comment by bigtimebuddy** [comment] 2021-02-05 03:06
Sure, I'm going to close this seems like I answered your question.

**Closed by bigtimebuddy** 2021-02-05 03:06 UTC
Labels: 👍 Not A Bug
