### ISSUE TITLE
lineTo paths being auto-closed in latest dev build

### ISSUE THREAD

**Issue by GBagley** [pixijs/pixi.js#1892] opened 2015-06-13 01:13 UTC
In the latest dev build (I really wanted the polygon improvements from: https://github.com/GoodBoyDigital/pixi.js/issues/1869 :+1: ), seems lineTo commands are getting auto-closed. i.e., the last point is being connected to the first point. Simple example:

http://jsfiddle.net/v7cgo4vb/

Not sure if this is actually a bug, or if someone was just testing something in the dev build and hasn't put it back yet, but thought I should bring it up at least.

**Comment by stbaer** [comment] 2015-06-13 07:21
This looks like a regression from pull request #1863.

**Comment by stbaer** [comment] 2015-06-13 07:26
A quick workaround without changing the PIXI source would be to put:

```js
if (g.currentPath && g.currentPath.shape) {
        g.currentPath.shape.closed = false;
    }
```
at the end of the draw function (with g as the PIXI.Graphics instance)

**Comment by wayfu** [comment] 2015-07-31 04:35
As the author of #1863 I feel like I have to say something ;) I investigated further, and the "closed" value of the shape is never actually passed to drawShape, it gets reset in drawPolygon. I don't know which strategy you'd think is best to tackle that, locally I've been storing the closed value in the first if clause, before it gets thrown away, like this:
```
(...)
    var closed;
    
    if (path instanceof Phaser.Polygon || path instanceof PIXI.Polygon)
    {
        closed = path.closed;
        path = path.points;
    }
(...)
```
...and then later in the function, I reset it: 
```
(...)
    var poly = new Phaser.Polygon(points);
    poly.closed = closed;
    
    this.drawShape(poly);
(...)
```

Still, it will get thrown out in drawShape again, unless it's explicitly saved, so I went the extra variable route there as well:
```
(...)
    var closed = shape.closed;
    //  Handle mixed-type polygons
    if (shape instanceof PIXI.Polygon)
    {
        shape.flatten();
    }

    var data = new PIXI.GraphicsData(this.lineWidth, this.lineColor, this.lineAlpha, this.fillColor, this.fillAlpha, this.filling, shape);
    
    this.graphicsData.push(data);

    if (data.type === PIXI.Graphics.POLY)
    {
        data.shape.closed = closed;
        if (this.filling) data.shape.closed = true; // not sure about this line, does a fill depend on the shape being closed?
        this.currentPath = data;
    }
(...)
```

I am not going to make a PR with these changes unless the pixi people say that's how they'd do it, because my workaround feels naive, clumsy and unprofessional. It works, though!

**Comment by wayfu** [comment] 2015-08-02 21:28
I found another place where things would need to change: in lineStyle and moveTo, new Polygons are constructed. These would need to have their closed value set to false.

**Comment by whizzkid** [comment] 2015-08-17 09:35
Any progress on this issue?

**Comment by englercj** [comment] 2015-09-28 05:54
This should be fixed in the latest dev code, can you retry it again? Thanks!

**Comment by whizzkid** [comment] 2015-09-28 07:52
Yup, that fixed it, my shape isn't automatically closed anymore.

My graph-view thanks you :)

**Comment by englercj** [comment] 2015-09-28 19:18
No problem :) I'm going to close this then since it is fixed in the next release.

**Closed by englercj** 2015-09-28 19:18 UTC
Labels: bug, Graphics
