### ISSUE TITLE
Blank canvas, upon registering plugins.

### ISSUE THREAD

**Issue by xpicer** [pixijs/pixi.js#7048] opened 2020-12-04 14:55 UTC
Not an issue for now, but i would just like to chip in this report, and also get some insight into what the problem is.
It was fine for around a week now, but the following happened.

### Expected Behavior
Canvas loads up my scene with the preconfigured size, background and elements.

### Current Behavior
Blank black canvas, nothing on screen but all sprites, containers are loaded in stage when logged, no errors.

### Solution (For Now)
After toggling the gsap plugin i've been using, (commented and uncommented) things went back to normal.

### Steps to Reproduce
gsap.registerPlugin(PixiPlugin) // Everything's fine for now
PixiPlugin.registerPIXI(PIXI) // after toggled these lines
let pixi = new PIXI.Application(options)
document.body.appendChild(pixi.view)

### Environment
- **`pixi.js` version**:  5.3.3
- **Browser & Version**:  Google Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- **OS & Version**: Windows 10 Pro, build 1909

**Comment by bigtimebuddy** [comment] 2020-12-04 15:15
Curious. Can you create a reproduction of this on codepen or jsfiddle? I have not heard of this yet.

**Comment by xpicer** [comment] 2020-12-04 15:25
Not sure how I can reproduce it because I did what I did above and it's resolved for now, it's like my first time opening an issue, it's more like a heads up really.

**Comment by SukantPal** [comment] 2020-12-05 17:41
You should link to which plugins you are using. `PixiPlugin` isn't an API I recognize.

**Comment by xpicer** [comment] 2020-12-08 11:16
PixiPlugin is an object import from 'gsap/PixiPlugin'

**Comment by bigtimebuddy** [comment] 2020-12-08 16:07
Thanks for heads up @xpicer. For bugs, it's only really useful if we can see a reproduction of the bug. There are lots of online tools for creating demos like jsfiddle.net, codepen.com etc. That helps us isolate if it's a code thing, documentation thing, or user-understanding thing. 

I'm going to close this because there's nothing for us to fix. Also, maybe an issue for gsap? If this pops up again for other users, hopefully they'll link to this issue. Thanks.

**Closed by bigtimebuddy** 2020-12-08 16:07 UTC
