### ISSUE TITLE
Transparent WebM videos do not clear previous alpha (Fix included!)

### ISSUE THREAD

**Issue by kurozael** [pixijs/pixi.js#4089] opened 2017-06-07 11:24 UTC
Please see https://github.com/pixijs/pixi.js/issues/3526

It's urgent for our project to have this fix implemented into the latest Pixi.js release, we don't want to have to modify ourselves.

Thanks.

**Comment by ivanpopelyshev** [comment] 2017-06-07 12:11
I do that kind of fixes in GLTexture for every of my projects. There'll be a way to make your custom uploader in v5.

Right now the best strategy is DIY:

```js
PIXI.glCore.GLTexture.prototype.uploadData = function(data, width, height)
{
	this.bind();

	var gl = this.gl;
        this.type = this.type || gl.UNSIGNED_BYTE;

	// what type of data?
	gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, this.premultiplyAlpha);


	if(width !== this.width || height !== this.height || data instanceof HTMLVideoElement)
	{
		gl.texImage2D(gl.TEXTURE_2D, 0, this.format,  width, height, 0, this.format, this.type, data || null);
	}
	else
	{
		gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, width, height, this.format, this.type, data || null);
	}

	this.width = width;
	this.height = height;
};
```

**Comment by ivanpopelyshev** [comment] 2017-06-07 12:16
I suggest we add special flag for V5 default uploader, "always use texImage2D"

**Comment by ivanpopelyshev** [comment] 2017-06-08 11:09
@kurozael ping

**Comment by kurozael** [comment] 2017-06-08 15:18
Hi, yes this is fine, or can we just detect if it is a video like your example?

**Comment by saschagehlich** [comment] 2017-06-14 17:18
BTW, this issue is also causing video textures to be extremely slow:

http://codeflow.org/issues/slow_video_to_texture/

**Comment by zeh** [comment] 2017-12-12 04:24
@ivanpopelyshev Thank you so much for this. Was driving me crazy. Luckily patching `upload` worked, even on TypeScript. Hopefully something like this will be merged soon.

**Comment by themoonrat** [comment] 2018-07-08 14:55
@englercj Can I just get your confirmation that you changed to using texImage2D for v5 please? Various different PRs refer each other, and I think this is solved for v5, and a workaround has been given for v4, and thus this can be closed! Thanks

**Comment by neer2005** [comment] 2018-11-06 16:33
this patch doesn't work anymore on chrome 70

**Comment by m4nuC** [comment] 2018-11-13 17:25
Confirmed that the solution above stopped working since Chrome 70 update on Window machine only. OSX still works fine. @ivanpopelyshev could this be reopened or should I create a new issue ?

**Comment by tlackemann** [comment] 2019-09-11 13:08
In case it helps anyone still running into this problem, it most certainly is an issue with `texSubImage2D` and videos.

The link @saschagehlich posted was incredibly valuable to helping dig deeper into this.

The answer/patch above no longer works for PIXI v5, instead we patched `BaseImageResource` with a similar change.

```javascript
import { resources } from 'pixi.js'

resources.BaseImageResource.prototype.upload = function(renderer, baseTexture, glTexture, source) {
  const gl = renderer.gl;
  const width = baseTexture.realWidth;
  const height = baseTexture.realHeight;

  source = source || this.source;

  gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, baseTexture.premultiplyAlpha);

  // add this line, check for video
  const isVideo = !!source.videoWidth
  if (!isVideo && baseTexture.target === gl.TEXTURE_2D && glTexture.width === width && glTexture.height === height)
  {
    gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, baseTexture.format, baseTexture.type, source);
  }
  else
  {
    glTexture.width = width;
    glTexture.height = height;

    gl.texImage2D(baseTexture.target, 0, baseTexture.format, baseTexture.format, baseTexture.type, source);
  }

  return true
}
```

The results are really quite drastic.

**Before**
![2019-09-11-082818_1058x748_scrot](https://user-images.githubusercontent.com/2633753/64699733-7160af00-d473-11e9-9d93-f720879fb965.png)

**After**
![2019-09-11-082725_1058x748_scrot](https://user-images.githubusercontent.com/2633753/64699742-76bdf980-d473-11e9-8b18-eaa3c5c5ef6a.png)

I know this issue is stale but I would like to throw my hat in the ring for an option to possibly bypass `texSubImage2D` for certain resource types. Otherwise I hope this solution helps anyone else dealing with performance issues and videos.

**Comment by kurozael** [comment] 2019-12-18 09:13
I'm just bumping this because it still needs addressing.

**Closed** 2020-03-31 09:46 UTC
Labels: Resolution: Won't Fix, Type: Bug, Version: v4.x
