### ISSUE TITLE
Pixi.js canvas clipping issue on Android

### ISSUE THREAD

**Issue by acmoles** [pixijs/pixi.js#4015] opened 2017-05-12 17:43 UTC
In Chrome on android, Pixi canvas experiences unexpected clipping which isn't present on Desktop Chrome with an equivalent version.

Android Chrome version 58.0.3029.83, Desktop Chrome version 58.0.3029.110
Android 7.0.0, Desktop MacOS 10.12.4
Pixi versions tested: 4.2.2, 4.5.1

Minimal live test case: https://acmoles.github.io/Pixi-android-test/
Link to corresponding GIT repo: https://github.com/acmoles/Pixi-android-test

(look out for only the bottom left corner of the circle being visible on Android, but the whole circle being visible on Desktop)

**Comment by acmoles** [comment] 2017-05-14 17:00
I narrowed the issue down to adding `{antialias: true}` when creating a PIXI renderer/app. Switching to `{antialias: false}` fixes the issue.

**Comment by kcbleeker** [comment] 2017-05-15 11:41
@acmoles I'm investigating an issue that sounds very similar. Are you experiencing your issue on multiple different devices?

**Comment by acmoles** [comment] 2017-05-18 18:27
@kcbleeker I've only had the chance to test on one device - are you able to reproduce the error on another Android device running Chrome 58.0.3029.83?

**Comment by kcbleeker** [comment] 2017-05-22 06:19
@acmoles I'm actually unable to reproduce it thus far, but have users reporting this issue on the same Chrome version. I'm hoping someone can shed some light on the cause; if it's just a case of turning off the AA option, that's acceptable for now, I guess.

Similar issues I've found with other WebGL projects:
http://discuss.cocos2d-x.org/t/webgl-doesnt-work-properly-on-chrome-in-some-android-6-7-devices/36813
https://github.com/mpetroff/pannellum/issues/388

**Comment by kcbleeker** [comment] 2017-05-26 09:26
FYI, it looks like the fellers working on chromium have found the issue: 
https://bugs.chromium.org/p/chromium/issues/detail?id=696126

**Comment by acmoles** [comment] 2017-05-30 11:38
@kcbleeker turning off AA is fine for me, thanks for having a look. Good to hear a fix is in the pipe.

**Comment by englercj** [comment] 2017-06-19 17:33
Looks like a fix for this went in, then was reverted due to breaking ARM Chromebooks, and now a new fix is up for review and should be merged in soon.

**Comment by GoodBoyDigital** [comment] 2018-02-22 23:41
Hi there! Closing this issue for now due to its inactivity. Feel free to give us a poke if you would like this issue reopened. Thanks 👍

**Closed by GoodBoyDigital** 2018-02-22 23:41 UTC
Labels: Type: Browser Bug
