### ISSUE TITLE
PIXI.RESOLUTION and renderer.resolution

### ISSUE THREAD

**Issue by JiDW** [pixijs/pixi.js#1841] opened 2015-05-22 09:40 UTC
Just a reminder to deal one way or another with the fact that PIXI.RESOLUTION and the resolution property of a renderer are not linked at this moment.

I believe PIXI.RESOLUTION should be set to renderer.resolution when you create a renderer and provide a resolution parameter to it.

**Comment by drkibitz** [comment] 2015-05-23 02:07
`PIXI.RESOLUTION` is `CONST.RESOLUTION`, and constants in pixi should probably remain as such. The only time you should modify a constant is before initializing anything, not as the result of initialization. I do think it should probably be renamed to `DEFAULT_RESOLUTION` or something maybe, e.g. everywhere it is used, it is the default:
```js
this.resolution = resolution || CONST.RESOLUTION;
``` 

I think the problem is that there are quite a few places that I can find that does not use it, and one in particular is the one that is your actual bug here:
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/renderers/SystemRenderer.js#L83

And `options.resolutions` uses yet another constant default here `CONST.DEFAULT_RENDER_OPTIONS.resolution`.

@englercj @GoodBoyDigital 

If you do a project search for `resolution = `, you can find these rather easy, some of them look like they should be changed to default to `CONST.RESOLUTION`, some do not. Not sure what the intention is for all of them myself.

**Comment by englercj** [comment] 2015-05-23 02:16
I agree with @drkibitz, we should update to use this as the fallback for all resolutions options.

**Comment by englercj** [comment] 2016-10-17 00:35
I think things should mostly be using `renderer.resolution` and I just committed a fix to properly default that property to `PIXI.RESOLUTION`. Closing this for now.

**Closed by englercj** 2016-10-17 00:35 UTC
Labels: Difficulty: Easy, Domain: API, Priority: Medium, Status: Accepting PRs, Type: Enhancement, Version: v4.x
