### ISSUE TITLE
WebGL: All Blend Modes!

### ISSUE THREAD

**Issue by mrgoonie** [pixijs/pixi.js#3029] opened 2016-09-28 16:34 UTC
Hello, it's me again! And this is not an issue 😃 

I've just walked around the internet and found this link: http://yomotsu.net/blog/2013/08/04/blendmode-in-webgl.html

I didn't understand a single word in this post, but these formulas looks promising. Just drop it here in case it could give you (or someone) an idea to make the other blend modes work on webGL context, beside those current ones. 

If it's just some random stuffs... then never mind, have a nice day!

**Comment by englercj** [comment] 2016-09-28 17:15
Duplicate of #2219.

As mentioned there, the difficulty is that we use the built-in blending functions in GL which do not provide the capacity for most of the complete blend modes people expect.

For us to do blend modes like this we would have to blend using a shader which incurs a cost and redesign we aren't yet comfortable with.

**Closed by englercj** 2016-09-28 17:15 UTC

**Comment by ivanpopelyshev** [comment] 2016-10-01 11:58
Also, https://github.com/pixijs/pixi-picture works with some of blendModes :)

**Comment by mrgoonie** [comment] 2016-10-01 12:01
Thanks for that @ivanpopelyshev, but I know PIXI.Picture plugin ! I'm just a bit more ambitious 😄

**Comment by ivanpopelyshev** [comment] 2016-10-01 12:35
@mrgoonie You can add more blendModes in form of shader. All coordinates, texture copy problems are already solved in the plugin :)
