### ISSUE TITLE
Need Documentation on JSON format - Online examples don't work

### ISSUE THREAD

**Issue by patientplatypus** [pixijs/pixi.js#4223] opened 2017-08-12 20:01 UTC
I am trying to follow along with the guide provided here: 

https://pixijs.github.io/examples/#/demos/animatedsprite-demo.js
- and after a bit of digging here is the sheet they use for their texture mapper
https://github.com/pixijs/examples/blob/gh-pages/required/assets/mc.json

To get an example up of a simple animated sprite. The issue that I am having is that I am following along almost exactly and I am getting an error - if the example online is not working it might need to be updated. 

The example has: 

```
var app = new PIXI.Application();
document.body.appendChild(app.view);

app.stop();

PIXI.loader
    .add('spritesheet', 'required/assets/mc.json')
    .load(onAssetsLoaded);

function onAssetsLoaded() {

    // create an array to store the textures
    var explosionTextures = [],
        i;

    for (i = 0; i < 26; i++) {
         var texture = PIXI.Texture.fromFrame('Explosion_Sequence_A ' + (i+1) + '.png');
         explosionTextures.push(texture);
    }
```

Where I have:

```
  componentDidMount(){
    this.renderer = PIXI.autoDetectRenderer(1366, 768);
    this.refs.gameCanvas.appendChild(this.renderer.view);
    this.stage = new PIXI.Container();
    this.stage.width = 400;
    this.stage.height = 400;

    console.log(littlemarioforwardwalkjson)

    PIXI.loader
        .add(littlemarioforwardwalkpng, littlemarioforwardwalkjson)
        .load(()=>this.spriteLoaded());

    // console.log(PIXI.utils.TextureCache);

  }

  spriteLoaded(){
    console.log('yolo');
    var frames = [];
    var index = 0;
    console.log('hello there sailor');
    console.log(PIXI.utils.TextureCache)
    for (var i = 0; i < 3; i++) {
          index = i+46;
          var texture = PIXI.Texture.fromFrame("mario_characters1_"+index+".png");
          marioTextures.push(texture);
     }
  }

```
The error I am getting is: 

`Error: the frameId “mario_characters1_46.png” does not exist in the texture cache`

This is frustrating as my texturepacker json file is displaying correctly: 

```
{"frames": {

"mario_characters1_46.png":
{
	"frame": {"x":0,"y":0,"w":12,"h":15},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":12,"h":15},
	"sourceSize": {"w":12,"h":15},
	"pivot": {"x":0.5,"y":0.5}
},
"mario_characters1_47.png":
{
	"frame": {"x":12,"y":0,"w":11,"h":16},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":11,"h":16},
	"sourceSize": {"w":11,"h":16},
	"pivot": {"x":0.5,"y":0.5}
},
"mario_characters1_48.png":
{
	"frame": {"x":23,"y":0,"w":15,"h":16},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":15,"h":16},
	"sourceSize": {"w":15,"h":16},
	"pivot": {"x":0.5,"y":0.5}
}},
"meta": {
	"app": "http://www.codeandweb.com/texturepacker",
	"version": "1.0",
	"image": "littlemarioforwardwalk.png",
	"format": "RGBA8888",
	"size": {"w":38,"h":16},
	"scale": "1",
	"smartupdate": "$TexturePacker:SmartUpdate:ae9c1a55b9f5884f4a4c0182ea720ca9:80c341baf7877296bb8143f4c51a5998:383ea93646790c53db2201f0624e779e$"
}
}
```

If I console.log(PIXI.utils.TextureCache) I get:

`{data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACYAAAAQCAYAAAB6Hg0eAAAACXBIWXMAAAsTAAALEwEAmpwYAAABUUlEQVRIx6VVPZqFIAxM/DwE1+B1WL5j0NrucWxtPcYr106uwS2yxQobMWB0aVSciTP5QYRikTVU7mGI+BT3lIdXJCmIFqcRVeP1fHN9xXzvrP/dCws46wG/FryLK9cdXpduvkegBE7Xg9vJE02etLhy/y6vE52F5eCMP2txkrg7POSOJDc1UVe4YT72rzZ+4qGU0mpjsj7Q4p7GF13lrGwG1leEYQakyVMiZvf7+1qWWnH5MEi8QwY0ZSsxrY+k7NQ4tUnNzZ8CcIKmRBk/vsFtBtxmxFI5689ZGd85RjbHDJxKc3Xw1coiYfOE7YZaByyPP8yAfesDYllZXznrAez+Yv60h+Xi1CdriJe1KzMg/U74M4aIJxNM1NNfUbn6v4aNhylaoTExISKBIdg+pwaGcJ7IFeKhIlx8TbRqvCVxUqYlPMfVjhO1MM3SiP+PuB9QuQ5f9MhyUAAAAABJRU5ErkJggg==: Texture}`

So it would seem that the error is saying that the Texture Cache is only seeing one image blob - however, calling Texture.fromFrame is how the example on the website says to get it to work, and I think I am reproducing the code very closely. 

I do not normally post errors in github repos but there seems to be a problem either with the documentation or something is broken - the example as it is can't be reproduced in a "hello world" style animation. 

Please advise.

NOTE: I have also made a stackoverflow question here: https://stackoverflow.com/questions/45654490/cant-get-a-sprite-animation-run-in-pixijs-on-react

**Comment by patientplatypus** [comment] 2017-08-12 20:36
NOTE: I've gone back and looked at the example again. 
Take a look how the PIXI.loader is defined:
```
PIXI.loader
    .add('spritesheet', 'required/assets/mc.json')
    .load(onAssetsLoaded);
```

It mentions 'spritesheet' but provides no path to where it is so I can't test what format the image is in, or if it is a base64 blob like in my example. In fact, I can't find it anywhere in the examples repository when searching (I've searched and come up empty, not searched and had an overwhelming list). This means that the example is not clear enough to debug the above problem without further input.

**Comment by djmisterjon** [comment] 2017-08-12 20:36
+1 need same help here
https://github.com/pixijs/pixi.js/issues/4221

**Comment by patientplatypus** [comment] 2017-08-12 20:37
Sorry for closing the issue.

**Comment by patientplatypus** [comment] 2017-08-12 20:38
NOTE: I've gone back and looked at the example again.
Take a look how the PIXI.loader is defined:

```
PIXI.loader
    .add('spritesheet', 'required/assets/mc.json')
    .load(onAssetsLoaded);
```

It mentions 'spritesheet' but provides no path to where it is so I can't test what format the image is in, or if it is a base64 blob like in my example. In fact, I can't find it anywhere in the examples repository when searching (I've searched and come up empty, not searched and had an overwhelming list). This means that the example is not clear enough to debug the above problem without further input.

**Comment by patientplatypus** [comment] 2017-08-12 22:17
Note - I've found that this is a deal breaker for me. Examples should work and here they do not. I am going to be switching to a different animation library.

**Comment by ivanpopelyshev** [comment] 2017-08-12 22:46
Use TexturePacker or Shoebox, output format is JSON(hash) or JSON(pixi)., Though there are differences , sometimes you have manually look into pixi spritesheet sources and what output was produced by those tools. 

If you think you'll find animation library that doesn't require from you knowledge of its sources and documentation, you'll be very disappointed.

**Comment by ivanpopelyshev** [comment] 2017-08-12 22:52
Im sorry, I'm just very frustrated with your posts, i just read another one. I hate webpack and I dont know why people even think that it'll be smooth if they dont want to spend time to help us with making good configs and documentation on it. I mean, if I go here and ask "WHY IT ISNT WORKING IN SCALA.JS????" , how will you like that?

**Comment by ivanpopelyshev** [comment] 2017-08-12 22:54
As a good example, @cursedcoder helped us a lot with pixi-spine to make the plugin working on every available build system including webpack.

**Comment by patientplatypus** [comment] 2017-08-12 23:00
I don't think it's a webpack issue - I've managed to import the Pixi library correctly, and import both the atlas and the image. It just doesn't work following the same format as the example posted online. *Shrugs*

**Comment by ivanpopelyshev** [comment] 2017-08-12 23:07
Post complete example (with json and everything) and I'll show you how to debug it :)

**Comment by patientplatypus** [comment] 2017-08-12 23:14
Sure. 

This is the website I'm working on. npm start -> navigate to blogs archive -> blog post 2.

Here is the project. 

https://github.com/patientplatypus/professional_portfolio

The index.js file here is where I am working.

https://github.com/patientplatypus/professional_portfolio/tree/master/src/components/pages/blogs/blogtwo

Error is 

`Error: the frameId “mario_characters1_46.png” does not exist in the texture cache`

**Comment by ivanpopelyshev** [comment] 2017-08-12 23:18
There are two places to look:

1) PIXI.loader.resources['spritesheet'] shuld contain the list of parsed textures
2) use breakpoints somewhere in the https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/Spritesheet.js , check how its parsing your stuff.

**Comment by ivanpopelyshev** [comment] 2017-08-12 23:22
I'm going to sleep, I'll look tomorrow into your code if you still have that problem.

**Comment by patientplatypus** [comment] 2017-08-12 23:25
Good night.

**Comment by englercj** [comment] 2017-08-13 16:36
Correct me if I am wrong @patientplatypus, but I think this may be the same as #4219? I'm going to close this one since I answered there, but if you have any more issues please let us know.

Thanks!

**Closed by englercj** 2017-08-13 16:36 UTC

**Comment by patientplatypus** [comment] 2017-08-13 16:44
You may close this if you wish, but I still cannot get this to work. I've looked at your comments and while long, it doesn't seem to address the issue I had. I've moved on to other things I can be more productive in.

**Comment by englercj** [comment] 2017-08-13 17:11
Then it seems like I don't fully understand what problem you are having. I've used webpack and pixi in the past effectively, so I'm pretty sure this is just a misunderstanding or misconfiguration. A repository that reproduces your problem would be a good way to move forward with helping you, that way I can look at your project layout and help you get it in a working state.

**Comment by patientplatypus** [comment] 2017-08-13 17:14
There is a repository that I linked to upthread. I'm sure there is a misunderstanding, but where it is or how to solve it I do not know.

**Comment by englercj** [comment] 2017-08-13 22:07
OK, so here is how your configuration is loading the json/png resources for Blog 2.
It is actually inlining the image as a data-uri, and the json file is being loaded from disk,
parsed, and inserted into your source as an object.

This is because your config says to load images as base64-encoded data-uris (via the [`url-loader`](https://github.com/webpack-contrib/url-loader)):

```js
const assets = () => () => ({
  module: {
    rules: [
      { test: /\.(png|mov|m4v|jpe?g|svg|pdf|woff2?|gif|ttf|eot)$/, loader: 'url-loader?limit=8000' },
    ],
  },
})
```

And json is loaded by default as the object in [v2 of webpack](https://webpack.js.org/guides/migrating/#json-loader-is-not-required-anymore):

> When no loader has been configured for a JSON file, webpack will automatically try to load the JSON file with the [`json-loader`](https://github.com/webpack/json-loader).

Ok. Now that we know that, we know that you don't need to use the loader to load your resources. They are being inlined by webpack for you.

Because of that, instead of loading these assets lets just use them!

```js
// imports that will be resolved by webpack according to the config
import * as PIXI from 'pixi.js';
import littlemarioforwardwalkpng from '../../../../../public/mario_characters/littlemarioforwardwalk.png';
import littlemarioforwardwalkjson from '../../../../../public/mario_characters/littlemarioforwardwalk.json';

// boilerplate setup stuffs
var renderer = PIXI.autoDetectRenderer();
var stage = new PIXI.Container();

// create a base texture from the data-uri that webpack gives you
var baseTexture = PIXI.BaseTexture.fromImage(littlemarioforwardwalkpng);

// use the JS Object that webpack parsed from the json file to create a spritesheet
var spritesheet = new PIXI.Spritesheet(baseTexture, littlemarioforwardwalkjson);

// parse the object data and the base texture to create textures for each frame
spritesheet.parse(() => {
    // `spritesheet.textures` now has a texture for each frame, but in an object keyed
    // by the name of the frame. This transforms that object into an array of frames so
    // we can pass it directly into an animated sprite
    var textures = Object.keys(spritesheet.textures).map((t) => spritesheet.textures[t]);

    // create the animated sprite
    var animatedSprite = new PIXI.extras.AnimatedSprite(textures);

    // slow down the anim speed a bit, and play the animation
    animatedSprite.animationSpeed = 0.25;
    animatedSprite.play();

    // add it to the stage and render!
    stage.addChild(animatedSprite);
    animate();
});

function animate() {
  requestAnimationFrame(animate);
  renderer.render(stage);
}
```

Note that the spritesheet parsing I am doing here is very similar to what the loader's
middleware for handling spritesheets does: https://github.com/pixijs/pixi.js/blob/574174abbb432e16f98f7ce31708412aaed95f95/src/loaders/spritesheetParser.js#L35-L46

After these changes it animates as expected. Hopefully this helps explain what is going
on in your webpack config, and how you can integrate with PixiJS.

**Comment by patientplatypus** [comment] 2017-08-13 22:49
Thank you it now works.

**Comment by bigtimebuddy** [comment] 2017-08-13 22:56
:+1: thanks @englecj!

**Comment by ivanpopelyshev** [comment] 2017-08-14 06:16
👍 for helping with webpack, again.

**Comment by rhernandog** [comment] 2018-05-20 00:33
@englercj 
![Alt Text](https://media.giphy.com/media/V6P1hm3nVD9M4/giphy.gif)
