### ISSUE TITLE
Video and BLEND_MODES not working with >= v4.0.1

### ISSUE THREAD

**Issue by williammanco** [pixijs/pixi.js#3114] opened 2016-10-15 10:10 UTC
Hi Mathew and GoodBoy team,
I have found a possible bug, if I use the pixi.js version 4.0.0, a video as texture and blending mode work properly but **with versions > 4.0.0 stops working** (with images works).

A piece of code
`var mask = new PIXI.Sprite(new PIXI.Texture.fromVideoUrl('clip.mp4'));`
`var bg = new PIXI.Sprite(new PIXI.Texture.fromImage('image.jpg'));`
` stage.addChild(bg);`
 `stage.addChild(mask);`
`mask.blendMode = PIXI.BLEND_MODES.SCREEN;`

Good work boys
William

**Comment by englercj** [comment] 2016-10-15 14:58
Likely a duplicate of #2979. This has been fixed in the `dev` branch and will go out with v4.1 soon.

**Closed by englercj** 2016-10-15 14:58 UTC
