### ISSUE TITLE
problen with the antialias made goole  render interval is too long,

### ISSUE THREAD

**Issue by fengFanYong** [pixijs/pixi.js#2939] opened 2016-09-10 09:13 UTC
if I setting antialias for true ,the animate Refresh time as 37s in goole;but if I setting antialias for false,the animate Refresh time as 17s in goole;
it no difference the antialias for true or false in IE;
code as below:

```
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>js test</title>
    <style>
        body {margin: 0;padding: 0;background-color: #000000;}
    </style>

    <script src="./pixi.min.js"></script>

</head>

<body>
<script>
    var stage = new PIXI.Container();
    var render = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, {antialias: true});
    document.body.appendChild(render.view);

        bt = new PIXI.Sprite();

        bt.on('mousedown', onDragStart);
        bt.on('touchstart', onDragStart);

        bt.on('mouseup', onDragEnd);
        bt.on('mouseupoutside', onDragEnd);
        bt.on('touchend', onDragEnd);
        bt.on('touchendoutside', onDragEnd);

        bt.on('mousemove', onDragMove);
        bt.on('touchmove', onDragMove);

        bt.anchor.set(0.5);
        bt.x =150;
        bt.y = 200;
        bt.width = 140;
        bt.height = 344;

        gt = new PIXI.Graphics();
        gt.beginFill(0x123123);
        gt.drawRect(0,0,1,1);
        gt.endFill();
        bt.addChild(gt);
        stage.addChild(bt);




    var time = Date.now();
    requestAnimationFrame(update);
    var startTime = Date.now();
    var count = 0;
    var sum = 0;
    function update() {
        count ++;
        if(count == 100){
            var endTime = Date.now();
            console.log("____ render interval: %d ms\n", endTime-startTime);
            startTime = Date.now();
            count = 0;
        }
        requestAnimationFrame(update);
        render.render(stage);
    }

    function onDragStart(event) {
        this.data = event.data;
        this.dragging = true;
    }

    function onDragEnd() {
        this.dragging = false;
        this.data = null;
    }

    function onDragMove() {
        if (this.dragging)
        {
            var newPosition = this.data.getLocalPosition(this.parent);
            this.position.y = newPosition.y;
        }
    }
</script>
</body>
</html>
```

PIXI version v4.0.1;
brower : 52.0.2743.82;
win7: Enterprise 64bits ;
cpu : inter G3260;
Thank!

**Comment by englercj** [comment] 2016-09-14 15:53
Duplicate of #2944?

**Closed by englercj** 2016-09-14 15:53 UTC
Labels: duplicate
