### ISSUE TITLE
Incorrect Transparency Amount With Additive Sprites

### ISSUE THREAD

**Issue by MattOstgard** [pixijs/pixi.js#2248] opened 2015-12-15 01:04 UTC
Originally I posted this as a bug with pixi-spine before realizing that it is actually an issue with pixi itself: https://github.com/pixijs/pixi-spine/issues/68

Below is an image and source to reproduce the problem. It appears as if alpha is being applied twice to sprites with additive blend modes and as a result a faded out sprite can appear barely visible, while the same values in other programs (photoshop, spine) would still be clearly visible. The top bar uses normal blend mode, and the bottom two additively blended bars should appear exactly the same as the top since the background is black.

I created it by making 11 white sprites and tinting the alpha of each at increments of 10 percent and setting the blend mode to additive.

You can see the issue here: http://codepen.io/mgard/pen/MKKWLR

![download](https://cloud.githubusercontent.com/assets/6550818/11798884/eb69bde4-a283-11e5-978b-6f7ef7ae7be5.png)

**Comment by ivanpopelyshev** [comment] 2016-01-05 11:15
And we have that problem in production: 

http://forums.rpgmakerweb.com/index.php?/topic/53817-show-picture-in-additive-mode-renders-notably-different-incorrectly-in-webgl-mode/

**Comment by MattOstgard** [comment] 2016-01-05 19:01
Quick update. I believe changing the blendFunc variables from [gl.SRC_ALPHA, gl.DST_ALPHA] to [gl.ONE, gl.ONE] might fix it. Here is an example:
http://codepen.io/mgard/pen/jWBVNa?editors=001

It's working because in TextureShader.js the vertex colors get premultiplied by the alpha. Apparently the texture rgb is also premultiplied by the alpha channel even though the shader doesn't actually do this. I guess browser passes off the texture this way? I'm surprised if that is the case. I expect other blend modes will also have to be changed in a similar way, but haven't tested anything else yet.

**Comment by ivanpopelyshev** [comment] 2016-01-05 19:07
so it also depends on if there were premultiplied alpha in texture and in webglrenderer itself

**Comment by MattOstgard** [comment] 2016-01-05 19:36
Looks like there is an option in webgl on whether textures get premultiplied or not, which by default it does premultiply:
```javascript
gl = canvas.getContext("webgl", {
  premultipliedAlpha: false  // Ask for non-premultiplied alpha
});
```
Copied from: http://webglfundamentals.org/webgl/lessons/webgl-and-alpha.html

This is important to note because if you are using RGBA as masks it will not work as expected. For instance scrolling the RGB while keeping alpha channel as a stationary mask.

**Comment by ivanpopelyshev** [comment] 2016-01-05 20:01
PIXI has that too: { "transparent": "notMultiplied" } or just {"transparent": "false"} for renderer

**Comment by JonasT** [comment] 2016-01-05 20:07
Yes, however the default for this pixi.js option *is* false, which should result in WebGL's premultipledAlpha being set to false according to the pixi.js source:
```
premultipliedAlpha:this.transparent && this.transparent !== 'notMultiplied',
```
..and RPG Maker doesn't change that pixi option when creating the renderer, so as a result it should already be disabled.

**Comment by MattOstgard** [comment] 2016-01-06 01:47
@JonasT wow that is really weird. Somewhere along the way it must be getting reset because I just did a test where I made a custom shader that discards the alpha channel so we can see only the RGB.
http://codepen.io/mgard/pen/jWBmrZ

If it wasn't being premultiplied the image would be white. If you want to be sure the image itself isn't premultiplied you can get the 1 pixel tall png here: https://dl.dropboxusercontent.com/u/36289/xfer/2015/transparent_gradient_11x1.png

**Comment by JonasT** [comment] 2016-01-06 02:04
I'm not even sure what premultiplied means, so I don't know how that 1 pixel thing should look like and why. I just wanted to help out by checking what options are set in pixi.js by RPG Maker.

I can test something else if you want, but I'd need clear instructions on what you'd need tested. (e.g. do you want me to make a black background and put that image in additive blending mode in RPG Maker in front of it and make a screenshot?)

**Comment by JonasT** [comment] 2016-01-06 02:44
I can confirm adding those lines of code to the project fixes additive blending:

```javascript

(function() {

PIXI.WebGLRenderer.prototype._preAdditiveFix_mapBlendModes =
    PIXI.WebGLRenderer.prototype.mapBlendModes;
PIXI.WebGLRenderer.prototype.mapBlendModes = function()
{
    var fixAdditive = false;
    if (!PIXI.blendModesWebGL) fixAdditive = true;
    var returnValue = this._preAdditiveFix_mapBlendModes();
    if (fixAdditive) {
        var gl = this.gl;
        PIXI.blendModesWebGL[PIXI.blendModes.ADD] = [gl.ONE, gl.ONE];
    }
    return returnValue;
};

})();
```

**Comment by MattOstgard** [comment] 2016-01-06 20:20
To do an official fix there are two options that I can think of:

1) We leave premultiplication on textures on and change the blend mode constants to reflect that. Normal blend mode would remain the same, but additive would change. Other blend modes might also not be working with premultiplication, I haven't tested that.
I posted an example of that earlier here: http://codepen.io/mgard/pen/jWBVNa

2) Turn premultiply off by default (more standard for opengl) and still have to change blend modes. Additive constant would remain the same, but normal blend mode would have to change. Like with the first option other blend modes will probably have to change as well.
You can see an example I just did of that here: http://codepen.io/mgard/pen/XXMYqQ

Both options look like the same amount of work. I think option 2 is how most developers would expect it to work by default so I think that is the better option. This change may affect other things I'm not aware of so I'd like to hear from the devs on this.

**Comment by GoodBoyDigital** [comment] 2016-01-30 22:20
all fixed now, thanks @ivanpopelyshev :+1:

**Comment by ivanpopelyshev** [comment] 2016-01-30 22:20
Official decision is that defaut blending modes and shaders are working for with pre-multiplied textures.  Use non-pre-multiplied on your own risk, with your own shaders and blending.

**Closed by GoodBoyDigital** 2016-01-30 22:20 UTC

**Comment by MattOstgard** [comment] 2016-02-02 19:07
Nice thanks @ivanpopelyshev!

**Comment by drunkly** [comment] 2019-02-15 12:23
I'm stucked exactly with the same problem with a Spine Animation. I need the blend mode Additive to give the animations effects, however I can't apply them wihtout have weird effects on the transparency parts of the image when one slot is over other. I add an example to reproduce this problem:

https://codepen.io/anon/pen/MLPBaX?editors=0010

On the left-> transparent: true
On the right-> transparent: false

You can see the wierd effect if you set BlendMode=Additive with the button.

I need the transparent=true because I need to set a hight resolution background (2560x1440) and I don't want the renderer clean and redraw it each frame loop due performance issues so I'm setting a background renderer fixed and a transaparent renderer over it with my smaller game assets.

I tried the solutions given here but I could not make it works. Set the blend mode to normal is not an option.

Please, someone can point me in the right direction? Thanks in advance.
