### ISSUE TITLE
Pixi JS Renderer Drawingbuffer issues on iOS 

### ISSUE THREAD

**Issue by bhaux** [pixijs/pixi.js#4106] opened 2017-06-16 06:00 UTC
Hi there!
Pixie code which runs well on desktop seems to behave strangely on mobile.
I am a noob to pixie.js so I may with a very high likeliness be doing something wrong here.

When I use my drawing code on mobile, it appears that the canvas refreshes strangely. 
I am not redrawing the entire stroke but maintaining the DrawingBuffer and just adding new sprites to it.

No matter if I set 'legacy:' to false or true (as below) - it will give me the same result.

Thanks for taking a look!

![pixierenderer](https://user-images.githubusercontent.com/10859650/27213590-bb10a780-521c-11e7-844a-18cfd66d6953.gif)

```

initializePixieCanvas() {
    console.log("init canvas")
    const cArea = this.canvasContainer;
    const width  = 1000;
    const height = 1000;
    this.stage = new PIXI.Container();
    this.renderer = new PIXI.WebGLRenderer(
      width,
      height,
      {
          antialias: false,
          transparent: true,
          resolution: 2,
          clearBeforeRender: false,
          preserveDrawingBuffer: true,
          premultipliedAlpha: false,
          forceFXAA: true,
          legacy: true
      }
    );

    cArea.appendChild(this.renderer.view);

    this.renderer.view.style.position = "absolute";
    this.renderer.view.style.top = "0";
    this.renderer.view.style.left = "0";
    this.renderer.view.style.pointerEvents = "none";
    this.renderer.view.style.zIndex = "99";

    const cnvs = this.renderer.view;
    const scaleForHighResDisplay = true;
    if (scaleForHighResDisplay) {
        cnvs.width = width * 2;
        cnvs.height = height * 2;
        cnvs.style.width = width + 'px';
        cnvs.style.height = height + 'px';
    }

    this.pointer = new PIXI.Sprite(PIXI.Texture.fromCanvas(this.brushElement));
    this.pointer.texture.destroy();
    this.pointer.texture = PIXI.Texture.fromCanvas(this.brushElement);
    this.pointer.anchor.x = 0.5;
    this.pointer.anchor.y = 0.5;

    this.renderer.clear();

    this.stage.addChild(this.pointer);
}
```

**Comment by fcntl** [comment] 2017-06-16 06:04
You should be writing native apps for stuff this advanced.

**Comment by bhaux** [comment] 2017-06-16 06:14
The web app is surprisingly fast and it seems so close - other than that the drawingbuffer likes to regurgitate old data of course...

**Comment by bhaux** [comment] 2017-06-17 05:03
Unfortunately turning antialiasing still has a significant hit on the performance. Any help on bypassing/fixing this is bug is hugely appreciated. thx!

**Comment by GoodBoyDigital** [comment] 2018-02-22 23:44
hello! This looks like it may be a precision issue, have you tried setting the precision of the shaders to highP?

**Comment by floepi** [comment] 2018-03-15 17:58
I can confirm that it works with antialiasing enabled. 

@GoodBoyDigital : Tried setting "highP" which did not have an effect unfortunately

Any other idea how this could be fixed without the performance hit of antialiasing?

**Comment by ivanpopelyshev** [comment] 2018-03-15 18:32
@floepi 

You can try change transparency, if you dont need that background.

```js
{ transparent: 'notMultiplied'}
```

or 

```js
{ transparent: false}
```

**Comment by bhaux** [comment] 2018-03-15 20:09
unfortunately we will need both as this is a transparent paint layer... 
We should see if we can debug why this is not happening with antialiasing enabled...

**Comment by ivanpopelyshev** [comment] 2018-03-15 21:16
Do you want to debug mobile browser?

**Closed** 2019-02-24 15:31 UTC
Labels: Renderer: WebGL, Resolution: Won't Fix, Type: Question, Version: v4.x
