### ISSUE TITLE
Blend mode add on iPad air 2

### ISSUE THREAD

**Issue by hsienwei** [pixijs/pixi.js#5677] opened 2019-05-14 09:35 UTC
### Expected Behavior
https://imgur.com/HCFUJz2
### Current Behavior
On iPad air 2(A1566), it will be like below.
https://imgur.com/a/djIvp6A
Should not showing black rect.
### Possible Solution
In my case, I can use blend setting below to solve it temporary.
[gl.ONE, gl.ONE, gl.ONE, gl.ONE_MINUS_SRC_ALPHA]
### Steps to Reproduce
please try https://drive.google.com/open?id=1zjJ6shjbDylhPL9nWGIGwEHk49en_kJn
### Environment

- **`pixi.js` version**: v5.0.2
- **Browser & Version**: Safari and Chrome
- **OS & Version**: iPad air 2  OS version: 12.1.4

PC chrome(74.0.3729.131), android device and some iOS device do not have this issue.

**Comment by ivanpopelyshev** [comment] 2019-05-14 10:36
Duplicate of #5673 and #5446 , both are because our ADD is the same as in Adobe Flash.

Workaround: yes, what you said.

I believe we have to add one more ADD blendMode, however i dont know whether to choose 
`[gl.ONE, gl.ONE, gl.ONE, gl.ONE_MINUS_SRC_ALPHA]` or `[gl.ONE, gl.ONE]`. The biggest problem is the name. Any ideas?

**Comment by ivanpopelyshev** [comment] 2019-05-14 11:06
Oh, wait, sorry, its different. Maybe continuation of #5563 . Something about artifacts on iPad.

**Comment by themoonrat** [comment] 2019-07-28 17:25
@hsienwei Could you let us know if the latest verison of PixiJS fixes this for you? Thanks!

**Comment by hsienwei** [comment] 2019-08-04 15:22
Test in iPad air 2 with pixi.js version v5.1.1.  Issue fixed.

**Closed** 2019-08-04 16:36 UTC
Labels: Version: v5.x
