### ISSUE TITLE
Pixi js show Black rectangle on mobile device browser and work fine on Laptop browsers

### ISSUE THREAD

**Issue by coderweb009** [pixijs/pixi.js#5046] opened 2018-07-30 06:27 UTC
Pixi js This is what show's on dekstop browsers when i view it in mobile size 

![download](https://user-images.githubusercontent.com/29151814/43380549-26c6eb96-93ef-11e8-81b6-a2fca2807446.png)

But on mobile device it shows 
![whatsapp image 2018-07-30 at 11 55 26 1](https://user-images.githubusercontent.com/29151814/43380698-adafb8e0-93ef-11e8-9967-719147d44999.jpeg)

and also no error on console .....please help

**Comment by ivanpopelyshev** [comment] 2018-07-30 07:58
need more details.

**Comment by coderweb009** [comment] 2018-07-30 11:05
Okay i think 
![image](https://user-images.githubusercontent.com/29151814/43393689-9bbd3e52-9415-11e8-9893-045da049b8c1.png)

sprite issue 
when i remove the keeper and player form game. black rect not coming 

![image](https://user-images.githubusercontent.com/29151814/43393939-8a18546a-9416-11e8-9eca-94e6c6f8a147.png)

**Comment by ivanpopelyshev** [comment] 2018-07-30 11:32
try update pixi to latest.

**Comment by coderweb009** [comment] 2018-07-30 12:03
i am using latest but dosn't work but when i scale my sprite 1 to 0.2 then black screen go away 

![image](https://user-images.githubusercontent.com/29151814/43396265-ab83c4f6-941e-11e8-9435-afd2709a8e21.png)
![image](https://user-images.githubusercontent.com/29151814/43396270-b09813b6-941e-11e8-9a59-6017f342d6ed.png)

**Comment by ivanpopelyshev** [comment] 2018-07-30 12:17
ok, that's very strange. That's the first time i see that kind of bug. Please make a fiddle or a zip-archive with html+js that reproduces the bug.

**Comment by coderweb009** [comment] 2018-07-30 12:31
okay sure and where i can upload it

**Comment by coderweb009** [comment] 2018-07-30 13:41
Please help i reduce the sprite size 
 "size": {"w":800,"h":171},

![image](https://user-images.githubusercontent.com/29151814/43400722-100765ce-942c-11e8-8ac0-e038c776bc9c.png)


again black rect shows on mobile 

![image](https://user-images.githubusercontent.com/29151814/43400816-50f26caa-942c-11e8-909d-28724671a42f.png)

i think this is some kind of webgl issue 
[.Offscreen-For-WebGL-0x9b53c600]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

**Comment by ivanpopelyshev** [comment] 2018-07-30 14:38
Oh, i get it. Your mobile supports textures up to 4096. your texture size is 4200 :)

**Comment by bigtimebuddy** [comment] 2018-07-30 14:46
Duplicate of #4377

**Closed by bigtimebuddy** 2018-07-30 14:46 UTC
