### ISSUE TITLE
multiple filters break rendering

### ISSUE THREAD

**Issue by enriko-riba** [pixijs/pixi.js#3719] opened 2017-02-09 19:51 UTC
Not sure if this is by design but assigning multiple filters affects the whole stage where one would expect that filters affect only the display object they are applied to.
Furthermore the order of the filters changes this behavior. 
Note: using v4.3.4 release version

Example
If applying a blur and afterwards a ColorMatrix the whole stage gets colored in blue.  Using the PIXI Blur example just add:
```
var clmFilter = new PIXI.filters.ColorMatrixFilter();
littleRobot.filters = [blurFilter2,clmFilter];
```
The robot gets blured but the the stage is obscured (note that we havent even applied a colormatrix operation).

Now change the order of filters:
```
var clmFilter = new PIXI.filters.ColorMatrixFilter();
littleRobot.filters = [clmFilter, blurFilter2];
clmFilter.blackAndWhite();
```
everything looks fine

**Comment by mderk** [comment] 2017-02-17 17:14
Might to be related:
https://codepen.io/anon/pen/vgwLbv

When you apply both hue and brightness filters to a sprite, image alpha is ignored and the sprite become opaque. 
This is a regression from [at least] 4.2.3.

**Comment by themoonrat** [comment] 2017-02-17 17:46
Putting https://d157l7jdn8e5sf.cloudfront.net/dev/pixi.js into your codepen, it appears that the latest development build has this fixed

**Comment by mderk** [comment] 2017-02-17 18:02
Yes, and the original issue by @enriko-riba seems to be fixed too in dev:
http://codepen.io/anon/pen/ZLNLNE

Thanks!

**Comment by englercj** [comment] 2017-04-17 03:09
Closing since this seems fixed.

**Closed by englercj** 2017-04-17 03:09 UTC
Labels: Domain: API, Plugin: Filters, Renderer: WebGL, Type: Bug
