### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by danipaleu** [pixijs/pixi.js#3866] opened 2017-03-23 16:08 UTC
Uncaught TypeError: Cannot read property 'push' of undefined
    at FilterManager.freePotRenderTarget (pixi.js:114)
    at FilterManager.popFilter (pixi.js:114)
    at MaskManager.popSpriteMask (pixi.js:114)
    at MaskManager.popMask (pixi.js:114)

Hello , I am receiving this error after a while playing the game, and I need to restart the PC for the game to work second time, can somebody help me with this ?

**Comment by GoodBoyDigital** [comment] 2017-03-24 11:29
Hi there! Please can you provide more information. Thanks!

**Comment by englercj** [comment] 2017-04-17 23:28
Hey @danipaleu, do you have a code sample that reproduces this issue that we can investigate?

Thanks!

**Comment by nunocf** [comment] 2018-02-23 12:53
We've come across the same problem over the past few weeks and we've narrowed it down to a key generation not matching it's key on the filter's map.

in freePotRenderTarget() function in FilterManager.js
```
freePotRenderTarget(renderTarget)
    {
        const minWidth = renderTarget.size.width * renderTarget.resolution;
        const minHeight = renderTarget.size.height * renderTarget.resolution;
        const key = ((minWidth & 0xFFFF) << 16) | (minHeight & 0xFFFF);

        this.pool[key].push(renderTarget);
    }
```
For us, it doesn't break on all of the devices.
When it does happen, the renderTarget used in this function has a different width and height to the one used when generating the key for the pool.
At the moment it's unclear wether this is because we're handling a different renderTarget or if the width and height have been recalculated at some point (this issue only happens for a few of our users, and even the same copy of the code hosted on another domain works fine).

We've come up with a way of avoiding the error, but we're causing a memory leak in it's place.
the solution is as follows:
```
freePotRenderTarget(renderTarget) {
        const minWidth = renderTarget.size.width * renderTarget.resolution;
        const minHeight = renderTarget.size.height * renderTarget.resolution;
        let key = ((minWidth & 0xFFFF) << 16) | (minHeight & 0xFFFF);

        if (this.pool[key] === undefined) {
            for (var current in this.pool) {
                key = current;
            }
        }
        this.pool[key].push(renderTarget);

    }
```
bear in mind this only works in our case because we never use more than one key in our pool.

I hope this information helps you guys coming up with a possible fix for this. 
Thanks!
nunocf

**Comment by ivanpopelyshev** [comment] 2018-04-23 13:28
anyway, that thing is fixed in pixi-v5. 

@bigtimebuddy Can I please backport it to v4? Its about this key: https://github.com/pixijs/pixi.js/blob/next/packages/core/src/filters/FilterSystem.js#L414

**Comment by bigtimebuddy** [comment] 2018-04-23 13:35
@ivanpopelyshev okay, go for it

**Closed** 2018-07-15 12:06 UTC
Labels: Domain: API, Plugin: Filters, Status: Needs More Info, Version: v4.x
