### ISSUE TITLE
baseTexture.wrapMode=PIXI.WRAP_MODES.CLAMP not working in beginTextureFill

### ISSUE THREAD

**Issue by yuyic** [pixijs/pixi.js#7053] opened 2020-12-07 10:45 UTC
### Expected Behavior
graphics.beginTextureFill can make a no-repeat filling

### Current Behavior
graphics.beginTextureFill will repeat texture whatever I set texture.baseTexture.wrapMode = PIXI.WRAP_MODES.CLAMP

### Possible Solution
Use PIXI.Sprite instead, but I need to fill hundreds of times in each frame , it means I need to transform hundreds of Sprites in each frame, it may cause performance issue, I think beginTextureFill hundred times is faster than transform in hundreds of sprites?

### Steps to Reproduce
https://www.pixiplayground.com/#/edit/aEldlK8d5fevbe9zXL5In
### Environment
pixi.js 5.4.0-rc2

**Comment by SukantPal** [comment] 2020-12-12 15:45
This is a duplicate of #6714

**Comment by bigtimebuddy** [comment] 2020-12-12 16:23
Closing duplicate and reopening original.

**Closed** 2020-12-12 16:23 UTC
