### ISSUE TITLE
Graphics | ARC drawing issue

### ISSUE THREAD

**Issue by antoninlanglade** [pixijs/pixi.js#1660] opened 2015-04-15 09:02 UTC
Hello,

When I do that :

```js
this.pixiElement = new PIXI.Graphics();
this.pixiElement.lineStyle(this.lineWidth, this.fillColor,1);
this.pixiElement.arc(this.center.x, this.center.y, this.animationRadius, this.startAngle, this.endAngle);
```

I have an issue with the arc drawing. Instead of drawing just the arc, pixi draws also a line between every updates and clears that links the two drawings. 

![capture d ecran 2015-04-15 a 11 01 58](https://cloud.githubusercontent.com/assets/1774288/7155430/f0740bb2-e35e-11e4-80f3-a18d37b40551.png)

Thanks

**Comment by englercj** [comment] 2015-04-15 14:17
Does that happen even if you use `moveTo` between arc calls?

**Comment by antoninlanglade** [comment] 2015-04-15 16:09
if I try : 

this.pixiElement.moveTo(this.center.x, this.center.y);
this.pixiElement.lineStyle(this.lineWidth, this.fillColor,1);
this.pixiElement.arc(this.center.x, this.center.y, this.animationRadius, this.startAngle, this.endAngle);

the results : 
![capture d ecran 2015-04-15 a 18 08 22](https://cloud.githubusercontent.com/assets/1774288/7163477/7f57c112-e39a-11e4-9719-978ca5f302b1.png)

**Comment by englercj** [comment] 2015-04-15 17:15
When you do arc it draws a line from the current location to where the arc starts, whether or not that is "correct" we can decide and fix it. In the mean time, you can just `moveTo` the position where the arc will start drawing.

**Comment by antoninlanglade** [comment] 2015-04-16 12:01
You're right Man !

Ring.prototype.update = function(dt){

	this.startAngle += Math.PI*2/180;
	this.endAngle += Math.PI*2/180;
	var startPoint = this.getStartPositionArc(this.startAngle,this.animationRadius);

	this.pixiElement.moveTo(this.center.x + startPoint.x, this.center.y + startPoint.y);
	this.pixiElement.lineStyle(this.lineWidth, this.fillColor,1);
	this.pixiElement.arc(this.center.x, this.center.y, this.animationRadius, this.startAngle, this.endAngle);
	
}
Ring.prototype.getStartPositionArc = function(angle, radius){
	return new Point({
		x : Math.cos(angle) * radius,
		y : Math.sin(angle) * radius
	})
}

![capture d ecran 2015-04-16 a 13 47 52](https://cloud.githubusercontent.com/assets/1774288/7180160/39ae4ec4-e43f-11e4-9383-ae7643c6a9d0.png)

I understand your point ! I feel wrong about that because of Canvas Arc drawing. I don't disagree with this solution but if I can propose to write an explaination on the doc it will be better for understanding :)

Thanks a lot for your time and your comprehension

**Comment by jwdunn1** [comment] 2015-06-16 07:10
As a workaround to this bug, after invoking the .clear() method on the Graphics object, set the property .currentPath= null; Seems to work well without memory issues, but I could be wrong.

**Comment by kittykatattack** [comment] 2015-06-30 01:26
I can also confirm that the follow code produces the image shown.
```
  let arcLine = new Graphics();
  arcLine.lineStyle(4, 0x000000, 1);
  arcLine.arcTo(0, 128, 128, 128, 64);
  stage.addChild(arcLine);
```

![f01001](https://cloud.githubusercontent.com/assets/2936104/8422146/8a2f5410-1ea5-11e5-88d8-8f0c8945f809.gif)

**Comment by englercj** [comment] 2016-09-27 23:03
Is this still an issue in the latest v4 dev? I feel like we fixed this a while ago.

**Comment by englercj** [comment] 2016-10-06 02:27
Closing this since I think it is fixed, if it still reproduces please open with a repro case using the newest dev of pixi.

You can see how to download the latest build [in the FAQs](https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build).

Thanks!

**Closed by englercj** 2016-10-06 02:27 UTC
Labels: Domain: API, Plugin: Graphics, Priority: Low, Renderer: WebGL, Status: Needs More Info, Type: Bug, Version: v4.x
