### ISSUE TITLE
v5 destroy() not working ( Cannot read property 'CONTEXT_UID' of null )

### ISSUE THREAD

**Issue by federicovezzoli** [pixijs/pixi.js#5644] opened 2019-05-03 15:41 UTC
I'm working with nuxt on a website and inside some pages components I have a pixi application running. I've noticed a high memory usage, especially when going back to a page already visited and pixi re-running an already run app. So I'm trying to force some GC to free up some memory, but not having any luck.

### Expected Behavior
app to be destroyed

### Current Behavior
throws this blocking error: 
Uncaught TypeError: Cannot read property 'CONTEXT_UID' of null
at TextureSystem.destroyTexture

### Steps to Reproduce
app.destroy()

where app is 
const app = new PIXI.Application()

You can see the error here:
https://flussocreativo.netlify.com/
just click any link inside the home to trigger the destroy.

### Environment
- **`pixi.js` version**: 5.0.0

**Comment by bigtimebuddy** [comment] 2019-05-03 15:49
This does not reproduce. Can you please provide an example that reproduces this? The link you posted is 404.
https://pixiplayground.com/#/edit/Kvb2XPlUlzwHKJq1Mw4R0

**Comment by federicovezzoli** [comment] 2019-05-03 15:56
Sorry @bigtimebuddy, It was still deploying, please check again: https://flussocreativo.netlify.com/

**Comment by bigtimebuddy** [comment] 2019-05-03 19:31
@federicovezzoli It's going to be very difficult for anyone to debug this because everything is minified in that example.

Please help us track down your issue by creating a _simple_ isolated example that reproduces this issue on jsfiddle/codepen/pixiplayground. That's the best way for us to identify the underlying issue and to verify that it got fixed.

**Comment by ivanpopelyshev** [comment] 2019-05-03 21:03
Or at least give us non-obfuscated stacktrace

**Comment by andzdroid** [comment] 2019-05-03 22:06
I have the same problem:


```
TypeError: Cannot read property 'CONTEXT_UID' of null
    at TextureSystem.destroyTexture (TextureSystem.js:296)
    at BaseRenderTexture.emit (index.js:181)
    at BaseRenderTexture.dispose (BaseTexture.js:509)
    at BaseRenderTexture.dispose (BaseRenderTexture.js:133)
    at BaseRenderTexture.destroy (BaseTexture.js:492)
    at BaseRenderTexture.destroy (BaseRenderTexture.js:142)
    at RenderTexture.destroy (Texture.js:239)
    at FilterSystem.emptyPool (FilterSystem.js:512)
    at FilterSystem.destroy (FilterSystem.js:412)
    at Runner.emit (Runner.js:68)
```

**Comment by andzdroid** [comment] 2019-05-03 22:26
I have made an example to reproduce this: https://pixiplayground.com/#/edit/Kvb2XPlUlzwHKJq1Mw4R0

**Comment by bigtimebuddy** [comment] 2019-05-03 23:50
You're our hero @andzdroid. Perfect. @ivanpopelyshev could you look into that destroy?

**Comment by federicovezzoli** [comment] 2019-05-04 07:42
thanks @andzdroid !

**Comment by ivanpopelyshev** [comment] 2019-05-04 21:26
Please check if pixijs.download/dev-texture-system-destroy/pixi.js works for you.

I did not work on complete texture and shaders recycle yet, I only fixed geometries. But at least I can make it that way it won't crash :) It should work in your case because we also cause `loseContext` event on context and it clears whatever we forgot to clear automatically.

**Comment by federicovezzoli** [comment] 2019-05-05 10:28
Yes, it works for me, thanks @ivanpopelyshev !
Now waiting for it to be merged to master.

**Comment by bigtimebuddy** [comment] 2019-05-05 14:11
Merged!

**Closed by bigtimebuddy** 2019-05-05 14:11 UTC

**Comment by federicovezzoli** [comment] 2019-05-05 14:42
Sorry guys, I know this is probably a silly question but I'm pretty new to the npm stuff: 
How does it works to get from the master to the npm package?
thanks a lot.

**Comment by themoonrat** [comment] 2019-05-05 16:11
We have to do a new official release of PixiJS for you to pick up the new code via npm.

**Comment by bigtimebuddy** [comment] 2019-05-05 17:52
New release is coming, just have one more bug PR to approve and merge.
