### ISSUE TITLE
Out of memory chomre when loading 200k sprite ?

### ISSUE THREAD

**Issue by khiemntu** [pixijs/pixi.js#5314] opened 2018-12-29 09:06 UTC
I am using ParticleContainer to load 200k sprite object with image texture is 1KB. The chrome crash after memory inscrease to 2GB. Why my memory inscrease so much ? I see bunnymarker performance test with 100k sprite and no crash. Are there any problem in here ? Below is my algorithm:

> create ParticalContainer
> for(1 to 200k) {
>      create sprite with texture
>      add srpite to particleContainer
>  }
> render particleContainer

**Comment by ivanpopelyshev** [comment] 2018-12-29 12:52
Which version is it?

**Comment by khiemntu** [comment] 2018-12-29 13:05
4.8.2

**Comment by ivanpopelyshev** [comment] 2018-12-29 13:06
I guess there's something wrong with "autoResize" feature of particlecontainer.

**Comment by ivanpopelyshev** [comment] 2018-12-29 13:09
Btw, I see that i forgot to remove that `if`, we need to add autoResize in condition: https://github.com/pixijs/pixi.js/blob/v4.x/src/particles/webgl/ParticleRenderer.js#L135 

But it saves videomemory, not destroys it, so, your bug is different.

**Comment by englercj** [comment] 2018-12-29 16:10
Can you share a running example that reproduces please? I'd like to see exactly what you are doing.

**Comment by englercj** [comment] 2018-12-29 16:34
Unfortunately what I want to is do memory snapshots in chrome debug tools and see what is eating 2G of memory. I'd also like to experience the crash and look through logs. Since you can't share, all I can say is you should do some of those things to try and track down your issue.

**Comment by khiemntu** [comment] 2018-12-29 16:47
@englercj thanks for your suggestion

**Comment by bigtimebuddy** [comment] 2019-01-06 03:04
Closing this as I believe @englercj has offered a good explanation and suggestion.

**Closed by bigtimebuddy** 2019-01-06 03:04 UTC
