### ISSUE TITLE
lineAlignment at small sizes

### ISSUE THREAD

**Issue by georeith** [pixijs/pixi.js#6497] opened 2020-03-25 11:42 UTC
### Expected Behavior

- Inside stroke is contained within the fillable area of an object (it certainly shouldn't extend further than center stroke)
- Outside stroke edges do not clip

### Current Behavior

https://pixiplayground.com/#/edit/bvjRVoDSNkUH9TGF_Ihsm

Columns left to right are: Outside, Center, Inside
Rows are the same item

![image](https://user-images.githubusercontent.com/3090066/77532519-eb470b80-6e8c-11ea-8c88-23316b9dbe1c.png)

### Possible Solution

Eeek, I know this a tough problem, stuff starts breaking down when stroke is larger than the fillable area. 

- The outside stroke edges clipping looks like a `miterLimit` issue (could that be exposed for Graphics `lineStyle`)?
- Clipping the inside stroke to the fill of the item

### Environment

- **`pixi.js` version**: _e.g. 5.2.1
- **Browser & Version**: Chrome 80
- **OS & Version**: macOS Mojave
- **Running Example**:  https://pixiplayground.com/#/edit/bvjRVoDSNkUH9TGF_Ihsm

**Comment by ivanpopelyshev** [comment] 2020-03-25 12:27
MiterLimit is one of issues that we just dont have time for :( I would be happy to solve it but there's just so many other Graphics-related things I'm doing. I can help with debugging if you make a PR. We even had a PR before: #5302. The problem is where to get time and people resources for it.

**Comment by georeith** [comment] 2020-03-25 13:00
@ivanpopelyshev that's fair, I am just starting down my journey with pixi.js and evaluating its level of support for our current offering (as we feel the need to move to a more performant base). I have similar time constraints at the moment and like you need to put more time into bigger issues but when this is a larger priority for us I will try and revive the `miterLimit` and `lineJoin` issues.

Regarding the inside stroke escaping the fill area has this been evaluated before?

Not sure how you are implementing `lineAlignment` but I had a canvas 2D solution that doesn't require path offsetting: http://jsbin.com/gulixejotu/1/edit?html,js,output

**Comment by eXponenta** [comment] 2020-03-27 07:09
For fixing Graphics rendering and improving mitter and line joints, and Winding rulle, we should:
1. Add new tesselator
2. Drop existed Graphics implementation
3.Write new, and doesn't drop backwards campobility
4. Implement addHoles() in newest Graphics

**Comment by SukantPal** [comment] 2020-03-31 17:47
@georeith I just got line join, caps, and miter-limit merged: https://github.com/pixijs/pixi.js/pull/6502

**Comment by SukantPal** [comment] 2020-03-31 17:50
Clipping the inside stroke is a more complex problem.

We can't check if the inner stroke is inside the geometry - or at least the solution isn't going to be non-trivial. That is because it won't work for non-convex polygons and polygons whose points are entered counter-clockwise (where inner stroke is actually outside of the polygon).

**Comment by georeith** [comment] 2020-03-31 22:42
@SukantPal awesome thanks for the heads up!

Regarding the inside stroke clipping I think it's a mistake IMO to consider the non filled area of a polygon the inside based on the direction of its path.

Stroke alignment makes the most sense to me when reasoning about it to do with fill and considering the filled area of the item to be its inside.

Are you aware of the reason it works as it does currently?

**Comment by SukantPal** [comment] 2020-03-31 22:52
@georeith Line alignment is the weight of each side of the stroke. If the line width is 10px, then a 0.5 alignment means 5px on outside and 5px inside.

If it is 1, then full 10px on outside. If it is 0, then full 10px inside.

**Comment by georeith** [comment] 2020-04-01 21:12
@SukantPal thanks for the explanation. So my understanding is that its not necessarily the optimal way of it working but its a design decision based on it being more expensive to work out where the fill will be located.

The reason this is an issue for me is that I am building a drawing tool for designers and thus want them to be able to add polygons and choose their line alignment, so I am unable to control the direction of the polygons created.

I will be looking at porting my existing line alignment which uses double width stroke and composite operations to perform inside and outside strokes. Will feedback my success.

**Comment by SukantPal** [comment] 2020-05-07 17:54
@georeith Can we close this?

**Comment by georeith** [comment] 2020-05-07 18:40
@SukantPal up to you guys, I think this would still be considered unexpected behaviour for most. I can appreciate the complexity and cost in fixing it so can also appreciate the "won't fix" for this.

**Closed** 2020-05-07 20:36 UTC
Labels: 🙏 Feature Request
