### ISSUE TITLE
PIXI.Container does not have containsPoint

### ISSUE THREAD

**Issue by DavidGOrtega** [pixijs/pixi.js#4735] opened 2018-03-05 04:55 UTC
I'm looking workarounds to support Multiple gestures with Hammer.js that is the library I use the most.

I found the repo Hammer Pixi, and I tried to plug it in my code. It did't work, following the code I discovered that containers do not have containsPoint. It's weird since Graphics, Stage, Sprite... all of them contains this...

Is this a bug or is desired as it is?

**Comment by ivanpopelyshev** [comment] 2018-03-05 09:47
The difference between having no function and no empty function is that there wont be extra call. I dont know when and who decided to check for function availability there, but its not a bug. 

https://github.com/pixijs/pixi.js/blob/dev/src/interaction/InteractionManager.js#L1106

**Comment by lTyl** [comment] 2018-03-13 19:31
Try using this fork of pixi-hammer: https://github.com/mralbobo/pixi-hammer.

```displayObject.on('hammer-singletap', ()=>{console.log('Tapped!')});```

**Comment by themoonrat** [comment] 2018-07-01 10:28
@DavidGOrtega Closing as there not being a contains point is intentional. A container being 'clicked' just means 'are any of the children clicked' rather than 'has the bounds of the container been clicked'. You can always create your own containsPoint function on the container if you wish to override this behaviour

**Closed by themoonrat** 2018-07-01 10:28 UTC
Labels: Domain: API, Type: Question, Version: v4.x
