### ISSUE TITLE
WARNING: Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by JsAaron** [pixijs/pixi.js#2596] opened 2016-05-23 07:19 UTC
Excuse me
First of all, feel the author with such a good library. First time use have a few problems, problems to solve

In single-page applications using pixi. Js.  Now use the MovieClip and PIXI. Elves animated Sprite. 
A canvas corresponds to a PIXI object.  Due to performance issues.  I take multiple canvas element. Shared a requestAnimation. 

The following code：

```
maskSprite = new PIXI.Sprite(this.maskTexture[0]);
stage1.addChild(this.maskSprite);
addQueue(function() {
    renderer.render(stage1);
})

movie = new PIXI.extras.MovieClip(textures);
stage2.addChild(movie.maskSprite);
addQueue(function() {
   renderer.render(stage2);
})

addQueue = function(fn) {
    list.pust(fn)
    requestAnimation(list)
}
```
Running is normal, But page will prompt error a few times,
 `WARNING: Too many active WebGL contexts. The Oldest context will be lost.`
 I don't know if I destroy mode has a problem.I only in the renderer method invoked on the destruction.
The following code：
`renderer.destroy(true)`

The problem:
> WARNING, because the wrong to destroy?

![image](http://images.cnblogs.com/cnblogs_com/aaronjs/832802/o_4AB5688D-873E-4192-B14C-10078544441C.png)

If I didn't describe clearly, I send the source code
sprite.js
[https://github.com/JsAaron/es6-magazine/blob/master/src/lib/component/pixi/sprite.js](https://github.com/JsAaron/es6-magazine/blob/master/src/lib/component/pixi/sprite.js)
queue.js
[https://github.com/JsAaron/es6-magazine/blob/master/src/lib/component/pixi/core/queue.js](https://github.com/JsAaron/es6-magazine/blob/master/src/lib/component/pixi/core/queue.js)

**Comment by englercj** [comment] 2016-05-25 15:34
Duplicate of #2233?

**Comment by GoodBoyDigital** [comment] 2016-06-11 19:14
hello! this has been addressed in v4 (latest dev branch)
We are now destroying the context with the ```WEBGL_lose_context``` extension if it is available.

**Closed by GoodBoyDigital** 2016-06-11 19:14 UTC
