### ISSUE TITLE
Click/touch events pass through canvas

### ISSUE THREAD

**Issue by kcbleeker** [pixijs/pixi.js#3847] opened 2017-03-20 13:10 UTC
I'm working on a large and pretty mature project. We've been using PIXI for the last few months, and a few weeks ago I updated to 4.4.1. In the last few days I've been looking at an issue that seems to have cropped up. Our canvas is displayed over a bunch of other DOM elements on mobile devices.

Since moving from 4.2.2 to 4.4.1, click events can pass through the canvas to the elements behind, which is...bad.

For reference, I initialize like this: 
```javascript
this.renderer = PIXI.autoDetectRenderer({
				view: this.canvas,
				autoResize: true,
				resolution: constants.dpiScale,
				antialias: true,
				transparent: true
			});
```

Switching to WebGLRenderer or CanvasRenderer doesn't seem to affect it.
Rolling back to 4.2.2 stops the issue. Any ideas?

**Comment by ivanpopelyshev** [comment] 2017-03-20 14:05
That's known problem. @themoonrat is working on it. #3790

**Comment by andrewstart** [comment] 2017-03-20 23:19
Hmm, that sounds like a very different issue than 3790. Clicks going through the canvas to DOM elements is an interesting thing.

**Comment by andrewstart** [comment] 2017-03-21 00:01
Looking at the code, I can't think of any reason why this would happen. Could you set up an example fiddle/pen for this behavior?

**Comment by kcbleeker** [comment] 2017-03-22 09:31
Hi @andrewstart 

Will try to find time to put one together soon.

**Comment by kcbleeker** [comment] 2017-03-22 13:15
Okay, the steps for this are rather specific, and it took me a while to replicate.

The click event must also trigger moving the entire canvas out from under the pointer, AND it must be a touch event.

Use the below pen, and either use a mobile device, or emulate one in Chrome. When you click the bunny, the canvas slides right, and the div below gets a click event. Note: not a click, hold your mouse for just a half-second than you would for a  normal click.

https://codepen.io/anon/pen/qroGXR

Note: for fun, I thought I'd prove it doesn't happen in earlier versions, so I tried 4.2.3, and it still happens. Coincidentally we were and are still using 4.2.2, and it works as expected:
https://codepen.io/anon/pen/aJYgNV

**Comment by ivanpopelyshev** [comment] 2017-03-22 13:18
@kcbleeker 

Try this one: http://pixijs.download/fix-interaction-issues/pixi.js , its #3857

**Comment by kcbleeker** [comment] 2017-03-22 13:21
Hi @ivanpopelyshev 

I did a sort-of manual copy-paste of these changes into https://pixijs.download/v4.4.2/pixi.js, but the problem was still present.

**Comment by andrewstart** [comment] 2017-03-23 02:35
I played around with this, and did get it to occur in 4.2.2 as well. The problem is the canvas is moved in response to a `pointerdown` (also `touchstart`) event, and is moved clear of the area where the compatibility `mousedown` (and friends) occurs a short time later, which then happens on the DOM behind. At least when emulating touch in Chrome, calling `ev.data.originalEvent.preventDefault()` (or setting `renderer.plugins.interaction.autoPreventDefault = true`) has no effect, but it might for actual devices.

**Comment by englercj** [comment] 2017-04-17 23:30
Hey @andrewstart is this issue also fixed by #3940?

**Comment by andrewstart** [comment] 2017-04-18 02:28
No, it's more like the inverse of that bug.

**Comment by englercj** [comment] 2017-04-18 02:59
OK, I'll leave this one open then!

**Comment by alextappin** [comment] 2018-02-16 00:13
Is this still an issue with the latest version?

**Comment by lorilorr1** [comment] 2018-02-16 05:40
Sometimes BAD IS BAD

**Closed** 2019-02-24 15:31 UTC
Labels: Plugin: Interaction Manager, Resolution: Won't Fix, Status: Needs Investigation, Type: Bug, Version: v4.x
