### ISSUE TITLE
Transparent WebM videos do not render correctly

### ISSUE THREAD

**Issue by saschagehlich** [pixijs/pixi.js#3526] opened 2016-12-31 16:23 UTC
It seems that previously rendered video frames are not cleared:

https://jsfiddle.net/vm4h4928/

I dived into the code but could not find the cause of this issue. All you do is upload the texture, but this should also include transparent pixels?

**Comment by themoonrat** [comment] 2016-12-31 20:21
Interesting point - this only happens for WebGL. It displays fine on Canvas renderer

**Comment by saschagehlich** [comment] 2017-03-23 08:51
@themoonrat Anything new regarding this issue?

**Comment by englercj** [comment] 2017-03-23 15:26
Honestly not sure if this is a pixi bug since we just pass the video directly to the gl context as a texture and the browser takes care of it.

**Comment by barbarosso** [comment] 2017-05-05 08:20
@englercj It seems to be a pixi4 problem
I forked the jsfiddle and changed it to pixiv3
That one seems to do it correctly.
https://jsfiddle.net/t06hep8m/

**Comment by barbarosso** [comment] 2017-05-05 11:02
@englercj Me and my colleague @pietervanneste  did some investagation.

It seems that following part is causing the problem.


```js
if(newHeight !== this.height || newWidth !== this.width)
	{
		gl.texImage2D(gl.TEXTURE_2D, 0, this.format, this.format, this.type, source);
	}
	else
	{
    	gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, this.format, this.type, source);
	}
```

If we change it to 

```js
gl.texImage2D(gl.TEXTURE_2D, 0, this.format, this.format, this.type, source);
```
so we don't call gl.texSubImage2D, It seems to clear the texture after every frame.

**Comment by kurozael** [comment] 2017-06-07 11:23
I can confirm that @barbarosso's fix does indeed work. Can we please get this fix applied to the latest version of Pixi.js as soon as possible?

**Comment by themoonrat** [comment] 2018-07-08 15:03
I believe this is fixed in v5

**Closed by themoonrat** 2018-07-08 15:03 UTC
Labels: Renderer: WebGL, Status: Needs Investigation, Version: v4.x
