### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by simPod** [pixijs/pixi.js#6668] opened 2020-05-28 16:50 UTC
Hi I tried to check examples at https://pixijs.io/examples/#/demos-advanced/star-warp.js but there are some errors, see screen

![image](https://user-images.githubusercontent.com/327717/83169924-08f65280-a114-11ea-99eb-3c53bdb96b86.png)

**Comment by bigtimebuddy** [comment] 2020-05-28 16:54
Dev is currently broken. We are on it. Duplicate of https://github.com/pixijs/examples/issues/66

Please use a release, for example:
https://pixijs.io/examples/?v=v5.2.4#/demos-advanced/star-warp.js

**Comment by simPod** [comment] 2020-05-28 16:55
Oh, thanks!

**Closed** 2020-05-28 18:00 UTC
Labels: 🕷 Bug
