### ISSUE TITLE
Pixi.js container3d & RPG maker MV

### ISSUE THREAD

**Issue by ganzimaro** [pixijs/pixi.js#4180] opened 2017-07-25 17:46 UTC
Hello. There is a need to create a game interface using perspective, but the game engine does not have such features. I connected your pixi.js via plugins, but I get an error "updateChildTransform". Can you give a hint, how to synchronize different scripts, or other uses of 3d containers.

**Comment by ivanpopelyshev** [comment] 2017-07-25 21:07
Hello! Need more info, I can certainly help you with that.

**Comment by ivanpopelyshev** [comment] 2017-07-25 21:12
I'm writing new version of it, and depends on your problem, we can test either new plugin either whole new fork.

**Comment by Dairnon** [comment] 2017-07-26 02:57
I think the person wants a 3d container to work with MVs engine, and is having problems. Person just wants the 3d container for perspective stuff.

**Comment by ganzimaro** [comment] 2017-07-26 07:36
Dairnon rightly says. The task is to create a game interface using perspective. All that was found is your 3rd container. Since RPG Maker MV already has a pixi.js, I connected your version as a plugin and when creating a 3d container, I get an error (already just this):


_rpg_managers.js:1756 TypeError: undefined is not a function
    at Container3d.updateTransform [as displayObjectUpdateTransform] (pixi-3d.js:19907)
    at Container3d.79.Container.updateTransform (pixi-3d.js:18944)
    at Scene_Menu.updateTransform (pixi.js:8395)
    at WebGLRenderer.render (pixi.js:16312)
    at Function.Graphics.render (rpg_core.js:1467)
    at Function.SceneManager.renderScene (rpg_managers.js:1836)
    at Function.SceneManager.updateMain (rpg_managers.js:1794)
    at Function.SceneManager.updateMain (SRD_SuperToolsEngine.js:386)
    at Function.SceneManager.update (rpg_managers.js:1714)_


I apologize for the indistinct explanation.

**Comment by ganzimaro** [comment] 2017-07-26 07:44
If working with RPG Maker MV has a problem, maybe you can suggest me how to turn "PIXI.Container" into "Bitmap". It is known that when we use "cacheAsBitmap", "Bitmap" is obtained from the container, but how to interact with it now? How to get an independent Bitmap?

**Comment by ivanpopelyshev** [comment] 2017-07-26 07:53
Tell me first what do you want to see in the end? Where do you want to apply thse 3d features?

**Comment by djmisterjon** [comment] 2017-07-26 08:11
@ivanpopelyshev
i tink is direcly relied to this.
am also on the rmmv engine 
https://github.com/pixijs/pixi.js/issues/4168
he maybe talk about the scaling perspective.
We had discussed it here.

**Comment by ganzimaro** [comment] 2017-07-26 08:11
Thanks for the help, however I will not bother you with additional tasks. The only thing I would like to know, you do not know about "cacheAsBitmap", as I wrote above?

**Comment by ganzimaro** [comment] 2017-07-26 08:25
The code for transforming a single image is already available and works. In the container you need to put text and images and then transform it in perspective with all the children.
Now I have every text and image transformed separately, which slows the game. As an option, I think to make an image out of the container with the children, and after that, create a perspective.

If nothing happens, the interface designer will keep on racking his brains)

**Comment by ivanpopelyshev** [comment] 2017-07-26 08:35
Ah, that's good :) 

But you didnt give me enough info to help your case. You can share project in dropbox like @Dairnon did , and join pixijs slack, i have sent you invite.

**Comment by ganzimaro** [comment] 2017-07-26 08:58
![demo7](https://user-images.githubusercontent.com/1789453/28612859-3b591a34-71f9-11e7-84e2-bfd5d3f39d3d.png)
@ivanpopelyshev 
At the moment I can post the photoshop image while I prepare the project for download. The task is to make the left and right blocks in perspective.

**Comment by ivanpopelyshev** [comment] 2017-07-26 09:29
Тваюжмать.

Yeah, I think that can be done with partial solution. Let me think on that a bit :)

**Comment by ganzimaro** [comment] 2017-07-26 09:48
Well I will wait. For now I will experiment further. So you do not know how to take Bitmap as image from "cacheAsBitmap"?

**Comment by ivanpopelyshev** [comment] 2017-07-26 10:10
I hate both RMMV Bitmap and cacheAsBitmap. You can look at Bitmap.snap(...) it has some useful code: renders stuff into renderTexture and presents as bitmap.

**Comment by ganzimaro** [comment] 2017-07-26 13:27
@ivanpopelyshev Thank you. "Bitmap.snap" gave an excellent basis in obtaining images from the container. Here is the result:

![71](https://user-images.githubusercontent.com/1789453/28623606-315fd4d4-721f-11e7-9938-842dd7890f09.png)

Of course, need to make some more corrections to the code, but this is a solution to the problem with the perspective, at least with the current capabilities RPG Maker MV.

Solution code:


```
function getBitmapContainerLGS(container, width, height) {
    var bitmap = new Bitmap(width, height);
    var context = bitmap._context;
    var renderTexture = PIXI.RenderTexture.create(width, height);
    Graphics._renderer.render(container, renderTexture);
    var canvas = Graphics._renderer.extract.canvas(renderTexture);
    context.drawImage(canvas, 0, 0);
    renderTexture.destroy({ destroyBase: true });
    bitmap._setDirty();
    return bitmap;
};

var transform = [0, 0, 0, 3.5, 0, -3.5, 0, 0];
var snap = getBitmapContainerLGS(this.menuCharacter, 400, 500);
var sprite = new Sprite(snap);
sprite.bitmap.drawTransformLGS(transform);//Transform Function
this.addChild(sprite);
```

**Comment by ivanpopelyshev** [comment] 2017-07-26 17:18
Btw, we found one critical error with renderTextures that can affect snap, it is fixed in 4.5.4, and it will go to official RMMV. I think you can just swap your pixi.js for latest one.

**Comment by ivanpopelyshev** [comment] 2017-07-28 23:07
Alpha version is ready: https://github.com/pixijs/pixi-projection/

**Comment by ganzimaro** [comment] 2017-07-29 11:26
Thanks.
If I understand correctly, it should work, but there is nothing on the screen, although everything is in the container if you look at the code.


```
var container = new PIXI.projection.Container2d();
var sprite = new Sprite(***);
container.addChild(sprite);

this.addChild(container);
container.proj.setFromQuad([0, 0, 0, 0, 0, 0, 0, 0], container .anchor, 570, 790);
```


What did I miss?

**Comment by ivanpopelyshev** [comment] 2017-07-29 11:39
setFromQuad accepts 4 points - vertices of quad you need, not 8 numbers. Also just for your knowledge, i dont use anchor yet, and container doesnt have it at all ;)

Please look at the code: https://github.com/pixijs/pixi-projection/blob/master/src/Projection2d.ts#L136

```
setFromQuad([{x:0, y:0}, {x:100, y:0}, {x:100, y:100}, {x:0 y:100}]);
```

Also, in your case its better to specify x axis, like in http://pixijs.github.io/examples/#/projection/basic.js , its the point where all lines parallel to X axis are merging.

```
container.proj.setXAxis({x:3000, y:height/2}, 1); //somewhere very far away
```

**Comment by ganzimaro** [comment] 2017-07-29 13:49
The plugin already works fine when transforming images, using either of the two methods.
As for containers, any attempt to transform it leads to this result (only the direction of inclination changes):
![72](https://user-images.githubusercontent.com/1789453/28745271-b5172e16-747d-11e7-9517-39a36ba423ab.png)

**Comment by ivanpopelyshev** [comment] 2017-07-29 14:18
Need to see the code, i have to debug it. Can you provide code that will work in pixi-examples? Or may be just share me the project in dropbox

**Comment by ivanpopelyshev** [comment] 2017-07-29 14:38
OK, I know what's wrong. Text!  Suppose you use some "sprite" that is old pixi class.

```js
sprite.calculateVertices = PIXI.projection.Sprite2d.calculateVertices;
sprite.calculateTrimmedVertices = PIXI.projection.Sprite2d.calculateTrimmedVertices;
sprite.proj = new PIXI.projeciton.Projection2d(sprite.transform);
```

I'm going to add special mixin function right now.

**Comment by ivanpopelyshev** [comment] 2017-07-29 14:54
OK, I've added "convertTo2d()" option to any element, and you can convert whole subtree!

```js
container.convertSubtreeTo2d();
```

**Comment by ganzimaro** [comment] 2017-07-29 15:17
Thank you for your quick work, I ran to check.

**Comment by ganzimaro** [comment] 2017-07-30 09:29
OK, actually this situation:
![73](https://user-images.githubusercontent.com/1789453/28752182-ea787138-7521-11e7-81df-a0862242651b.png)
I also wanted to clarify whether I can use the Sprint of the RPG Maker, or only PIXI.Sprite?
File link:
https://github.com/ganzimaro/HwTF/blob/master/www/js/plugins/LGS_Equip.js
The code used is in the "3D TEST" commented part.
In the game this: "New game-Esc-Inventory"

Character window is executed using "Bitmap.snap" and its subsequent transformation.

**Comment by Dairnon** [comment] 2017-07-30 10:02
The RPGMV sprite just wraps a PIXI.Sprite, so that should work no problem. However I do wanna say that you don't actually need an RPGSprite

If your worried about RPGMV bitmaps, remember that a bitmap just wraps a pixi,baseTexture.

something like new PIXI.Sprite(bitmap.baseTexture) should work (bitmap being the img you loaded with the ImageManager)

**Comment by ivanpopelyshev** [comment] 2017-07-30 10:22
I think the problem is that Rpgmaker sprites overriden renderWebGL thingy and are using simple "sprite" plugin instead of "sprite2d". Lets fix it.

```
Sprite.prototype._renderWebGL = function(renderer) {
    if (this.bitmap) {
        this.bitmap.touch();
    }
    if(this.bitmap && !this.bitmap.isReady()){
        return;
    }
    if (this.texture.frame.width > 0 && this.texture.frame.height > 0) {
        if (this._bitmap) {
            this._bitmap.checkDirty();
        }

        //copy of pixi-v4 internal code
        this.calculateVertices();
      if (this._isPicture & this.pluginName = 'sprite') {
            // use heavy renderer, which reduces artifacts and applies corrent blendMode,
            // but does not use multitexture optimization
            this._speedUpCustomBlendModes(renderer);
            renderer.setObjectRenderer(renderer.plugins.picture);
            renderer.plugins.picture.render(this);
        } else {
            // use renderer specified in pluginName
            renderer.setObjectRenderer(renderer.plugins[this.pluginName]);
            renderer.plugins.sprite.render(this.pluginName);
        }
    }
};
```

**Comment by ganzimaro** [comment] 2017-07-30 12:11
Sorry if I'm doing something wrong.
I connected this code, but result was the same.

**Comment by ivanpopelyshev** [comment] 2017-07-30 12:57
ok, i changed the code of the fix a bit, try now.

**Comment by ganzimaro** [comment] 2017-07-31 08:21
**Test report:**
Transformation works, but there are two nuances. If we use RPG Maker Sprite, then the result is like on the left image.

```
var sprite = new Sprite();
sprite.bitmap = new Bitmap(ScreenSize * 540, ScreenSize * 40);
sprite.bitmap.drawBitmapLGS("square", 540, 40, 0, 0, 0, 0, "#a3ffe0");
container.addChild(sprite);
```

If - PIXI.Sprite, then as on the right.

```
var bitmap = new Bitmap(ScreenSize * 540, ScreenSize * 40);
bitmap.drawBitmapLGS("square", 540, 40, 0, 0, 0, 0, "#a3ffe0");
var sprite = new PIXI.Sprite.fromImage(bitmap.canvas.toDataURL());
container.addChild(sprite);
```

The second nuance is that when we transform the figures, we get the chopped edges. In both cases the same.
![test](https://user-images.githubusercontent.com/1789453/28768702-4ef8008c-75e1-11e7-8626-54501341ad77.png)
If the first nuance can be missed, then second - no. Is there a way to remove, or at least minimize the effect.

**Comment by ivanpopelyshev** [comment] 2017-07-31 08:57
sprite.scaleMode = PIXI.SCALE_MODES.LINEAR

as for chopped edges, that's antialiasing problem. AA cant work inside filters and masks, and RMMV menus use that heavily. There's workaround: 

Suppose you use rectangular texture for that aqua-bar. Pad that texture with some transparent pixels.

**Comment by ganzimaro** [comment] 2017-07-31 12:26
Everything is working. Thank you for your help and your time.
I'm going to refine the automation of the transformation and continue to code the game.

**Comment by ivanpopelyshev** [comment] 2017-07-31 13:31
Ok, just reopen this one when you need help. I assigned new tag for it, so we can track all issues about projections.

**Closed by ivanpopelyshev** 2017-07-31 13:31 UTC
Labels: Plugin: 3d and projections, Type: Feature Request
