### ISSUE TITLE
CORS not working with PIXI.Sprite.fromImage

### ISSUE THREAD

**Issue by klinden** [pixijs/pixi.js#4043] opened 2017-05-19 14:00 UTC
When using PIXI.Sprite.fromImage to create a sprite from a remote URL (and then subsequently load it onto a stage and render the stage), the image(s) do not load properly if the cross origin parameter is set to true. 

Steps to reproduce
1. Create a Sprite using fromImage and setting crossOrigin to true. e.g. `var sprite = PIXI.Sprite.fromImage(url, true);`

2. Add the sprite to the stage and render the stage

3. The image does not load, the canvas is solid black, and Chrome lists the following warning: `[.Offscreen-For-WebGL-09C4DAE8]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.`

However, if I try to load the same image without specifying the crossOrigin parameter, e.g. `var sprite = PIXI.Sprite.fromImage(url);` and using the Chrome extension "Allow-Control-Allow-Origin: *" which simulates CORS always on, the same image is loaded correctly.

**Comment by englercj** [comment] 2017-05-19 15:00
Looks like this is because if you pass the variable manually it skips the cross origina auto-detection and doesn't do anything with the param:

https://github.com/pixijs/pixi.js/blob/e1cfd26673ad009e612e8e7b18d59b6846befb4b/src/core/textures/BaseTexture.js#L682-L685

If you leave it out, it auto-detects cross origin and works correctly. The fix would be to add the following block after that block:

```js
else if (crossorigin)
{
    image.crossOrigin = typeof crossorigin === 'string' ? crossorigin : 'anonymous';
}
```

and that should fix it.

**Comment by klinden** [comment] 2017-05-19 15:05
Thanks for the heads up. I'll try to see if I can get around to fixing it myself. As a side note (not sure if this needs to be a separate issue or not), but the auto detection does not work for two URLs on the same domain with different ports. For example, http://localhost:4200 and http://localhost:8080 are not technically  in the same origin, but the auto detection does not work for this case.

**Comment by englercj** [comment] 2017-05-19 17:44
Good catch, should probably fix both with this issue.

**Comment by ereesman** [comment] 2017-05-21 23:40
Hi there, I was able to reproduce the report by @klinden although I got a slightly different error message when experiencing the broken behavior. I implemented the fix suggested by @englercj and added a test. 

Cheers,
E

**Comment by englercj** [comment] 2017-05-22 03:35
Merged!

**Closed by englercj** 2017-05-22 03:35 UTC
Labels: Difficulty: Easy, Domain: API, Priority: Low, Status: Accepting PRs, Type: Bug, Version: v4.x
