### ISSUE TITLE
WebGL VideoTexture renders upside down / y flipped in Firefox 50

### ISSUE THREAD

**Issue by FabianElsmer** [pixijs/pixi.js#3577] opened 2017-01-12 16:09 UTC
Hey people,
I''m on Fedora 24, Firefox 50
and every WebGL VideoTexture renders upside down since I upgraded to the newest Firefox version
Replicable even on the PIXI Demo page:

https://pixijs.github.io/examples/#/basics/video.js

![screenshot from 2017-01-12 16-53-32](https://cloud.githubusercontent.com/assets/9722121/21897445/ddd60fbe-d8e9-11e6-84f8-b627cd6a505c.png)

**Comment by themoonrat** [comment] 2017-01-12 18:02
It's the correct way on my PC and on my laptop. Both on Windows.

**Comment by FlorianLudwig** [comment] 2017-01-13 09:19
@themoonrat I can reproduce this on three different computers.

Make sure you have Firefox 50.  It might be a Firefox bug as it only happens after newest changes in firefox but http://krpano.com/ios/bugs/ios8-webgl-video/ is not affected.  So what is pixi doing differently? 

Systems tested:
 * Desktop, Windows 10, NVIDIA GTX 650
 * Laptop, Windows 10, NVIDIA Quadro K1100M
 * Laptop, Fedora 25, Intel integated GPU (of an i7-7500U)
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1330672#c1 can reproduce it with an AMD card

**Comment by themoonrat** [comment] 2017-01-13 09:32
I tried on Firefox 50 and Firefox Developer Edition 52 on both. PC using Geforce 770 Ti, the laptop... not sure off hand, i believe it's a low end mobile Geforce

**Comment by FlorianLudwig** [comment] 2017-01-13 09:46
@themoonrat  are you sure pixi is using the webgl renderer?

**Comment by yoo2001818** [comment] 2017-01-18 09:19
I found out that this only happens if `gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, true)` is called. Also, I was able to reproduce this problem without using pixi.js, so I'm sure this is an browser issue.

To work around this, you can this line to `glTexture.premultiplyAlpha = false`. I'm not sure how this will affect transparent images, but since almost all videos don't have alpha channel, it could check whether if the source type is video or not.
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/TextureManager.js#L128

**Comment by FabianElsmer** [comment] 2017-01-18 10:52
@yoo2001818 Thank you so very much!

**Comment by IgorGamer** [comment] 2017-02-20 18:25
Could you help me to solve this problem?  I couldn't reproduce your solution this in pixi.min.js

`	function PlayGameVideo(lastVideo) {
		var texture = PIXI.Texture.fromVideo(lastVideo);
		videoSprite = new PIXI.Sprite(texture);

		texture.baseTexture.source.loop = true;

		videoSprite.width = 720;
		videoSprite.height = 480;
		videoSprite.anchor.set(0.5); 
	
		stage.addChild(videoSprite);

	        video.currentTime = 0;
		video.play();
	}`

**Comment by englercj** [comment] 2017-04-18 00:58
Closing this since it has been answered.

**Closed by englercj** 2017-04-18 00:58 UTC
Labels: Renderer: WebGL, Type: Browser Bug, Version: v4.x
