### ISSUE TITLE
Resolution not working correctly on chrome 39? 

### ISSUE THREAD

**Issue by mrjor** [pixijs/pixi.js#1962] opened 2015-07-08 08:37 UTC
Hi I am working on a project that user Pixi v3 with a lot of sprite animations. Everything is working fine but recently we received a screenshot from a user that doesn't get its resolution correct. It is displayed in a Macbook pro 15 inch 2 yrs old with chrome 39. 

http://gavoorsunwebgeel.nl/

<img width="1680" alt="screen shot 3" src="https://cloud.githubusercontent.com/assets/886538/8566195/ba72a682-255c-11e5-9ed2-02bd64104cb1.png">

I don't know why it is doing this and if this is a hardware ore software related issue.

Thanks!

**Comment by englercj** [comment] 2015-07-08 13:00
Have you tried to reproduce on retina devices? Does it work there?

Have you tried to downgrade Chrome to 39 and see what happens?

I can't think of the cause off the top of my head, just need to test all the factors you might think it is and see what happens.

**Comment by mrjor** [comment] 2015-07-08 13:16
Hi, 

Yes it works on other retina devices. Also downgraded Chrome to 39 on my IMac but it works fine.

**Comment by englercj** [comment] 2015-07-08 13:51
Have you ensured it works properly on both renderers under those conditions as well? Could be possible their hardware made them use a different renderer than you (assuming you use `autoDetectRenderer`).

**Comment by mrjor** [comment] 2015-07-08 14:12
I am actually using this if statement. 

 if (isWebGLSupported) return new PIXI.WebGLRenderer(width, height, options);
        return new PIXI.CanvasRenderer(width, height, options);

**Comment by englercj** [comment] 2015-07-08 14:33
Ok, my question in the same though. Have you ensured that under those conditions (retina device/chrome 39) it works the same on both renderers?

**Comment by mrjor** [comment] 2015-07-08 14:44
Yes thats correct. It works in both ways in 39 on my IMac. I will try to get some more details of this user.

**Comment by GoodBoyDigital** [comment] 2016-01-31 23:28
hello! Closing this for now. Let me know if this pops up again :+1:

**Closed by GoodBoyDigital** 2016-01-31 23:28 UTC
Labels: need-more-info
