### ISSUE TITLE
problem with render too slow in Mobile terminal

### ISSUE THREAD

**Issue by fengFanYong** [pixijs/pixi.js#2972] opened 2016-09-18 07:35 UTC
hi
I found that the render interval is too long,animate Refresh 1000 times as:
google : 18s;
Mobile terminal : 29;
And with the sprite number of Increased,animate Refresh time is longer.
code as below:

```
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>js test</title>
    <style>
        body {margin: 0;padding: 0;background-color: #000000;}
    </style>

    <script src="//cdn.bootcss.com/pixi.js/4.0.1/pixi.min.js"></script>

</head>

<body>
<script>
    var stage = new PIXI.Container();
    var render = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, {antialias: true},true);
    document.body.appendChild(render.view);

    for(var i=0;i<200;i++){
        bt = new PIXI.Sprite();
        bt.anchor.set(0.5);
        bt.x =150;
        bt.y = 200;
        bt.width = 140;
        bt.height = 344;

        gt = new PIXI.Graphics();
        gt.interactive = true;
        gt.beginFill(0x123123);
        gt.drawRect(0,0,1,1);
        gt.endFill();
        bt.addChild(gt);
        stage.addChild(bt);
    }

    var time = Date.now();
    requestAnimationFrame(update);
    var startTime = Date.now();
    var count = 0;
    var sum = 0;
    function update() {
        count ++;
        if(count == 1000){
            var endTime = Date.now();
            console.log("____ render interval:"+(endTime-startTime));
            startTime = Date.now();
            count = 0;
        }
        requestAnimationFrame(update);
        render.render(stage);
    }
</script>
</body>
</html>
```

thank!

**Comment by englercj** [comment] 2016-09-22 00:10
I think this is a dupe of #2892?

**Closed by englercj** 2016-09-22 00:10 UTC
