### ISSUE TITLE
Issue with getting container height during mouseup event

### ISSUE THREAD

**Issue by Spigo-Kevin** [pixijs/pixi.js#2975] opened 2016-09-19 09:28 UTC
We've run into a problem regarding getting the height of a button class we've created for our projects. What we've done is created a class that inherits from PIXI.Container, this class will then add a PIXI.Sprite to itself which is used for displaying the button itself. We then add an instance of PIXI.Text to the sprite, this displays the caption on the button.

We set the sprite to be interactive and bind "mouseover", "mouseout", "mousedown", and "mouseup" on the sprite in order for the button to change it's state. We also bind "click" where we fire any callbacks bound to the button.

Now here's the problem, when we let go of the mouse while the mouse is still over the button it triggers a "mouseout" event shortly followed by a new "mouseover" event, this leads to undesired behaviour of the button, for example, clicking the button fast then holding down the mouse can cause the button to be in it's "over" state rather than the "down" state.

The reason this happens is because we move the caption by a certain offset when the button is clicked, to do this we recalculate the vertical center of the button every time it is clicked, in the process of calculating the vertical center we use "this.height" on our button. Now I believe the problem has to do with the recalculation of bounds that happens in the getter for "height", since, if we get the height directly from one of the textures we assigned to the sprite the problem disappears.

Here's a JSFiddle showing the problem: https://jsfiddle.net/ejbkv8cy/
Looking at line 75 you'll find the method used when moving the caption. There's a line I've commented out, if you swap the line currently there with the one commented out you should see the button start working as desired.

**Comment by ivanpopelyshev** [comment] 2016-09-19 09:30
".height" calls getLocalBounds() which breaks up everything. Don't use it. 

@GoodBoyDigital I told you so.

**Comment by Spigo-Kevin** [comment] 2016-09-19 09:37
Yeah I switched to getting the height from the texture instead, at least for the time being.

**Comment by ivanpopelyshev** [comment] 2016-09-19 09:45
Yeah, texture works too.

**Comment by englercj** [comment] 2016-09-29 20:42
Duplicate of #2823

**Closed by englercj** 2016-09-29 20:42 UTC
Labels: Domain: API, Plugin: Bounds, Plugin: Interaction Manager, Priority: Medium, Resolution: Duplicate, Type: Bug
