### ISSUE TITLE
Problems rendering polygonal shapes in v5.3.0

### ISSUE THREAD

**Issue by Aiwha** [pixijs/pixi.js#6757] opened 2020-07-10 16:17 UTC
### Expected Behavior
I'm drawing a bunch of polygons using lineTo(), and the rendering has changed between v5.3.0 and v5.2.4 : 
Expected behavior (in v5.2.4):
![pixi530](https://user-images.githubusercontent.com/12586768/87174921-310ecf00-c2d8-11ea-9750-2efc91c83eef.png)
### Current Behavior
Behavior in v5.3.0:
![pixi524](https://user-images.githubusercontent.com/12586768/87174924-31a76580-c2d8-11ea-9e0e-44df2a0a5d76.png)
Looks like some wide angles of the stroke are being filled the same color as the stroke, and on the sides (where the points are really close to each other) long lines appear. 
Note that the two screenshots use the same lineStyle() values, and that the weird glitched lines on the side don't seem affected when changing the new miterLimit option in v5.3.0

### Possible Solution
My guess would be that this is linked to the addition of the join, cap and mitterLimit in 5.3.0.

- **`pixi.js` version**: 5.3.0

**Comment by bigtimebuddy** [comment] 2020-07-10 17:45
Duplicate of #6722

Will be fixed in 5.3.1 release, coming soon!

**Closed by bigtimebuddy** 2020-07-10 17:45 UTC
