### ISSUE TITLE
VertexArrayObjects and MultiTexture Batching on 'old' devices

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi.js#3558] opened 2017-01-08 22:01 UTC
Hey Pixi peeps,

I have noticed that there seems to be a few issues on old devices when using the above (which are enabled by default). 

Im thinking we could introduce a new prop to the settings / a render option called something like 'old'. Setting this prop to true would disable VAOs and set Max textures to 1. 

We could also set them to be that by default, but most modern devices really benefit from this stuff so I think its best to not to.

What do you think?

Cheers!

Mat

**Comment by themoonrat** [comment] 2017-01-08 22:17
Definitely. A couple of thoughts
1. Should we do some device detection ourselves for greatest compatibility out of the box? So if we know a Galaxy tab requires 'compatibility mode' we turn it on by default? Or always leave it down to the developer to choose?
2. Could this scale the other way? For example, I believe there were issues with highp with fragment shaders for some devices, but for some it'd be nicer to have it available? Could this flag go multiple ways? So -1 = compatibility, 0 = default, 1 = bleeding edge?

**Comment by staff0rd** [comment] 2017-01-08 22:33
Any examples or specific areas that these issues appear?  Could possibly help devs determining whether using the flag can be a solution for them.

**Comment by GoodBoyDigital** [comment] 2017-01-09 19:20
@staff0rd , this tends to be an issue than can pop up when rendering content on older generation devices. It manifests itself as crazy flickering / broken textures. I believe this is due to some old GPUs really struggle with if statements in shaders. Whilst others claim to support VBOs, but in reality do not.. 

@themoonrat I do like the idea of a compatibility mode. I think it could scale the other way too :)

**Comment by artsjedi** [comment] 2017-01-21 17:10
Is possible to disable disable VAOs in v4? how can I do it?

**Comment by artsjedi** [comment] 2017-01-21 17:18
Meybe... is there something that we could findout if the device will support the MultiTexture Batching. some gl flag or something?

**Comment by artsjedi** [comment] 2017-01-21 17:20
Is possible to disable disable VAOs in v4? how can I do it? Meybe... is there something that we could findout if the device will support the MultiTexture Batching. some gl flag or something?

@staff0rd  here is an example https://www.youtube.com/watch?v=t6wVYRm731I

**Comment by artsjedi** [comment] 2017-01-21 17:38
One important thing that i figure find out. 

I made some test with packing all textures in one big (really big) PNG. **this way the issue is gone.**
When I add more than one texture file, somehow the software swap the correct texture that it should render for each sprite.

For instance. some sprites was rendered with the incorrect  texture, in this case the bitmapfont image, and some sprites was renderer with the correct texture. And some texts, that should be renderer with bitmapfont image, was rendered with other textures images

**Comment by amrelhady** [comment] 2017-01-31 10:21
@artsjedi I think I am experiencing a similar issue. The issue happens when I load two spritesheets like this:
```
loader.add('sprite1.json')
          .add('sprite2.json')
          .load()
```

When I merged them into 1 spritesheet, it "works". FYI the issue I am seeing when loading them as two sheets is that textures from the first sheet are actually being used in place of those from the second one. It's as if they are using the same buffer or memory location.

**Comment by englercj** [comment] 2017-04-17 03:21
Closing since the new Legacy option has been added!

**Closed by englercj** 2017-04-17 03:21 UTC
Labels: Difficulty: Easy, Domain: API, Status: In Discussion, Type: Enhancement, Type: Question, Version: v4.x
