### ISSUE TITLE
[Android mobile chrome 58] pixi init options.antialias = true // has problem

### ISSUE THREAD

**Issue by shaoahs** [pixijs/pixi.js#4051] opened 2017-05-22 03:20 UTC
[Android mobile chrome 58] pixi init options.antialias = true // has problem
chrome 57 ,56, or older version  is normal !
#4015

**Comment by englercj** [comment] 2017-05-28 18:37
Can you elaborate please? What issue are you experiencing? Can you share a running example of this issue happening?

**Comment by PythonFanboy** [comment] 2017-05-30 07:33
It's probably Chrome bug reported here: http://crbug.com/696126

**Comment by shaoahs** [comment] 2017-06-09 01:14
use framework to manager canvas 
https://mithril.js.org/index.html
like class PIXI.Application 

like this 

> pixi component
```
import m from 'mithril';

let canvasStyle = {left: '0%', top: '0%', width: '100%', height: '100%'};
let baseStyle = {
  zIndex: 10,
  position: 'absolute',
  left: '0%',
  top: '0%',
  width: '100%',
  height: '100%'
};
let Component = {
  game: null,

  oninit (vnode) {
    let state = vnode.state;
    let attrs = vnode.attrs;
    let conf = vnode.attrs.config;
    let config = {
      useManager: conf.useManager,
      id: vnode.attrs.id || conf.id,
      width: conf.width || 1024,
      height: conf.height || 768,
      resolution: conf.resolution || 1,
      antialias: conf.antialias,
      transparent: conf.transparent,
    };

    state.config = config;
    state.style = attrs.style || baseStyle;

  },

  oncreate (vnode) {
    let state = vnode.state;
    let config = state.config;
    config.canvas = vnode.instance.children[0].dom;
    config.element = vnode.dom;

    let options = {
        view: config.canvas,
        resolution: screen.resolution,
        antialias: screen.antialias,
        transparent: screen.transparent
    };

    let renderer = PIXI.autoDetectRenderer(screen.width, screen.height, options);

    //--
    let stage = new PIXI.Container();
    render(stage);
  },

  onremove (/*vnode*/) {
    console.log('game onremove');

  },
  view (vnode) {
    let state = vnode.state;

    return m('.', {style: state.style},
      m('canvas', {style: canvasStyle})
    );
  }
};
export default Component;

```

> app
```
  let style = {zIndex: 10, position: 'absolute', left: '0%', top: '0%', width: '100%', height: '100%'};
  let app = {
    view () {
      return  m('.', {style: style},
        m(components.game.pixi, {
          config: null,
        })
      );
    }
  };
    m.mount(document.body, app);
```

**Comment by musikov** [comment] 2017-06-19 12:34
same issue here
https://github.com/pixijs/pixi.js/issues/4015

**Comment by englercj** [comment] 2017-06-19 17:33
Closing since this is a duplicate of #4015.

**Closed by englercj** 2017-06-19 17:33 UTC
Labels: Type: Browser Bug
