### ISSUE TITLE
Loading sprite sheet JSON with Typescript/Webpack

### ISSUE THREAD

**Issue by sandervspl** [pixijs/pixi.js#4029] opened 2017-05-15 16:56 UTC
Hi everyone,

I'm trying to load a JSON file from my project with PIXI but it's not working. I've tried multiple things but none seem to work.

```javascript
const planeSpriteSheet = require('../assets/spriteSheets/plane/plane.json');


PIXI.loader
  .add(planeSpriteSheet)
  .load(this.onAssetsLoad);
```
After compiling, this will be the error:
```
Uncaught Error: No url passed to add resource to loader.
    at Loader.add (webpack:///./~/resource-loader/lib/Loader.js?:323:19)
```

The JSON is loaded correctly when I check it with a `console.log(planeSpriteSheet)`.

This is my Webpack configuration
```javascript
const path = require('path');
const webpack = require('webpack');

module.exports = {
  devtool: 'source-map',

  entry: path.resolve(__dirname, '..', 'src/app.ts'),

  output: {
    path: path.resolve(__dirname, '..', 'public'),
    publicPath: '',
    filename: 'bundle.js'
  },

  resolve: {
    extensions: ['.ts', '.js', '.json'],
    alias: {
      assets: path.resolve(__dirname, '../src/assets/'),
      interfaces: path.resolve(__dirname, '../src/game/interfaces'),
      speed: path.resolve(__dirname, '../src/game/speed'),
      movement: path.resolve(__dirname, '../src/game/movement'),
    }
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin()
  ],

  module: {
    loaders: [
      {
        test: /\.ts$/,
        enforce: 'pre',
        loader: 'tslint-loader',
        options: {
          emitErrors: true,
          typeCheck: true,
        }
      },
      {
        test: /\.js?$/,
        loader: 'babel-loader',
        options: {
          presets: ['es2015', 'stage-0']
        },
        include: path.join(__dirname, 'src')
      },
      {
        test: /\.ts?$/,
        loader: 'ts-loader'
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.(gif|png|jpe?g|ttf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
        loader: 'file-loader'
      }
    ]
  }
};
```

**Comment by bigtimebuddy** [comment] 2017-05-15 19:13
You might want to check out the [Spritesheet](http://pixijs.download/release/docs/PIXI.Spritesheet.html) API. This allows you to create the spritesheet textures from the raw data, instead of going through the loader. You still need to manually load the image, however.  Something like this:

```js
const data = require('../assets/spriteSheets/plane/plane.json');
PIXI.loader
  .add('image', data.metadata.imageMetadata)
  .load((loader, resources) => {
     const sheet = new Spritesheet(resources.image.baseTexture, data);
     sheet.parse(() => {
        // done!
     });
});
```

**Comment by bigtimebuddy** [comment] 2017-05-15 19:15
Also, looks like a duplicate of #2906

**Comment by englercj** [comment] 2017-05-30 15:14
Closing this since it seems answered.

**Closed by englercj** 2017-05-30 15:14 UTC
Labels: Type: Question
