### ISSUE TITLE
Shall we provide textureWidth/textureHeight property in `Sprite.js` ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3483] opened 2016-12-19 06:26 UTC
Now , in my fork version , there are some codes in `_onTextureUpdate` of `Sprint.js` : 
```
    _onTextureUpdate()
    {
        this._textureID = -1;

        this.textureWidth = this._texture.orig.width;
        this.textureHeight = this._texture.orig.height;

        // so if _width is 0 then width was not set..
        if (this._width)
        {
            this.scale.x = sign(this.scale.x) * this._width / this.textureWidth;
        }

        if (this._height)
        {
            this.scale.y = sign(this.scale.y) * this._height / this.textureHeight;
        }
    }
```
the textureWidth/textureHeight is an easy way to access the texture's original size.
And I think  `sprite.textureWidth` is better than `sprite.texture.orig.width`.

But there is a problem puzzled me ：
 If users modify the  `sprite.texture.orig` directly , the textureWidth/textureHeight &   this.scale.x/ this.scale.y  would NOT auto updated , users have to call `_onTextureUpdate` manually.

So , I want to know that whether the PIXI allow/suggest users to  modify the  `sprite.texture.orig` directly ？

And whether we need a public method for  `updateTexture` manually ？ like this ：
```
updateTexture()
{
    this._onTextureUpdate();
}
```

**Comment by GoodBoyDigital** [comment] 2017-01-16 22:16
Hi @finscn! This is intended behaviour, I feel this issue is an edge case specific to your needs. 
Setting width / height is basically just a special way to modify the scale of an object. Closing for now. Thanks!

**Closed by GoodBoyDigital** 2017-01-16 22:16 UTC
Labels: Domain: API, Priority: Low, Type: Enhancement, Type: Question, Version: v4.x
