### ISSUE TITLE
BlurFilter is cause black screen with galaxy s8 or some mobile device

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi.js#4319] opened 2017-09-21 07:35 UTC
hi.  this issue is not happening on all of device.

galaxy s7 or s8 device is happened. 

i checked iphone 6 6plus,7 galaxy note3,  galaxy s7, s8

only s7 and s8 happend..

s8 is more complicate 

s7 is only problem with outline filter
but s8 is with blur or displacement ..

first time it is normal but repeat on/off and then blur or displacement cause black

i tested with pixi.filter.js 's demo(http://pixijs.github.io/pixi-filters/examples/)

**Comment by bigtimebuddy** [comment] 2017-09-21 09:59
Could you provide a screenshot?

**Comment by themoonrat** [comment] 2018-07-05 15:53
Closing as a believe this is a duplicate of https://github.com/pixijs/pixi.js/issues/4330 - and later browser versions have fixed the issue

**Closed by themoonrat** 2018-07-05 15:53 UTC
Labels: Plugin: Filters, Type: Browser Bug, Version: v4.x
