### ISSUE TITLE
baseTexure destroyed on a frame, can't find why

### ISSUE THREAD

**Issue by Inateno** [pixijs/pixi.js#1820] opened 2015-05-18 13:05 UTC
Hello,

I updated my engine with the latest version of PIXI and migration is ok except this point and I cannot find why this is happening, maybe it's the same problem than https://github.com/GoodBoyDigital/pixi.js/issues/1741 ?

I never call "destroy", I looked with a global search and this is only inside PIXI.

This is how I instantiate my sprite:
````javascript
  PIXI.Sprite.call( this, PIXI.utils.TextureCache[ frameId ] );
````
First time goes well, and if I reload the level later I got an error "cannot read hasLoaded of undefined".
I type "PIXI.utils.TextureCache[ "island-1" ]" in console and see "baseTexture = null".

I would like to fix this, after checking commits history there is tons of things changed.
Maybe you have an idea to locate approximately where this is coming from, and I will be able to investigate much more.

I'm trying to reproduce this bug on a smaller project.

**Comment by englercj** [comment] 2015-05-18 14:25
The only time a texture's baseTexture should be null is if it is destroyed, or set to null manually.

I can't think of any reason this would happen if you never call destroy. Hopefully you can reproduce with a focused test case so I can look into it.

**Comment by Inateno** [comment] 2015-05-18 14:31
Agree. What is strange is I didn't got this problem with 3.0.0-rc4.

**Comment by Inateno** [comment] 2015-05-18 18:48
Ok I found the origin.
I call "destroy" on my containers with true arguments because I push other container inside.

The problem is "true" argument is propagating inside all renderer (sprite, whatever) with "true", and when you call destroy with true on a renderer this destroy the texture.

`````javascript
  // destroy prototype on Container
  Container.prototype.destroy = function (destroyChildren)
  ..
    this.children[i].destroy(destroyChildren); // sending true to delete all children

  // destroy prototype on Sprite
  Sprite.prototype.destroy = function (destroyTexture, destroyBaseTexture) // getting true but this will act on texture not on children
````

So I'm guessing now, how can we destroy a container with all children inside without destroying all Textures ?

Should I wrote a middle-ware for doing my stuff (it's easy ofc) or should we must include this option inside PIXI ? (am I the only one using container this way ?)

If you don't think it's useful to look for an option inside PIXI just close this issue and I'll do a middle-ware :)

**Comment by JiDW** [comment] 2015-05-18 20:32
You can call removeChildren on the container, it will return the removed children. Then loop on them and call destroy without parameters.

**Comment by englercj** [comment] 2015-05-18 20:37
This happens because we break an OOP rule by making the overriden sprite destroy take different params than the parent (adding params is fine, but changing them makes this happen). IMO sprite destroy should take in `destroyChildren` as the first param, then its extra spritey stuff, but that is a breaking change we can't make :(

Instead, @JiDW's method will work for you.

**Comment by Inateno** [comment] 2015-05-18 21:05
There is a simple way to do this in my case but thanks @JiDW 

@englercj yeah, or maybe (this is nasty I assume, but will not change anything in "usage") add something like
````javascript
  if (children[i].texture )
    children[i].destroy(); // no params for things getting texture
  else
    // basic destroy call
````
There is few options to do this fix without changing destroy method on Renderer prototypes, this is surely the nastier but faster.
I can look on a better way to fix this properly.

**Comment by englercj** [comment] 2015-05-18 21:50
Yeah I've thought about doing that too, but I'm not the ducktype is sufficient. I'll keep thinking about this problem, thanks!

**Comment by Bobgy** [comment] 2015-06-12 09:52
I just met the same issue, it took me some time finding out why this happened and found it is already known.

Personally, I think it should be mentioned somewhere more accessible before it is resolved. (Would the documentation for PIXI.Container be a good place?)

Anyway, pixi.js is great for me! Thanks for all the work.

**Comment by GoodBoyDigital** [comment] 2016-02-04 09:21
closing for now as this seems sorted. thanks all :+1:

**Closed by GoodBoyDigital** 2016-02-04 09:21 UTC
Labels: enhancement

**Comment by Inateno** [comment] 2016-02-04 09:30
Glad to hear :)
