### ISSUE TITLE
Loader Progress event is incorrect when loading Sprite Sheets

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi.js#3095] opened 2016-10-11 20:26 UTC
Seems that the loader is currently displaying the incorrect progress when loading sprite sheets.
Loading 3 sprite sheets reports progress as going up to 150%. I have attached the example I have been testing with:

[loaderissue.zip](https://github.com/pixijs/pixi.js/files/522889/loaderissue.zip)

Not sure if this is loader of pixi related!

**Comment by englercj** [comment] 2016-10-11 20:43
Duplicate of #2876, this is a known issue in the resource-loader.

https://github.com/pixijs/pixi.js/issues/2876#issuecomment-245467084

I'm in-progress rewritting for v2 that should solve this issue.

**Closed** 2016-10-11 20:43 UTC
Labels: Plugin: Loader, Priority: Critical, Resolution: Duplicate, Type: Bug, Version: v4.x
