### ISSUE TITLE
MESH example doesn't working

### ISSUE THREAD

**Issue by andrew-vogulkin** [pixijs/pixi.js#5018] opened 2018-07-12 06:30 UTC
Your issue may already be reported! Please search [existing issues](../) before creating one.

![image](https://user-images.githubusercontent.com/7150648/42616166-e9dfbdf8-85b5-11e8-812a-0d0562eed527.png)

pixijs.io/:6 Uncaught TypeError: PIXI.Geometry is not a constructor

### Environment
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
mac OS  High Sierra 10.13.5

- `pixi.js` version: _e.g. 4.7.1_
- Browser: _e.g. Chrome 67_
- Device: _e.g. Desktop_

**Comment by ivanpopelyshev** [comment] 2018-07-12 08:36
There's strange line on this screenshot. "Please switch to `next` version to see this demo".

**Comment by andrew-vogulkin** [comment] 2018-07-12 14:42
i try to see example on the official site
![image](https://user-images.githubusercontent.com/7150648/42640428-f5020f52-85fa-11e8-8654-8f047a2577ca.png)

**Comment by bigtimebuddy** [comment] 2018-07-12 15:27
Duplicate of #4996 #4807 #4795

**Closed by bigtimebuddy** 2018-07-12 15:27 UTC
