### ISSUE TITLE
prepare.upload plugin does not work if only texture is changed

### ISSUE THREAD

**Issue by krompir2** [pixijs/pixi.js#4076] opened 2017-05-31 19:43 UTC
I am trying to replace a texture atlas of the animated sprite with another one, and play it. 
On every click I first fetch the texture atlas image from server. Than I make periodic checks if there is any animation  still running. Once there is no animation running, I replace animatedSprite.textures with the new on and upload that tetxure atlas to the gpu. After it is uploaded, I set canRunNext to true, signaling, that everything is uploaded and ready to go.

 I am using the following code to prepare new texture atlas on each click. 

 
It seems that prepare.upload does not work everytime! In fact, it only uploads texture every second time. I've put timers into the code, and I can observer that when the prepare.upload uploads to gpu, time difference (variable diff) is 200ms, but when it does not, time difference is just 60ms. Based on that I conclude that prepare.upload didn't upload the textures in some occasions. So when I click on animation trigger, there is a time delay because pixi cant run animations smoothly if they aren't uploaded to gpu first. 

What could I do to fix that? I've got over 1000 lines of code and I posted just the relevant stuff. Basically I need to just replace the texture atlas once the animations are over and upload the new one to gpu, so that ti can run the next time animation is triggered. 

CODE:

```
function setupNextSprite(){
            var newLoader = new PIXI.loaders.Loader()
            .add('nextSprite', 'pathToSprite.png')
            .load(function (loader, resources){
                start = +new Date();
                var interval = setInterval(function(){
                    if (!isAnimating){// animation stopped, you can upload files to gpu without making everything freeze
                        clearInterval(interval);
                            nextSprite.textures = setupFrames(resources["nextSprite"].texture.baseTexture);
                            app.renderer.plugins.prepare.upload(nextSprite, function(){
                                console.log("updoaded now");
                                canRunNext = true;
                                newLoader.reset();
                                end = +new Date();
                                var diff = end - start;
                                console.log(diff);
                            });
                    }
                },50);
            });
}


// event trigger code
nextSprite.gotoAndPlay(0);
canRunNext = false;
isAnimating = true;
setupNextSprite();
setTimeout(function(){
isAnimating= false;},timeOfAnimation);
```

**Comment by themoonrat** [comment] 2018-07-15 09:44
Closing as appears to be duplicate of https://github.com/pixijs/pixi.js/issues/4081

**Closed by themoonrat** 2018-07-15 09:44 UTC
Labels: Domain: API, Plugin: Prepare, Version: v4.x
