### ISSUE TITLE
Chrome for Android not drawing texture when loaded from IndexedDB

### ISSUE THREAD

**Issue by agale** [pixijs/pixi.js#2223] opened 2015-12-05 06:16 UTC
Hello,

It turns out Chrome for Android sets videoWidth/videoHeight to 0 for videos loaded from IndexedDB. Here's the test case: https://vidolio.com/bug. I added the following as a workaround until it's fixed:
VideoBaseTexture.prototype._onCanPlay = function ()
{
...
        this.width = this.source.videoWidth || this.source.width;
        this.height = this.source.videoHeight || this.source.height;
...
};

Thanks,
Andrew

**Comment by agale** [comment] 2015-12-05 06:43
Almost goes without saying but same thing happens in Opera for Android since it shares the Blink engine.

**Comment by englercj** [comment] 2015-12-09 15:45
Is this a Blink bug, or intended behavior that we just don't support yet?

**Comment by agale** [comment] 2015-12-13 17:59
This is a blink bug but thought I'd add the workaround I'm using until they fix it. 
The original ticket is https://code.google.com/p/chromium/issues/detail?id=562732 which got merged into https://code.google.com/p/chromium/issues/detail?id=504773.

**Comment by englercj** [comment] 2015-12-13 20:50
Cool, thanks for the information and the reseach @agale its very helpful!

**Comment by GoodBoyDigital** [comment] 2016-02-04 08:52
closing for now as it seems like a blink issue rather than a pixi one. thanks all :+1:

**Closed by GoodBoyDigital** 2016-02-04 08:52 UTC
