### ISSUE TITLE
Is that possible to use PIXI.js with Node.js?

### ISSUE THREAD

**Issue by ProgrammingLife** [pixijs/pixi.js#6778] opened 2020-07-26 22:26 UTC
I've installed pixi.js:
```
npm install pixi.js @types/pixi.js
```

My test script is:
```
import * as PIXI from "pixi.js";
const renderer = new PIXI.Renderer({ width: 500, height: 300 });
```

After `tsc` I get following error:
```
» tsc
../../node_modules/pixi.js/pixi.js.d.ts:4925:68 - error TS1016: A required parameter cannot follow an optional parameter.

4925             calculateProjection(destinationFrame?: PIXI.Rectangle, sourceFrame: PIXI.Rectangle, resolution: number, root: boolean): void;
                                                                        ~~~~~~~~~~~

Found 1 error.
```
What do I do wrong?

**Comment by bigtimebuddy** [comment] 2020-07-26 22:30
This is a TypeScript error (duplicate of #6774).

Also, it's currently not possible to run PixiJS in Node-only environments (browsers only). There are shims that users created (https://github.com/Prozi/pixi-shim) which try to hack Pixi into running Node.

Closing this because duplicate.

**Closed by bigtimebuddy** 2020-07-26 22:30 UTC

**Comment by ProgrammingLife** [comment] 2020-07-26 22:44
Are there any plans for bringing it node.js support for server rendering?

**Comment by bigtimebuddy** [comment] 2020-07-26 23:41
Yes, in fact there is!

https://github.com/pixijs/pixi.js/projects/12#card-41866013

We are waiting for a hero to come along and help us with this task, but we have a rough plan for it.
