### ISSUE TITLE
Graphics mask with intersection problem

### ISSUE THREAD

**Issue by elfrog** [pixijs/pixi.js#3283] opened 2016-11-14 06:02 UTC
After I upgraded the PixiJS version 3 to 4, masking with Graphics object do not mask its intersected area.

PIXI VERSION 3: [https://jsfiddle.net/elfrog/oozrecjn](https://jsfiddle.net/elfrog/oozrecjn)
PIXI VERSION 4: [https://jsfiddle.net/elfrog/n2mat7kj](https://jsfiddle.net/elfrog/n2mat7kj)

Is it an intended change? or I missed something...

**Comment by elfrog** [comment] 2016-11-14 07:27
And it also has a very different result on canvas renderer.

[https://jsfiddle.net/elfrog/n2mat7kj/1](https://jsfiddle.net/elfrog/n2mat7kj/1)

**Comment by staff0rd** [comment] 2016-12-03 12:58
Hi @elfrog, thanks for these examples of the error, this is a duplicate of #2877 so I've moved them over there.  I also merged your two canvas/webgl [into one](https://codepen.io/staff0rd/pen/oYEWZJ?editors=0010).  Thanks for this report!

**Closed by staff0rd** 2016-12-03 12:58 UTC
Labels: Domain: API, Plugin: Graphics, Type: Bug, Version: v4.x
