### ISSUE TITLE
How to build current dev?

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi.js#3033] opened 2016-09-29 06:58 UTC
Hey all,

How do you build the current DEV version? (on windows)

I've pulled the latest version and have done an **npm install**   and then **npm run build** ,  but it gives me 27305 times the following error:
 error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

and no built js file.

**Comment by themoonrat** [comment] 2016-09-29 07:01
@englercj this was what i mentioned yesterday, looks like any windows user will suffer the issue without a git reconfigure.

**Comment by themoonrat** [comment] 2016-09-29 07:10
@whizzkid until that's answered, for now your can either use the latest built pixi directly, guide for that @ https://github.com/pixijs/pixi.js/wiki/FAQs#where-can-i-get-a-build 
Or to build locally, open up the package.json , look for the lint npm declaration, and change it's contents to something like 'npm -v'
This stops it performing, and thus failing, the lint process before pixi is actually built

**Comment by englercj** [comment] 2016-09-29 14:35
The problem is that when you installed git, you told it to checkout files with windows line endings. So, when you clones pixi it changed all the line endings to CRLF. Then, when you tried to build our linter complains because we don't allow CRLF in the lib.

You should be able to fix this by choosing the "Checkout as-is, commit as-is" option when installing git for windows; or by running the following command post-install:

```
git config --global core.autocrlf false
```

I will just go ahead and change the linter though since it seems multiple people will have this issue. But if I get CRLF endings in my lib...I'm going to be so mad...

**Comment by themoonrat** [comment] 2016-09-29 15:43
Since I use source tree, which uses an imbeded git, I had a look to see what they were doing, and according to them they say
"Windows machines convert CRLF to LF when committing and LF to CRLF when checking out"
Thus nothing commit would be the wrong line endings, but whilst on a Windows PC it would fail the linting.

Would adding a .gitattributes file help perhaps?

**Comment by englercj** [comment] 2016-09-29 16:01
Added one, would you mind doing a fresh checkout without having `core.autocrlf` set to false and see if that works?

**Comment by themoonrat** [comment] 2016-09-29 16:08
Yep, that works

**Comment by themoonrat** [comment] 2016-09-29 16:09
Could maybe pinch a relevant preset one from https://github.com/alexkaratarakis/gitattributes to cover all filetypes we may commit

**Comment by englercj** [comment] 2016-09-29 17:05
Cool, going to close this for now.

@whizzkid If you try cloning again, it should work for you now (in dev branch). Sorry about that!

@themoonrat I'll take a look and improve ours as necessary, thanks!

**Closed by englercj** 2016-09-29 17:05 UTC
Labels: Domain: Tooling, Type: Question, Version: v4.x
