### ISSUE TITLE
Rope with alpha overlaps with itself

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi.js#2383] opened 2016-03-09 09:59 UTC
Hi - I'm running into a problem were I want to use a semi transparent image for a rope, but unfortunately where it overlaps itself you get a doubling up of the image which looks bad. I was hoping to improve this by using SCREEN blendMode and giving the image a black background rather than transparent but this provides the same issue. Also the same thing happens where the alpha is set, rather than the whole rope which is a bit unexpected. 

Is there any way around this ?  I'm trying to make a trail (a bit like SwiftKey/Swype, but fading out).

Thanks!

J

**Comment by andrewstart** [comment] 2016-03-18 13:06
Trails are often done with particle systems, although they may be rougher on performance than a rope. (Blatant self advertising) You could try using [PixiParticles](https://github.com/CloudKidStudio/PixiParticles) for a particle based trail.

**Comment by weepy** [comment] 2016-03-18 13:31
Yes love PixiParticles !

I did implement with a particle system which results in a nice looking
trail. Only difficulty is when the particles get too far apart and it looks
less continuous.

I was wondering about if it was possible to apply some kind of unsharp mask
that would cut off the opacity ? So then you could have larger partcles
with a blurry edge, but the filter would cut that down.  Not sure if this
is possible or not with filters as am not very experienced with them.

**Comment by andrewstart** [comment] 2016-03-18 22:51
I would imagine that you could make a small filter that acts similarly to the ColorStepFilter, but just for alpha - set alpha to 0 if below a certain value, and leave it alone otherwise.

**Comment by weepy** [comment] 2016-03-18 22:57
Nice! - and that would on a container ?

**Comment by andrewstart** [comment] 2016-03-18 22:59
Yes, although I believe it would be applied to each individual child as they are drawn, not the container as a whole.

**Comment by weepy** [comment] 2016-03-19 12:36
Ah is see. Guess that wouldn't work then ! Bummer !

**Comment by GoodBoyDigital** [comment] 2016-05-22 21:28
closing for now as this is intended behaviour. For what you are looking to achieve @andrewstart is spot on, a simple alpha filter applied to rope should do the trick!

**Closed by GoodBoyDigital** 2016-05-22 21:28 UTC

**Comment by weepy** [comment] 2016-05-22 21:31
Sorry @GoodBoyDigital --- He said "it would be applied to each individual child as they are drawn, not the container as a whole."  --- which would mean we would end up with the same situation  ? Or am I missing something ?

**Comment by GoodBoyDigital** [comment] 2016-05-22 21:52
you could apply the filter directly to rope or a container.
