### ISSUE TITLE
Missing Application plugins & Graphics' lineStyle types

### ISSUE THREAD

**Issue by tomasfreres** [pixijs/pixi.js#7141] opened 2021-01-12 15:06 UTC
I just updated to PixiJS v6 RC and wanted to check if the updated types in v6 broke our Angular project and I get this errors that certain attributes don't exist anymore on certain types. If I check the v6 docs, the attributes are still there and not deprecated. Then I saw, that the pixi.js.d.ts is missing from node_modules/pixijs and maybe that confuses the typescript compiler.

I get this error from VS Code:

`"Unable to open 'pixi.js.d.ts': Unable to read file '/Users/toms/Coding/WaveModeler/node_modules/pixi.js/pixi.js.d.ts' (Error: Unable to resolve non-existing file '/Users/toms/Coding/WaveModeler/node_modules/pixi.js/pixi.js.d.ts')."`

And a lot of compilation errors like this:
`ERROR in src/app/main/processTabContent/editor/editor.component.ts:102:18 - error TS2339: Property 'loader' does not exist on type 'Application'.
this.pixiApp.loader.load(() => this.pixiApp.renderer.render(this.pixiApp.stage));`

### Environment

- **`pixi.js` version**: 6.0.0-rc
- **OS & Version**: macOS 11.1 Big Sur
- **Angular Version**: Angular 10
- **Typescript Version**: 3.9.7

**Comment by bigtimebuddy** [comment] 2021-01-12 15:17
Thanks for reporting.

Do you have a reproduction of these errors? That would be helpful to verifying.

The first error doesn't make sense to me because we removed the **pixi.js.d.ts** file. Are you sure that isn't referenced somewhere in your project? The new type file should be in **node_mdoules/pixi.js/index.d.ts**.

As for the missing `loader` on Application, should be pretty straightforward. Can you describe any other missing properties you're seeing or is it just `loader`? Or again if you could get us a repo that reproduces this that's the most helpful.

**Comment by tomasfreres** [comment] 2021-01-12 15:58
@bigtimebuddy I'll try to make an StackBlitz example :) 

In the meantime: Those aren't the only errors. Here are a few more. I guess all connected to the error with the wrong *.d.ts

`src/app/main/toolbar/export/StageExporter.ts:46:42 - error TS2339: Property 'extract' does not exist on type 'Renderer | AbstractRenderer'. Property 'extract' does not exist on type 'AbstractRenderer'.
const dataURL = pixiApp.renderer.extract.canvas(stage).toDataURL();`

`src/app/main/toolbar/export/StageExporter.ts:81:25 - error TS2339: Property 'ticker' does not exist on type 'Application'.
pixiApp.ticker.remove(exportFunc);`

`src/shapes/flowObjectShapes/activity/ActivityShape.ts:69:47 - error TS2554: Expected 0-1 arguments, but got 4.
this.lineStyle(ActivityStyle.borderWidth, ActivityStyle.borderColor, 1, 0.5);`

**Comment by bigtimebuddy** [comment] 2021-01-12 16:14
The extract one has been fixed already (unreleased). Application ticker will get fixed with loader (working on that now).

Will look into lineStyle issue. I thought that was deprecated in favor of an single object. Hmm, will take a look.

**Comment by bigtimebuddy** [comment] 2021-01-12 17:57
@tomasfreres I think I hit all of these issues. Can you please confirm about the pixi.js.d.ts error? I'm not seeing how that's possible. A reproduction would help.

**Closed** 2021-01-13 20:37 UTC
