### ISSUE TITLE
Sprite batching causes GC pauses

### ISSUE THREAD

**Issue by davedx** [pixijs/pixi.js#1926] opened 2015-06-27 15:27 UTC
Hey guys,

We saw some behaviour yesterday when working with sprite batching that led us to believe the flush() was causing GC cycles due to things being allocated/thrown away again. After some hunting in the source I found the following line:

https://github.com/GoodBoyDigital/pixi.js/blob/07e4e26f8fd404524a7ebaa73c210de3d8f2cf25/src/core/sprites/webgl/SpriteRenderer.js#L342

Here you see that we do a subarray on the vertex float data, send the result to the GPU, then throw it away again.

I removed this line to make it send all of the data every time. It seems like rendering still works fine, I think it just means we're sending a bit more data to the GPU, but we prevent GC pauses that can interfere with smooth animation. (Especially on our slow set top boxes where a GC every 15 seconds causes a 150-200ms freeze D:)

I think it might be possible to make the sprite batch just dynamically resize the float array *when needed* instead of every frame (I had "downsizing" working but not "upsizing") -- maybe this is the optimum? Game devs learn pretty early on that you should try to avoid constantly making/removing game objects from a scene, so the resizing should not happen often. For us, the temp fix of just removing the subarray is working nicely.

Any thoughts on this?

**Comment by englercj** [comment] 2015-06-27 23:57
Do you have an example app the reproduces this behavior?

**Comment by davedx** [comment] 2015-06-30 06:21
The app we're working on is closed source. I'll try and put together something that reproduces the behaviour.

**Comment by davedx** [comment] 2015-07-01 07:45
Here's a demo repo: https://github.com/davedx/pixi_gc_demo

The code I patched is: https://github.com/davedx/pixi_gc_demo/blob/master/pixi.js#L17496

There's a screenshot of a sawtooth memory timeline in that repo too: https://raw.githubusercontent.com/davedx/pixi_gc_demo/master/pixi3.png

The weird thing is, if I remove the subarray and run it on our device (a set top box), we see almost no GC cycles if the app is idle (rendering every frame, no animations). But in Chrome on Win 8, I actually still see the memory sawtooth whether I have the subarray or not.

Any insights into this?

**Comment by englercj** [comment] 2015-07-07 16:31
Looking to implement a method like this:

https://github.com/GoodBoyDigital/pixi.js/pull/1939#issuecomment-118461829

I think this will work well to help solve this issue as well.

**Comment by bchevalier** [comment] 2015-07-22 06:15
I was wondering if that behaviour was consistant across all the browsers or if this was only happening on chrome?

**Comment by bchevalier** [comment] 2015-09-04 03:39
Hello pixipeople, looks like chrome has improved their garbage collector:
http://v8project.blogspot.ru/2015/08/v8-release-46.html

See section "Reduce the Jank", there seems to be a lot of improvements regarding garbage collection and typed arrays, there is also a video to demonstrate the improvements. Seem a good news for pixi in general and I'm pretty sure it fixes this issue (at least when chrome 46 is released).

**Comment by davedx** [comment] 2015-09-25 11:52
Not sure what the plan is for this? We still prefer a fixed batch size and not calling .subarray, but I think that would probably make Pixi too inflexible for other use cases...

**Comment by englercj** [comment] 2015-09-27 00:44
There have been a couple of improvements to the particle container in recent dev code that allow you to specify the sizing of your container which should remove the need for the dynamic-ness.

(See: #1990)

Can you try rebuilding from the dev branch, and see if those features added from #1990 solve your case?

**Comment by GoodBoyDigital** [comment] 2016-02-04 09:10
@davedx this has been addressed in the v4.0.0 branch of pixi. no more subarray :+1:

**Closed by GoodBoyDigital** 2016-02-04 09:10 UTC
Labels: enhancement, WebGL
