### ISSUE TITLE
Slow rendering with PIXI.Text on iPad

### ISSUE THREAD

**Issue by jashson** [pixijs/pixi.js#6326] opened 2020-01-13 17:54 UTC
First - this problem only occurs on my iPad Pro (iPadOS 13) and a tiny bit on my desktop Safari. The app runs with 60 fps on my iPhone 7 with iOS 13 or in latest Chrome.

### Issue
Adding 10 - 100+ PIXI.Text objects (with 20 to 30 chars each) to the stage and you will notice that the frames per seconds starts to drop more and more. Even on only having 10 to 20 text objects, the frames drops below 60fps on iPadOS 13

### Possible Solution
So far I didn’t found a quick solution, but i played around with different renderer-settings. Set antialias to false didn't make any difference. But when set renderer.resolution to a really high value like 9 or 10, the frames per seconds starts to increase remarkably. It almost hits 60fps. But this makes no sense at all, does it?

### Environment
- **`pixi.js` version**: _e.g. 5.2.0_
- **Browser & Version**: Safari iPadOS 13

**Comment by bigtimebuddy** [comment] 2020-01-13 18:22
Text is notoriously slow, _especially_ if it is updated constantly. 

The best optimization if you're using lots of Text, is to convert to using [BitmapText](https://pixijs.io/examples/#/text/bitmap-text.js) instead. BitmapText is not rendered using canvas and is instead rendered with sprites. It's much faster. The downside is that if you need Korean, Japanese or Chinese language or need multiple sizes, it's a poor choice because you need to pre-render all your characters.

**Comment by jashson** [comment] 2020-01-14 11:58
I did some more investigation to this. It is primarily a problem with canvas elements itself.

Using this lines of code to add some sprites to the stage, the frame rate on the iPad drops dramatically (still only at the iPad, iPhone runs perfectly fine):

```javascript
for (let i = 0; i < 100; i++) {
   let canvas = document.createElement("canvas");
   let sprite = PIXI.Sprite.from(canvas);
   pixi.stage.addChild(sprite);
}
```

Even try to get the using the image-data from the canvas to not pass a canvas itself, doesn't make anything better.

**Comment by jashson** [comment] 2020-01-14 12:08
It is not the canvas itself, but just using a static image data string results into the same situation. 

```javascript
for (let i = 0; i < 100; i++) {
   let staticImageData = "data:image/png;base64,iVBORw0......";
   let sprite = PIXI.Sprite.from(staticImageData);
   this.addChild(sprite);
}
```

**Comment by bigtimebuddy** [comment] 2020-01-14 13:04
You are trying to allocate a lot of memory for each canvas (even if blank).and then uploading to the GPU is going to be a major hiccup—this is what Text is doing, basically. Try spreading the effort across multiple frames. Also, only create enough elements for the things visible on screen and reuse instead of recreating.

**Comment by ivanpopelyshev** [comment] 2020-01-14 15:14
> ```js
> for (let i = 0; i < 100; i++) {
>    let staticImageData = "data:image/png;base64,iVBORw0......";
>    let sprite = PIXI.Sprite.from(staticImageData);
>    this.addChild(sprite);
> }
> ```

If its the same staticImageData it shouldn't be slow. If it varies, well, it spawns an Image

**Comment by eXponenta** [comment] 2020-01-15 08:21
100+ textures call 100/32 ~ 4 or more drawElements,  for iPad (with retina) it slow when textures to big.

Then Text re-uploads every change - very slow operation.

Use BitmapText or pixi-msdf for this, how @bigtimebuddy writes.

**Comment by jashson** [comment] 2020-01-15 09:08
Thanks for your help so far. I'm aware of changing Text is an expensive operation. In my case i only create it once and it doesn't change after that. I just have the feeling, that this is only related with iPadOS. As I initial wrote, the frame rate goes up, when increasing `renderer.resolution` to 8 to 10.

**Comment by ivanpopelyshev** [comment] 2020-01-15 09:45
> But when set renderer.resolution to a really high value like 9 or 10, the frames per seconds starts to increase remarkably

do you call `renderer.resize` after that?

**Comment by jashson** [comment] 2020-01-15 09:49
> > But when set renderer.resolution to a really high value like 9 or 10, the frames per seconds starts to increase remarkably
> 
> do you call `renderer.resize` after that?

Yes. I set the `resolution` via `PIXI.Application({resolution: ...})`. After that I call `renderer.resize`.

**Comment by ivanpopelyshev** [comment] 2020-01-15 09:56
Max backbuffer size is 4096. If `width * resolution` exceeds it, part of screen (at the right and bottom) is not rendered , and that's where you have a number of texts.

**Comment by eXponenta** [comment] 2020-01-15 18:59
@jashson can you share link to your project, i test it on my ipad 2018 with ios 13.3.

**Comment by jashson** [comment] 2020-01-16 11:20
> @jashson can you share link to your project, i can test it on my ipad 2018 with ios 13.3.?

Of course. here it is: https://matthiasschulz.com/showroom/playground/pixi-text-ipadpro/

Its very interesting, because the framerate drops only when circles AND text are visible at once. If only text OR circles are visible the app runs as it should. You can play around with some settings (dat.gui at top right) and you can have a look to the index.html itself, which contains all code used by this example.

**Comment by ivanpopelyshev** [comment] 2020-01-16 11:31
> Its very interesting, because the framerate drops only when circles AND text are visible at once. 

Circles of more than 100 vertices -> batch is broken. In this case number of drawCalls grows. You can check it with @eXponenta tool https://github.com/eXponenta/gstatsjs , it overrides `drawElements` of webgl contexts and counts it calls.

I'm not saying that draw-calls are everything but big number of those commands is bad. Maybe adjusting `PIXI.GraphicsGeometry.BATCHABLE_SIZE` to a number that is bigger than your circles vertex number can help ( https://github.com/pixijs/pixi.js/blob/b437b1759bde232f0fcdaf89127791d6b1d4329a/packages/graphics/src/GraphicsGeometry.js#L1073 ) 

How to calculate that number ?  Its somewhere in `graphics.geometry.points` after graphics is actually drawn. You can force it with `updateBatches` call ( https://github.com/pixijs/pixi.js/blob/b437b1759bde232f0fcdaf89127791d6b1d4329a/packages/graphics/src/GraphicsGeometry.js#L407 ) . Its different for different circle size and is based on calculations from here : ( https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/utils/buildCircle.js#L45 )

**Comment by ivanpopelyshev** [comment] 2020-01-16 12:43
```
graphics.geometry.updateBatches();
if (PIXI.GraphicsGeometry.BATCHABLE_SIZE < graphics.geometry['points'].length) {
    PIXI.GraphicsGeometry.BATCHABLE_SIZE = graphics.geometry['points'].length;
}
``` 

> Because i'm not that into WebGL programming, the question is, if there is or could be something bad with that code for production use?

Sorry, there is a limit that I can explain. Its all about balance. If you have a huge pixi5-svg object and try that trick on it, it might have consequences ;)

If you have only circles, and you apply trick on ALL circles, its the same as `PIXI.GraphicsGeometry.BATCHABLE_SIZE = 1000` or maybe `10000`.

**Comment by mmagik** [comment] 2020-01-19 15:01
Also you can implement msdf text generation in pixi, that`s works good and performant:
See how it works on threejs and do it in pixi meshes
https://tympanus.net/codrops/2019/10/10/create-text-in-three-js-with-three-bmfont-text/

**Comment by politan8** [comment] 2020-01-29 18:39
We are experiencing the same issue with performance. It appeared to be that 13 Safari on iPad loads _desktop_ version of website by default (unlike earlier version os iPadOS), Probably this set pixi to desktop mode and somehow it is not optimised for iPad. 
If we force browser to "Request Mobile Website" then the fps looks way better in our case (like it was before 13 safari).
@jashson could you try out to force mobile in safari?
@ivanpopelyshev is there separation to mobile/desktop modes inside pixi which might fail due to incorrect platform detection in ios13? 
I was trying to override 
`PIXI.utils.isMobile.apple.tablet = true;
PIXI.utils.isMobile.apple.device = true;`
before creating pixi application but obviously this didn't do the trick.

### **Environment**
pixi.js version: e.g. 5.2.1
Browser & Version: Safari iPadOS 13

**Comment by jashson** [comment] 2020-01-29 18:54
@politan8 Your are right. When I request the mobile site (via "AA" in the address bar of Safari) from my iPad Pro, the frame rate goes up to 60 fps. I tested it with my example I posted some days ago: https://matthiasschulz.com/showroom/playground/pixi-text-ipadpro/)

**Comment by themoonrat** [comment] 2020-01-29 19:12
This is some good sleuthing! There are a couple of places that use isMobile to go down different paths. 
The problem is, detection of iPads in this mode is rather hacky, Apple does everything in its power to stop you detecting it's an iPad. I've personally written a custom check for 'if it says it's a Mac but it has a touch screen and has narrow screen dimensions, then act like it's an iPad instead'

So first thing we need to do is find out what paths are being taken that make it slow, see if they're still needed. If they are, then we can help make iPad detection better. I can look at these tomorrow.

**Comment by politan8** [comment] 2020-01-29 19:44
adapting the ipad detection also took me a while and will cost us many server redeploys which is far from being done.
Keep us updated, you're doing a great stuff!

**Comment by themoonrat** [comment] 2020-01-29 21:11
Ok, here are some builds I'd like you to try out @politan8  and @jashson 

http://moonrat.co.uk/javascript/allow-max-textures-false.js
http://moonrat.co.uk/javascript/allow-max-textures-true.js
http://moonrat.co.uk/javascript/can-upload-same-buffer-false.js
http://moonrat.co.uk/javascript/can-upload-same-buffer-true.js
http://moonrat.co.uk/javascript/prefer-env-webgl1.js
http://moonrat.co.uk/javascript/prefer-env-webgl2.js

These all turn on and off various paths decided by the isMobile lib.
I bet £1 on 'can-upload-same-bugger-false' being the fastest.

**Comment by themoonrat** [comment] 2020-02-11 13:15
Another poke for @politan8  and @jashson  :)

**Comment by themoonrat** [comment] 2020-04-01 07:49
@politan8 @jashson

**Comment by themoonrat** [comment] 2020-04-23 16:08
@bigtimebuddy Unfortunately there's not much I can do here with no follow ups.

I do have a hunch, however, that the latest version of 'isMobile' we upgraded to on dev will solve the issue. This ensures that iPads now reporting as desktop browsers will still get correctly picked up as mobile devices. 

And that's where the performance issue seemed to be here; because when they switched to 'mobile' mode, performance went up.

It's still be nice to know which path of our code is so much slower on iPad desktop ... that's what my 6 builds were to cover. But I think we're good here.

**Comment by bigtimebuddy** [comment] 2020-04-23 16:13
Okay, I'm closing unless anyone has follow-up then we can reopen.

**Closed by bigtimebuddy** 2020-04-23 16:13 UTC
Labels: 🔍 Needs Investigation
