### ISSUE TITLE
Trimming spritesheet-based sprites seems hard in PIXI

### ISSUE THREAD

**Issue by sergebat** [pixijs/pixi.js#2255] opened 2015-12-20 15:54 UTC
"Trimming" sprite is common requirement to implement a progress bar, shooting laser ray, etc.

Looking at the API, it seems that the logical way is to `clone` a texture, then set is `frame` accordingly.

However, if album is exported with texture packer with trim enabled, this does not work, as in this case `trim` property need to be adjusted instead (respecting its `crop` property). If sprite is rotated in texture packer, I guess, things will become even more complex. For now, I disabled texture trimming in my "preloader UI". 

Is there a straightforward way in PIXI to display only a sub-rectangle of Sprite in its local coordinates, independently of underlying texture representation?

**Comment by englercj** [comment] 2015-12-20 17:38
Why can't you just set the frame of the texture?

```js
var frame = sprite.texture.frame;

// modify frame
frame.width--;

// set it so the setter runs and updates the texture UVs
sprite.texture.frame = frame;
```

**Comment by sergebat** [comment] 2015-12-20 19:20
From the `.frame` setter code. If trim is present in the album, frame changes are pretty much ignored. 
```
            if (this.trim)
            {
                this.width = this.trim.width;
                this.height = this.trim.height;
                this._frame.width = this.trim.width;
                this._frame.height = this.trim.height;
            }
            else
            {
                this.crop = frame;
            }
```

**Comment by englercj** [comment] 2015-12-20 20:53
Oh I see, the issue is that you have a trimmed sprite and need to change the frame, but PIXI doesn't let you. That is definitely a bug.

**Comment by GoodBoyDigital** [comment] 2016-08-09 20:30
is this still an issue in v4? Thanks! 👍

**Comment by englercj** [comment] 2016-09-28 15:42
Trim is fully supported now, closing!

**Closed by englercj** 2016-09-28 15:42 UTC
Labels: Domain: API, Resolution: Aged Away, Type: Bug, Version: v4.x
