### ISSUE TITLE
[BUG]: Graphics.beginTextureFill({ texture: PIXI.Texture.EMPTY }) makes lineStyle disappear

### ISSUE THREAD

**Issue by davidye** [pixijs/pixi.js#6563] opened 2020-04-15 18:21 UTC
### Expected Behavior

Line style still shows up when you call beginTextureFill({ texture: PIXI.Texure.EMPTY })

### Current Behavior

Line style disappears when called with beginTextureFill({ texture: PIXI.Texure.EMPTY })

### Possible Solution

Seems like an edge case

### Steps to Reproduce

Modify demo here: https://pixijs.io/examples/#/graphics/advanced.js

```
// beatifulRect.beginFill(0xFF0000);
beatifulRect.beginTextureFill({ texture: PIXI.Texture.EMPTY});
```

### Environment

- **`pixi.js` version**: 5.2.1
- **Browser & Version**: Chrome 80.0.3987.163
- **OS & Version**: macOS Catalina 10.15.4 (19E266)

**Comment by bigtimebuddy** [comment] 2020-04-15 18:39
I agree that's weird.

**Comment by bigtimebuddy** [comment] 2020-04-17 01:00
@davidye After some discussion on the PR #6568, we have decided that this is designed as intended and we won't fix. It is the correct behavior that when an invalid texture is assigned to either the fill or the stroke the whole graphic object (both fill and stroke) will be hidden. Please do not use `Texture.EMPTY` as a texture. If you want some invisible Texture, consider making a 1x1 transparent canvas texture.

If someone would like to make a note in the documentation describing this behavior, PRs welcome.

**Closed** 2020-05-07 17:47 UTC
Labels: 👍 Not A Bug, 🕷 Bug, 🤩 Good First PR
