### ISSUE TITLE
chrome on android not drawing sprite

### ISSUE THREAD

**Issue by dirtslayer** [pixijs/pixi.js#5410] opened 2019-02-05 03:32 UTC
I have a basic pixijs app copied from the tutorial and added some very basic stuff to constrain a sprite to the app rectangle. it works perfectly on  the desktop version of chrome but the android version is not showing my sprite.

source is here: https://github.com/dirtslayer/crib
live online is here: https://dirtslayer.github.io/crib/

**Comment by Dairnon** [comment] 2019-02-08 08:04
I can confirm the sprite shows on desktop but not Android

Sprites do work in android in other demos

You sure it isn't how u set the position that is messing up the android version?

**Comment by themoonrat** [comment] 2019-02-08 13:44
Using Chrome Debugger, you'll see

```
pixi.min.js:8 WebGL: INVALID_VALUE: texImage2D: width or height out of range
e.upload @ pixi.min.js:8
e.upload @ pixi.min.js:8
e.updateTexture @ pixi.min.js:8
e.bind @ pixi.min.js:8
e.flush @ pixi.min.js:8
e.render @ pixi.min.js:8
Wr.render @ pixi.min.js:8
Be.emit @ pixi.min.js:8
Xe.update @ pixi.min.js:8
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._tick @ pixi.min.js:8
requestAnimationFrame (async)
Xe._requestIfNeeded @ pixi.min.js:8
Xe.start @ pixi.min.js:8
start @ pixi.min.js:8
je.init @ pixi.min.js:8
(anonymous) @ pixi.min.js:8
t @ pixi.min.js:8
(anonymous) @ (index):19
(index):1 [.WebGL-0xe1093d00]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
254[.WebGL-0xe1093d00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
(index):1 WebGL: too many errors, no more errors will be reported to the console for this context.
```

**Comment by ivanpopelyshev** [comment] 2019-02-09 15:06
Interesting. something createing texture with zeroed dimensions?

**Comment by ivanpopelyshev** [comment] 2019-02-09 15:43
Oh, right, your texture has width 4320, and most of devices have 4096 limit on that. Use different texture please.

**Comment by themoonrat** [comment] 2019-02-09 15:49
Sounds like it's the issue to me, for sure.
@ivanpopelyshev Do you think there's a good location to put a warning pixi side of either a loaded texture or generated texture is over the device limits?

**Comment by ivanpopelyshev** [comment] 2019-02-09 16:58
yep

**Comment by ivanpopelyshev** [comment] 2019-02-09 17:36
Here is optimal place for that: 

https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/TextureSystem.js#L198 , `this.gl` is the context, `texture.realWidth` is the size. We have to check that `texture.target` is `TEXTURE2D`, add one more `if-else`. There, I coded it in my brain. Its occupied with something else at the moment, so I wont do PR yet.

**Comment by dirtslayer** [comment] 2019-02-10 17:01
Ok sounds good. Thanks. I did not want to change the file because I swiped it from another open spice project and wanted to preserve the original.

**Comment by bigtimebuddy** [comment] 2019-02-27 05:35
I’m going to close this since the issue seems answered. I’ll tag in case someone wants to tackle a better error for outside max texture size in a future PR since this is a reaccuring issue for new users.

**Closed** 2019-02-27 05:36 UTC
Labels: Status: Accepting PRs, Status: Future Work
