### ISSUE TITLE
Setting a mask or filter causes flickering

### ISSUE THREAD

**Issue by chronszcz** [pixijs/pixi.js#3937] opened 2017-04-14 10:33 UTC
Hello,

I'm having an odd issue on a laptop with Intel HD graphics card when using WebGL on EDGE and IE11 only.

Whenever I set a mask or filter, textures get swapped around the scene and end up in different sprites. It causes the whole scene to flicker. I'm using latest PIXI v3 version as it seems to be much faster than v4 on my testing machine.

I'll try to write some example code, but it also seems hardware dependant.

Any help would be appreciated!

**Comment by englercj** [comment] 2017-04-17 03:32
I think this is a duplicate of #3814.

**Closed by englercj** 2017-04-17 03:32 UTC
