### ISSUE TITLE
Problem with lineTo and repeated coordinates

### ISSUE THREAD

**Issue by dmoisset** [pixijs/pixi.js#1075] opened 2014-10-20 19:57 UTC
If I draw a polyline doing 2 consecutive calls to moveTo with the same coordinates, some parts of my line disappear or seem to be in the wrong place

For example
g.moveTo(0,0)
g.moveTo(50,50)
g.moveTo(50,50)
g.moveTo(0,0)

I'm using the webgl renderer

**Comment by edcarstens** [comment] 2015-01-05 04:21
Not sure this is fixed with the new version. I tried the latest version and still see a problem with drawing arms/hands using beginFill, moveTo,  lineTo, and endFill when coordinates happen to align. The symptom is a strange line extrapolation. I'm speculating that it is possibly caused by dividing by a very small number.

**Comment by edcarstens** [comment] 2015-01-05 04:34
The bug is showing up even without the beginFill and endFill calls, so the bug is in the moveTo and/or  lineTo methods. Can this issue be re-opened or should I create a new issue?

**Comment by englercj** [comment] 2015-01-05 05:59
Reopening, we will take a look at it as soon as we can (major core changes going on right now).

**Comment by edcarstens** [comment] 2015-01-18 17:26
I have a simple example that shows this problem clearly. The problem occurs when drawing a "fat" line with a sharp change in direction. I expect it to act like drawing with a fat marker, but instead the algorithm it uses results in an elongated sharp point at the change in direction that may extend off the screen. Try the example below.

// Pixi
// Issue #1075 (bug)
var stage = new PIXI.Stage(0);
// create a renderer instance
var renderer = PIXI.autoDetectRenderer(800, 600);
// add the renderer view element to the DOM
document.body.appendChild(renderer.view);

var g = new PIXI.Graphics();
g.lineStyle(16, 0xffcc66, 1);
g.moveTo(50, 100);
g.lineTo(200, 400);
g.lineTo(75, 100);
g.lineTo(150, 200);
g.lineStyle(1, 0xff0000, 1);
g.moveTo(50, 100);
g.lineTo(200, 400);
g.lineTo(75, 100);
g.lineTo(150, 200);
g.setStageReference(stage);
stage.addChild(g);

// Start animation
requestAnimFrame( animate );

// Animate
function animate() {
    // render the stage
    renderer.render(stage);
}

**Comment by edcarstens** [comment] 2015-01-18 17:53
I have a workaround everyone can use until this bug is fixed. Instead of multiple lineTo's, insert moveTo so that each straight line is drawn separately:

g.moveTo(50, 100);
g.lineTo(200, 400);
g.moveTo(200, 400);
g.lineTo(75, 100);
...

In addition you can use drawCircle and fill it with the line style width set to 1 at each vertex to give the impression of a fat round marker at each vertex.

**Comment by GBagley** [comment] 2015-04-23 23:39
Just got the latest v3 update, but it still has this bug. Any updates? The moveTo workaround Ed mentioned does seem to work, but makes things significantly slower in my case (my app is drawing lots of lines).

**Comment by GBagley** [comment] 2015-06-15 21:49
Bumping this one back up

**Comment by GoodBoyDigital** [comment] 2016-06-11 20:34
example looks good in v4 👍

**Closed by GoodBoyDigital** 2016-06-11 20:34 UTC
Labels: bug, Graphics
