### ISSUE TITLE
Parent Container does not emit any events when "interactiveChildren = false" is set

### ISSUE THREAD

**Issue by dcodeIO** [pixijs/pixi.js#2292] opened 2016-01-15 20:09 UTC
Not sure if this is actually an issue, but it appears to be one. I have a `Container` here that is set to `interactive = true` and `interactiveChildren = false`, which prevents any events to be emitted on the `Container` itself.

The issue seems to originate somewhere around here: https://github.com/pixijs/pixi.js/blob/962f5bdff1ed2d96cfeaef22897ed83b7cce79bd/src/interaction/InteractionManager.js#L410

`Container` neither has `#hitArea` nor `#containsPoint`, which in turn always makes the function return `false`.

When I think about it this could actually be intended, as a container itself doesn't have any real surface to touch or click - the surface are its children. I however expected its bounding box to trigger events, simply because I am able to attach listeners to it and can mark it interactive.

**Comment by englercj** [comment] 2016-01-15 21:13
I'm pretty sure this is intended behavior, but I can understand why it is confusing or even not how it should be. Right now the way to interact directly with a container is to assign it a hitArea, since there is no contains point function bounds checking doesn't occur.

**Comment by GoodBoyDigital** [comment] 2016-01-17 16:03
Hello! Yes this is intended behaviour. The purpose of the feature is to optimise hit detection. Setting interactiveChildren to false makes any children inside the container invisible to the interaction manager. Hope that makes sense!

**Closed by GoodBoyDigital** 2016-01-17 16:03 UTC
