### ISSUE TITLE
Video texture is a green on firefox

### ISSUE THREAD

**Issue by ajiteshsingh** [pixijs/pixi.js#7488] opened 2021-05-14 14:16 UTC
### Expected Behavior
The video texture should have same color without any tint added
<img width="321" alt="Screenshot 2021-05-14 at 7 47 44 PM" src="https://user-images.githubusercontent.com/22662498/118283692-43a3f700-b4ed-11eb-8d0b-011f8b56372d.png">

### Current Behavior
Video texture adds a green tint color
<img width="323" alt="Screenshot 2021-05-14 at 7 45 08 PM" src="https://user-images.githubusercontent.com/22662498/118283354-e7d96e00-b4ec-11eb-905d-85a4e4a50d81.png">

### Possible Solution
-
### Steps to Reproduce
https://jsfiddle.net/zodiacleo/nvb7eh1x/
### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by bigtimebuddy** [comment] 2021-05-14 14:36
Have you:

* determined if this is this specific video or all videos in this environment?
* have you updated your video drivers?
* is this reproducible on other similar platforms?
* does using a video element in HTML produce the same result?
* have you tried using an updated version of pixi?

**Comment by ajiteshsingh** [comment] 2021-05-14 14:48
1. it happens for few specific videos, I have added the link for one of them
2. yes video drivers are updated
3. yes it is reproducible on firefox - https://jsfiddle.net/zodiacleo/nvb7eh1x/
4. Using video element in HTML produces the correct result which is also added in the jsfiddle link
5. yes have tried with the updated version of Pixi as well, same green tint gets added

**Comment by bigtimebuddy** [comment] 2021-05-14 16:22
You seemed to indicate that this is only on specific videos--implying there are some unaffected videos. Have you investigated if this is an encoding/codec issue?

**Comment by bigtimebuddy** [comment] 2021-05-14 17:42
I was able to reproduce this error with WebGL (no PixiJS). 

https://mattkarl.com/bug-webgl-firefox-webm/
https://github.com/bigtimebuddy/bug-webgl-firefox-webm

This seems to be a webm decoding issue with Firefox. You should file an issue with Firefox or use another video format for this browser. Closing this issue.

**Closed by bigtimebuddy** 2021-05-14 17:42 UTC
