### ISSUE TITLE
Pixi Text: size should mean height of the whole text

### ISSUE THREAD

**Issue by tobireif** [pixijs/pixi.js#2331] opened 2016-01-30 12:39 UTC
It would be great if rendered Text would be sized to fully fit into the specified front size, including (ascenders and) descenders. This would be handy when trying to ensure that there's no overlap of the text with other text or image sprites.

When I supply the font size
```
new PIXI.Text(str, {font: "100 px Foo"});
```
and the descenders outgrow the specified 100px, there could be issues because the descenders could overlap other text / image sprites.

Also see http://codepen.io/TobiReif/full/YPawVM/ .

**Comment by ivanpopelyshev** [comment] 2016-01-31 23:11
This stuff is actually the same problem as https://github.com/pixijs/pixi.js/issues/2260 except the cut. PIXI uses HTML5 canvas 2d context when working with text. If you have problems with ascenders and descenders do this:

```javascript
myText.height = 100;
myText.scale.x = myText.scale.y;
```

**Comment by ivanpopelyshev** [comment] 2016-01-31 23:14
Actually, forget what I have said, it will look like shit :( 

The right way is to use Text.determineFontProperties to find correct font size. Look here: https://github.com/pixijs/pixi.js/blob/master/src/core/text/Text.js#L445

**Comment by GoodBoyDigital** [comment] 2016-01-31 23:56
this function has never been perfect im afraid. To get around this fact we added ```padding``` to the text style object. Increase this if you find you font is being cropped and it will solve the issue. :+1:

**Comment by tobireif** [comment] 2016-02-01 09:39
> this function has never been perfect im afraid. 

Perhaps you could leave the ticket open, so that the issues might get resolved sooner or later.

Regarding y-overlap:
```Text.determineFontProperties``` seems to measure the total height, thus I can determine the total height using this function - that's good. But when I supply the font size in ```new PIXI.Text```, the descenders outgrow the specified height. It would be great if Pixi could measure the actual maximum possible height, then render the full text (including descenders) inside the specified pixel height -> no y-overlap of rendered words. Currently, Pixi excludes descenders (see the http://codepen.io/TobiReif/full/YPawVM/ ).

Regarding cropped text:
Some web-apps use various fonts dynamically, it would be great if it wouldn't be necessary to manually set the "padding" property. Perhaps ```determineFontProperties``` would become more accurate it it would include some more descending characters? (eg '|MÉq' -> '|MÉqgyf') Otherwise perhaps the code  of these libs could help to get it right:
https://github.com/motiz88/canvas-text-metrics-polyfill
http://pomax.github.io/fontmetrics.js/
http://bl.ocks.org/eweitnauer/7324712
https://github.com/Pomax/Font.js

**Comment by ivanpopelyshev** [comment] 2016-02-01 10:22
@tobireif make a pull request.

**Comment by tobireif** [comment] 2016-02-01 10:36
Ideally I could find the time ...

**Comment by tobireif** [comment] 2016-02-01 13:40
Regarding y-overlap: (not regarding cropped text):

@GoodBoyDigital Perhaps I could see whether it's quick to include the descenders so that text fits completely into the height specified in ```new PIXI.Text```. But: Do you agree? And: It would break existing web-apps/games/etc, so perhaps it should be done in v4.

**Comment by ivanpopelyshev** [comment] 2016-02-01 14:00
@tobireif Make getter and setter for "fontSize" property in text. Getter calls "determineFontProperties", while setter parses current font and calculates correct pixel size for it.

Dont forget that user can pass us a list of fonts, "8px Arial, 10px Courier" or something like that, and we really dont know which one is actually used. Modify all of them.

**Comment by tobireif** [comment] 2016-02-01 18:12
@ivanpopelyshev Thanks for the tips. I might attempt to create a PR, but this issue ticket here is closed, so there might be no interest. Also, there are the open questions in my previous comment.

**Comment by ivanpopelyshev** [comment] 2016-02-01 18:55
@tobireif I added it to our private trello for v4 :+1:

**Comment by tobireif** [comment] 2016-02-01 18:57
Thanks!

**Comment by GoodBoyDigital** [comment] 2016-02-01 22:35
may have closed that one a bit quick :)

**Comment by tobireif** [comment] 2016-02-02 10:08
Regarding y-overlap / descenders growing out of the specified font size:

I asked Chris Lilley (editor / co-editor of various CSS specs):
https://twitter.com/svgeesus/status/694272964955627520
"Does CSS font-size include the descenders?"
"it should include them, yes."

So from a CSS-viewpoint (and to prevent overlap) the descenders should not overgrow the specified height -> the whole height of the rendered text should fit inside the specified height.

He also wrote "Unless the glyphs go outside the declared descender level" - for that we could measure some more "potentially descending characters" and we probably will have to keep the "padding" property.

**Comment by staff0rd** [comment] 2016-06-30 09:25
What's the magic `1.4` [here](https://github.com/pixijs/pixi.js/blob/ff4b027dd1ef05b586bf926601d3b932b1973f2c/src/core/text/Text.js#L476)?

I've got a scenario where I'm setting the scale and resolution on a `PIXI.Text` with `fontFamily: "Arial"`.  Doing so cuts the bottom of the letter _g_.  I commented out the line above, and the problem is fixed.  

[Later in that code](https://github.com/pixijs/pixi.js/blob/ff4b027dd1ef05b586bf926601d3b932b1973f2c/src/core/text/Text.js#L488), it looks like height is set by `baseline`, but `baseline` was calculated from `context.measureText('M').width`, so I'm not sure of what the intention is.

**Comment by GoodBoyDigital** [comment] 2016-08-09 20:28
fixed in v4 I believe! 👍

**Closed by GoodBoyDigital** 2016-08-09 20:28 UTC
