### ISSUE TITLE
WebGL Filters + Resolution = 2

### ISSUE THREAD

**Issue by rich-earth** [pixijs/pixi.js#3646] opened 2017-01-24 16:42 UTC
When working with 2x resolution rederer, if you apply any filter to a Sprite with a @2x texture, the filter renders the Sprite at 1x resolution, so looks blurry. 

See fiddle below, image on the left has no filter and looks crisp, same image in right with filter applied looked blurry rendered at 1x

You may need retina screen to see the problem...
http://jsfiddle.net/xpmbrqc9/

**Comment by themoonrat** [comment] 2017-01-24 17:01
If you give the latest dev build 
http://pixijs.download/dev/pixi.js
I believe there have been recent commits to fix that issue. Could you give it a go please?

**Comment by ivanpopelyshev** [comment] 2017-01-24 17:03
```
filter.resolution = 2;
```

That way it works. The problem is why it didnt work by default?

**Comment by rich-earth** [comment] 2017-01-24 17:06
Hey thanks guys
Confirm manually setting the filter res works.   Using the dev pixi didn't 

Cheers

**Comment by themoonrat** [comment] 2017-01-24 17:31
Oh :/ I'd hoped https://github.com/pixijs/pixi.js/pull/3614 would have covered this @ivanpopelyshev

**Comment by bigtimebuddy** [comment] 2017-01-24 17:47
@rich-earth 

If you use the dev branch and add: `PIXI.settings.RESOLUTION = 2;` to the top of the fiddle, it should render correctly without setting the resolution on the filter.

**Comment by rich-earth** [comment] 2017-01-24 18:06
Bonus! 👍

**Comment by ivanpopelyshev** [comment] 2017-01-24 18:55
@themoonrat I didn't know about that thing. 

@bigtimebuddy that means we can close it :)

**Closed by ivanpopelyshev** 2017-01-24 18:55 UTC
