### ISSUE TITLE
PIXI for node js

### ISSUE THREAD

**Issue by human211** [pixijs/pixi.js#7437] opened 2021-04-22 15:27 UTC
Is it possible to do support for node js? I need this for rendering on serverside.
For example node-canvas-webgl (https://github.com/akira-cn/node-canvas-webgl) works fine with threejs without any additional code.
If I try to run pixi the same way it won't work ... a lot of errors.
I have to write something like:
```
import * as PIXI from 'pixi.js';
window.PIXI = global.PIXI = PIXI;
const _canvasTest = (PIXI as any).CanvasResource.test;
(PIXI as any).CanvasResource.test = function (source: any) {
  return _canvasTest(source) || source instanceof Canvas; // Canvas from node-canvas
};
```
Thanks!

**Comment by bigtimebuddy** [comment] 2021-04-22 16:06
SSR is not yet supported but is on our roadmap. Duplicate of #6990

**Closed by bigtimebuddy** 2021-04-22 16:06 UTC
