### ISSUE TITLE
TilingSprite In Canvas Does Not Adjust for Texture and Renderer Resolutions

### ISSUE THREAD

**Issue by tjkopena** [pixijs/pixi.js#2083] opened 2015-09-06 22:37 UTC
I believe there is a bug in the canvas rendering of TilingSprites such that they do not properly adjust for texture and renderer resolutions of more than 1.  Seems like #1371 was perhaps not addressed for canvas? I'm working from Pixi 3.08-dev, f5abaa7060bd1347cfd0506ab2b60db9fc8c9f19 and also saw this in the 3.07 build from the repo.  I'm testing on my Samsung S3 using Firefox and Chrome.  Chrome on the S3 won't use WebGL, which is how I first noticed the issue and eventually realized it was a problem with canvas rendering.

In my test program, I get this expected output when using WebGL; pink is the background, and everything else is a single TilingSprite scaled to the screen width:

![screenshot_2015-09-06-17-53-45-sm](https://cloud.githubusercontent.com/assets/1175848/9706950/1f7c1278-54c6-11e5-9797-62b821eee714.png)

In canvas rendering however, the texture is doubled in size:

![screenshot_2015-09-06-17-54-14-sm](https://cloud.githubusercontent.com/assets/1175848/9706952/245bbe4c-54c6-11e5-8789-399b335ee846.png)

I'm setting the renderer resolution to window.devicePixelRatio, which is 2.  The base texture also has resolution 2 (when on a high resolution device).

The program (forcing canvas) is here:

http://rocketshipgames.com/tmp/bugs/20150906-pixi-tilingsprite/

Thx

**Comment by staff0rd** [comment] 2016-09-12 07:05
I was messing around in this space because I thought I had found a WebGL TilingSprite resolution issue.  [This pen](https://codepen.io/staff0rd/pen/amvxYV?editors=0010) however proves that as per @tjkopena, the issue is only in CanvasRenderer.

The following is Sprite, Sprite@2x, TilingSprite, TilingSprite@2;

### WebGL
![image](https://cloud.githubusercontent.com/assets/6289998/18427382/ef8f19d8-790a-11e6-90ae-beec1d4c7855.png)

### CanvasRenderer 
![image](https://cloud.githubusercontent.com/assets/6289998/18427337/b7c6c5fa-790a-11e6-9ab1-7b76c50e8a4c.png)

https://codepen.io/staff0rd/pen/amvxYV?editors=0010

**Comment by themoonrat** [comment] 2016-09-12 07:36
@GoodBoyDigital - There was a PR fix for this, https://github.com/pixijs/pixi.js/pull/2381, that got merged into dev, but doesn't appear in the code anymore?

**Comment by englercj** [comment] 2016-09-28 04:07
@GoodBoyDigital Any idea why this is missing now, or if this is fixed?

**Comment by staff0rd** [comment] 2016-09-28 04:16
Updated the pen to point at //s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.js

Still broken; https://codepen.io/staff0rd/pen/amvxYV?editors=0010

**Comment by themoonrat** [comment] 2017-01-01 21:42
@staff0rd But looks fixed when I've checked it now! Issue could now be closed?

**Comment by staff0rd** [comment] 2017-01-01 22:48
Fixed

**Closed by staff0rd** 2017-01-01 22:48 UTC
Labels: Domain: API, Plugin: Tiling Sprite, Priority: Medium, Renderer: Canvas, Type: Bug, Version: v4.x
