### ISSUE TITLE
Mesh examples not working

### ISSUE THREAD

**Issue by Cristy94** [pixijs/pixi.js#4807] opened 2018-03-27 16:58 UTC
The examples here are not working: http://pixijs.io/examples/#/mesh/triangle.js

The error is `Uncaught TypeError: PIXI.Geometry is not a constructor`

**Comment by bigtimebuddy** [comment] 2018-03-27 18:01
Duplicate of #4795

**Closed by bigtimebuddy** 2018-03-27 18:01 UTC
