### ISSUE TITLE
Opacity on lines borked

### ISSUE THREAD

**Issue by georeith** [pixijs/pixi.js#6560] opened 2020-04-15 14:23 UTC
### Expected Behavior

Should be able to add opacity to a line

### Current Behavior

Where the line overlaps in a curve streaks appear in it.

![image](https://user-images.githubusercontent.com/3090066/79348278-b4fd2900-7f2c-11ea-8171-940e60a366bd.png)

### Possible workaround

Draw the line solid, render to a texture and then apply opacity (can be seen by applying `circle.cacheAsBitmap = true` to the attached pixiplayground). This suffers a loss of fidelity in the curve though.

### Steps to Reproduce

Create an ellipse or curve and put a line on it

### Environment

- **`pixi.js` version**:  5.2.1
- **Browser & Version**:  Chrome 80
- **OS & Version**:  Mac OS Mojave
- **Running Example**: https://pixiplayground.com/#/edit/A22hhBZYvo9FlcJOaUAHa

**Comment by ivanpopelyshev** [comment] 2020-04-15 15:23
Someone modified that example, i dont see a problem there.

**Comment by ivanpopelyshev** [comment] 2020-04-15 15:25
The problem is known , and it would be good if you point me to WebGL renderer that solved ;)

however, it might work with whatever we have in dev, because @SukantPal worked on joints a bit.

put "https://pixijs.download/dev/pixi.js" in setting of that playground - that will be saved only if you modify source too - that's the bug of playground

**Comment by georeith** [comment] 2020-04-15 15:40
> Someone modified that example, i dont see a problem there.
I updated the link. Not sure what happened there.

> and it would be good if you point me to WebGL renderer that solved ;)
Don't know of any open source ones.

**Comment by bigtimebuddy** [comment] 2020-04-15 16:37
There are a lot of easy workaround for this issue. The underlying issues is complicated to solve because of how the strokes are tessellated. Some workarounds:

* use AlphaFilter [example](https://pixiplayground.com/#/edit/P0yxYXLIm2PNCqUopWgpl)
* use cacheAsBitmap [example](https://pixiplayground.com/#/edit/ombAeA24WC8tcd3ij7GHZ)
* don't use strokes, convert your shapes to fills
* use a parallel CanvasRenderer, which shouldn't have these issues

**Comment by georeith** [comment] 2020-04-15 20:07
Sorry miss pressed close there.

Thanks @bigtimebuddy just evaluating the alternatives you suggested:

- `AlphaFilter`: it works but destroys the crispness of the lines, would require some sort of anti-aliasing on top not sure if I can maintain the fidelity of edges to an acceptable degree here.
- `useCacheAsBitmap`: same as above ^
- Don't use strokes: convert your strokes to fills. Very difficult in my case as these are not pre-generated assets but parameterised assets in a vector drawing tool so would need a general case solution for stroke conversion to outlines which isn't cheap, especially as they can then edit these strokes on the fly.
- use a parallel CanvasRenderer: possibly the best solution? Doesn't require antialiasing, worried about how it scales as I need to do this to thousands of vectors.

**Comment by SukantPal** [comment] 2020-04-15 20:11
@georeith I think you can take create a custom renderer for graphics using `pluginName`. Your renderer will then use the depth buffer to eliminate overlapping fragments.

Tell me if you need help with that. 

https://github.com/pixijs/pixi-batch-renderer might be too complicated; however, if you have _thousands_ of vectors, you might want to create a batch renderer that fixes this issue as well.

**Comment by georeith** [comment] 2020-04-15 20:38
Thanks @SukantPal I need a bit to digest this information as I'm very new to WebGL and the concepts of batching etc. I'm going to drop you a line if thats OK as I have a lot of features and this is part of a larger project and want to make sure of the suitability of the approach.

**Comment by SukantPal** [comment] 2020-04-15 20:42
@georeith Come over to our slack workspace so you can ping me when you need: https://join.slack.com/t/pixijs/shared_invite/zt-dcem1map-uVuVGC7pZ0trF8SrcA2p9g, :)

**Comment by bigtimebuddy** [comment] 2020-04-15 22:37
@ivanpopelyshev introduced multisampling in dev (will be in 5.3.0). You will be able to do something like this which is rendering your graphics to a RenderTexture.

https://jsfiddle.net/bigtimebuddy/6tzyv91j/

Ignore the issue with ellipse stroke in the middle, we have a fix for that in the queue.

**Closed** 2020-05-07 17:48 UTC
