### ISSUE TITLE
[ERROR] About an error :  "WebGL: INVALID_ENUM: activeTexture: texture unit out of range"

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi.js#3426] opened 2016-12-08 14:39 UTC
the code at

https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js#L275-L295

Sometimes ,  ```t._enabled ``` always equals ```TICK``` , then the nextTexture._virtalBoundId always be ```-1```.

And there is an error on browser's console : 
```
WebGL: INVALID_ENUM: activeTexture: texture unit out of range
```

**Comment by bigtimebuddy** [comment] 2016-12-08 14:44
Duplicate of #3373

**Closed by bigtimebuddy** 2016-12-08 14:44 UTC

**Comment by finscn** [comment] 2016-12-08 15:15
@bigtimebuddy  , OK. I've add more informations  at  https://github.com/pixijs/pixi.js/issues/3373#issuecomment-265764333

I hope it could help you to find the key point of this issues.

**Comment by bigtimebuddy** [comment] 2016-12-08 17:00
Thank you @finscn!
