### ISSUE TITLE
PIXI.Text align:right doesn't work

### ISSUE THREAD

**Issue by cawoodm** [pixijs/pixi.js#4341] opened 2017-10-01 17:26 UTC
PIXI.Text align:right doesn't work (Canvas, v4.5.5, Windows 10, Chrome).

```javascript
new PIXI.Text("Hello", {
    fontFamily : "Arial", fontSize: 24, fill : 0xffffff, align: "right"
});
```

Text appears aligned left and grows to the right from it's `.x` coordinate.

**Comment by ivanpopelyshev** [comment] 2017-10-01 17:48
I think its for multiline. May be you just want to set anchor to (1.0, 0.0) ?

**Comment by bigtimebuddy** [comment] 2017-10-01 17:56
Check out https://pixijs.github.io/pixi-text-style/ to see how this is used.

**Comment by bigtimebuddy** [comment] 2017-10-01 19:32
Also, before posting a new issue @cawoodm, you might want to search existing closed and open issues. This one is a duplicate of these: #4002 #3476

**Closed by bigtimebuddy** 2017-10-01 19:32 UTC
